#include "CommandPayload.hpp"
#include <algorithm>
#include <cctype>
#include <climits>
#include <cstdlib>

namespace bee { namespace {
bool digits(const std::string& value, size_t min, size_t max) {
  return value.size() >= min && value.size() <= max &&
    std::all_of(value.begin(), value.end(), [](unsigned char c){ return std::isdigit(c) != 0; });
}
bool decimal(const std::string& value, size_t integerDigits, size_t fractionDigits, bool positive) {
  if(value.empty() || value[0]=='+' || value[0]=='-') return false;
  const auto dot=value.find('.');
  if(dot!=std::string::npos && value.find('.',dot+1)!=std::string::npos) return false;
  const auto integers=dot==std::string::npos?value.size():dot;
  const auto fraction=dot==std::string::npos?0:value.size()-dot-1;
  if(integers<1 || integers>integerDigits || fraction>fractionDigits || (dot!=std::string::npos&&fraction==0)) return false;
  for(size_t i=0;i<value.size();++i) if(i!=dot && !std::isdigit(static_cast<unsigned char>(value[i]))) return false;
  if(positive && std::all_of(value.begin(),value.end(),[](char c){return c=='0'||c=='.';})) return false;
  return true;
}
bool signedDecimal(const std::string& value,size_t integerDigits,size_t fractionDigits){if(value.empty()||value[0]=='+')return false;return value[0]=='-'?decimal(value.substr(1),integerDigits,fractionDigits,false):decimal(value,integerDigits,fractionDigits,false);}
bool safeText(const std::string& value,size_t max) {
  return !value.empty() && value.size()<=max && std::none_of(value.begin(),value.end(),[](char c){return c=='\t'||c=='\r'||c=='\n'||static_cast<unsigned char>(c)<0x20;});
}
bool optionalSafeText(const std::string& value,size_t max) {
  return value.empty() || safeText(value,max);
}
bool validUNP(const std::string& value) {
  if(value.size()!=21 || value[8]!='-' || value[13]!='-') return false;
  if(!std::isupper(static_cast<unsigned char>(value[0])) || !std::isupper(static_cast<unsigned char>(value[1]))) return false;
  for(size_t i=2;i<8;i++) if(!std::isdigit(static_cast<unsigned char>(value[i]))) return false;
  for(size_t i=9;i<13;i++) if(!std::isupper(static_cast<unsigned char>(value[i]))&&!std::isdigit(static_cast<unsigned char>(value[i]))) return false;
  for(size_t i=14;i<21;i++) if(!std::isdigit(static_cast<unsigned char>(value[i]))) return false;
  return true;
}
void append(std::vector<uint8_t>& out,const std::string& value){out.insert(out.end(),value.begin(),value.end());}
void tab(std::vector<uint8_t>& out){out.push_back(0x09);}
std::vector<std::string> split(const std::vector<uint8_t>& raw,char separator){std::vector<std::string> out(1);for(uint8_t c:raw){if(c==static_cast<uint8_t>(separator))out.emplace_back();else out.back().push_back(static_cast<char>(c));}while(!out.empty()&&out.back().empty())out.pop_back();return out;}
bool uint32Value(const std::string& value,uint32_t& out){if(!digits(value,1,10))return false;unsigned long x=std::strtoul(value.c_str(),nullptr,10);if(x>UINT_MAX)return false;out=static_cast<uint32_t>(x);return true;}
bool uint64Value(const std::string& value,uint64_t& out){if(!digits(value,1,10))return false;char* end=nullptr;unsigned long long x=std::strtoull(value.c_str(),&end,10);if(!end||*end!='\0')return false;out=static_cast<uint64_t>(x);return true;}
bool datePrefix(const std::string& value,bool withTime){const size_t need=withTime?17:8;if(value.size()<need)return false;const size_t separators[]={2,5};for(size_t i=0;i<8;i++){if(i==separators[0]||i==separators[1]){if(value[i]!='-')return false;}else if(!std::isdigit(static_cast<unsigned char>(value[i])))return false;}if(!withTime)return true;if(value[8]!=' '||value[11]!=':'||value[14]!=':')return false;for(size_t i=9;i<17;i++)if(i!=11&&i!=14&&!std::isdigit(static_cast<unsigned char>(value[i])))return false;return true;}
bool fullDateTime(const std::string& value){if(value.size()!=19||value[2]!='-'||value[5]!='-'||value[10]!=' '||value[13]!=':'||value[16]!=':')return false;for(size_t i=0;i<value.size();i++)if(i!=2&&i!=5&&i!=10&&i!=13&&i!=16&&!std::isdigit(static_cast<unsigned char>(value[i])))return false;return true;}
bool documentedDateTime(const std::string& value){return datePrefix(value,true)||fullDateTime(value);}
bool daisyDate(const std::string& value){return value.size()==6&&digits(value,6,6);}
bool daisyDateTime(const std::string& value){
  if(value.size()!=17||value[2]!='.'||value[5]!='.'||value[8]!=' '||value[11]!=':'||value[14]!=':')return false;
  for(size_t i=0;i<value.size();i++)if(i!=2&&i!=5&&i!=8&&i!=11&&i!=14&&!std::isdigit(static_cast<unsigned char>(value[i])))return false;
  return true;
}
bool daisyLongDateTime(const std::string& value){
  if(value.size()!=19||value[2]!='.'||value[5]!='.'||value[10]!=' '||value[13]!=':'||value[16]!=':')return false;
  for(size_t i=0;i<value.size();i++)if(i!=2&&i!=5&&i!=10&&i!=13&&i!=16&&!std::isdigit(static_cast<unsigned char>(value[i])))return false;
  return true;
}
bool countAmount(const std::string& value,DaisyCountAmount& out){const auto pos=value.find(';');if(pos==std::string::npos||value.find(';',pos+1)!=std::string::npos||!uint32Value(value.substr(0,pos),out.count)||!decimal(value.substr(pos+1),10,2,false))return false;out.amount=value.substr(pos+1);return true;}
bool sha1ReportValue(const std::string& value){if(value.size()!=47||value[23]!='\n')return false;for(size_t i=0;i<value.size();i++){if(i==5||i==11||i==17||i==29||i==35||i==41){if(value[i]!='-')return false;}else if(i!=23&&!std::isxdigit(static_cast<unsigned char>(value[i])))return false;}return true;}
bool daisyDateOrUnset(const std::string& value){return value=="XXXXXX"||daisyDate(value);}
bool exactDecimal(const std::string& value,size_t integerDigits,size_t fractionDigits){
  const auto dot=value.find('.');return decimal(value,integerDigits,fractionDigits,false)&&dot!=std::string::npos&&value.size()-dot-1==fractionDigits;
}
bool fiscalMemoryDateTime(const std::string& value){if(documentedDateTime(value))return true;if(value.size()!=16||value[2]!='-'||value[5]!='-'||value[10]!=' '||value[13]!=':')return false;for(size_t i=0;i<value.size();i++)if(i!=2&&i!=5&&i!=10&&i!=13&&!std::isdigit(static_cast<unsigned char>(value[i])))return false;return true;}
bool negativeInt(const std::string& value,int& out){if(value.size()<2||value[0]!='-'||!digits(value.substr(1),1,6))return false;long x=std::strtol(value.c_str(),nullptr,10);if(x<INT_MIN||x>=0)return false;out=static_cast<int>(x);return true;}
bool negativeOrZeroInt(const std::string& value,int& out,int minimum){if(value=="0"){out=0;return true;}if(!negativeInt(value,out)||out<minimum)return false;return true;}
bool hexAddress(const std::string& value){return value.size()>=1&&value.size()<=6&&std::all_of(value.begin(),value.end(),[](unsigned char c){return std::isdigit(c)||(c>='A'&&c<='F');});}
bool upperHex(const std::string& value,size_t exact){return value.size()==exact&&std::all_of(value.begin(),value.end(),[](unsigned char c){return std::isdigit(c)||(c>='A'&&c<='F');});}
bool printableAscii(const std::string& value,size_t max){return !value.empty()&&value.size()<=max&&std::all_of(value.begin(),value.end(),[](unsigned char c){return c>=0x20&&c<=0x7f;});}
bool qrTemplateId(const std::string& value){static const char* ids[]={"CLB","DNO","DPT","DT","PLU","PRC","QTY","SAL","SN","SUM","TAM","TAX","TDS","TMU","TXT","CLE"};return std::any_of(std::begin(ids),std::end(ids),[&](const char* id){return value==id;});}
int hexNibble(char c){if(c>='0'&&c<='9')return c-'0';if(c>='A'&&c<='F')return c-'A'+10;return -1;}
bool base64Data(const std::string& value){if(value.empty()||value.size()>4096||value.size()%4!=0)return false;size_t padding=0;for(size_t i=0;i<value.size();i++){char c=value[i];if(c=='='){padding++;if(i<value.size()-2||padding>2)return false;}else if(padding||!(std::isalnum(static_cast<unsigned char>(c))||c=='+'||c=='/'))return false;}return true;}
uint64_t documentLimit(uint8_t type){return type==2?3650:(type==3||type==7?9999999999ULL:9999999ULL);}
}

bool buildDaisyOpenReceipt(const OpenReceiptPayload& in,std::vector<uint8_t>& out,std::string& error){
  if(in.operatorNumber<1||in.operatorNumber>30||!digits(in.password,1,6)||!validUNP(in.unp)){error="DAISY_OPEN_FIELDS";return false;}
  out.clear();append(out,std::to_string(in.operatorNumber));out.push_back(',');append(out,in.password);out.push_back(',');append(out,in.unp);if(in.invoice){tab(out);out.push_back('I');}return true;
}
bool buildDaisyOpenReversal(const ReversalOpenPayload&in,std::vector<uint8_t>&out,std::string&error){if(in.operatorNumber<1||in.operatorNumber>30||in.password.empty()||in.password.size()>8||!validUNP(in.unp)||in.reason>2||in.originalDocument<1||in.originalDocument>9999999||!documentedDateTime(in.originalDateTime)||!safeText(in.fiscalMemoryNumber,13)){error="DAISY_REVERSAL_FIELDS";return false;}out.clear();append(out,std::to_string(in.operatorNumber));out.push_back(',');append(out,in.password);out.push_back(',');append(out,in.unp);tab(out);out.push_back('R');append(out,std::to_string(in.reason));out.push_back(',');append(out,std::to_string(in.originalDocument));out.push_back(',');append(out,in.originalDateTime);tab(out);append(out,in.fiscalMemoryNumber);return true;}
bool buildDatecsOpenReceipt(const OpenReceiptPayload& in,std::vector<uint8_t>& out,std::string& error){
  if(in.operatorNumber<1||in.operatorNumber>30||!digits(in.password,1,8)||!validUNP(in.unp)||in.tillNumber<1||in.tillNumber>99999){error="DATECS_OPEN_FIELDS";return false;}
  out.clear();append(out,std::to_string(in.operatorNumber));tab(out);append(out,in.password);tab(out);append(out,in.unp);tab(out);append(out,std::to_string(in.tillNumber));tab(out);if(in.invoice)out.push_back('I');tab(out);return true;
}
bool buildDaisySaleItem(const SaleItemPayload& in,std::vector<uint8_t>& out,std::string& error){
  if(!safeText(in.name,72)||in.taxGroup<'A'||in.taxGroup>'H'||!decimal(in.unitPrice,8,2,true)||!decimal(in.quantity,8,3,true)||in.discountType>4||(in.discountType&& !decimal(in.discountValue,8,2,true))){error="DAISY_ITEM_FIELDS";return false;}
  out.clear();append(out,in.name);tab(out);out.push_back(static_cast<uint8_t>(0xC0+(in.taxGroup-'A')));append(out,in.unitPrice);if(in.quantity!="1.000"){out.push_back('*');append(out,in.quantity);}if(in.discountType){out.push_back(in.discountType<=2?',':'$');out.push_back((in.discountType==1||in.discountType==3)?'+':'-');append(out,in.discountValue);}return true;
}
bool buildDatecsSaleItem(const SaleItemPayload& in,std::vector<uint8_t>& out,std::string& error){
  if(!safeText(in.name,72)||in.taxGroup<'A'||in.taxGroup>'H'||!decimal(in.unitPrice,7,2,true)||!decimal(in.quantity,6,3,true)||in.discountType>4||(in.discountType&& !decimal(in.discountValue,7,2,true))||in.department>99||(!in.unit.empty()&&!safeText(in.unit,6))){error="DATECS_ITEM_FIELDS";return false;}
  out.clear();append(out,in.name);tab(out);append(out,std::to_string(in.taxGroup-'A'+1));tab(out);append(out,in.unitPrice);tab(out);append(out,in.quantity);tab(out);if(in.discountType)append(out,std::to_string(in.discountType));tab(out);if(in.discountType)append(out,in.discountValue);tab(out);append(out,std::to_string(in.department));tab(out);append(out,in.unit);tab(out);return true;
}
bool buildDaisyPayment(const PaymentPayload& in,std::vector<uint8_t>& out,std::string& error){
  const std::string allowed="PNCDUBE";if(allowed.find(in.daisyPaymentCode)==std::string::npos||!decimal(in.amount,8,2,true)){error="DAISY_PAYMENT_FIELDS";return false;}out.clear();tab(out);out.push_back(static_cast<uint8_t>(in.daisyPaymentCode));append(out,in.amount);return true;
}
bool buildDatecsPayment(const PaymentPayload& in,std::vector<uint8_t>& out,std::string& error){
  if(in.datecsPaidMode>5||!decimal(in.amount,7,2,true)){error="DATECS_PAYMENT_FIELDS";return false;}out.clear();append(out,std::to_string(in.datecsPaidMode));tab(out);append(out,in.amount);tab(out);return true;
}
bool buildDaisyDailyReport(bool zReport,std::vector<uint8_t>& out){out.assign(1,static_cast<uint8_t>(zReport?'0':'2'));return true;}
bool buildDatecsDailyReport(bool zReport,std::vector<uint8_t>& out){out.assign(1,static_cast<uint8_t>(zReport?'Z':'X'));tab(out);return true;}
bool buildDaisyCashMovement(const CashMovementPayload& in,std::vector<uint8_t>& out,std::string& error){
  if(!decimal(in.amount,7,2,true)){error="DAISY_CASH_FIELDS";return false;}out.clear();if(in.cashOut)out.push_back('-');append(out,in.amount);out.push_back(',');tab(out);append(out,"$EUR");return true;
}
bool buildDatecsCashMovement(const CashMovementPayload& in,std::vector<uint8_t>& out,std::string& error){
  if(!decimal(in.amount,7,2,true)){error="DATECS_CASH_FIELDS";return false;}out.clear();out.push_back(in.cashOut?'1':'0');tab(out);append(out,in.amount);tab(out);return true;
}
bool buildDaisyTaxRatesPeriod(const std::string& startDate,const std::string& endDate,std::vector<uint8_t>& out,std::string& error){
  if((startDate.empty())!=endDate.empty()||(!startDate.empty()&&(!daisyDate(startDate)||!daisyDate(endDate)||startDate.substr(4,2)+startDate.substr(2,2)+startDate.substr(0,2)>endDate.substr(4,2)+endDate.substr(2,2)+endDate.substr(0,2)))){error="DAISY_TAX_PERIOD";return false;}
  out.clear();if(!startDate.empty()){append(out,startDate);out.push_back(',');append(out,endDate);}return true;
}
bool buildDaisySubtotal(const SubtotalPayload& in,std::vector<uint8_t>& out,std::string& error){
  if(in.discountType>4||(in.discountType==0&&!in.discountValue.empty())||(in.discountType!=0&&!decimal(in.discountValue,10,2,true))){error="DAISY_SUBTOTAL_FIELDS";return false;}
  out.clear();out.push_back(in.print?'1':'0');out.push_back(in.display?'1':'0');
  if(in.discountType){out.push_back(in.discountType<=2?',':'$');out.push_back((in.discountType==1||in.discountType==3)?'+':'-');append(out,in.discountValue);}return true;
}
bool buildDaisyFiscalTotals(char type,std::vector<uint8_t>& out,std::string& error){
  if(type!='N'&&type!='T'&&type!='\0'){error="DAISY_FISCAL_TOTAL_TYPE";return false;}out.clear();if(type!='\0')out.push_back(static_cast<uint8_t>(type));return true;
}
bool buildDaisyDiagnostic(bool calculate,std::vector<uint8_t>& out){out.clear();if(calculate)out.push_back('1');return true;}
bool buildDaisyErrorDescription(uint8_t code,std::vector<uint8_t>& out,std::string& error){if(code<1||code>127){error="DAISY_ERROR_NUMBER";return false;}out.clear();append(out,std::to_string(code));return true;}
bool buildDaisyCurrencyTransition(char operation,uint8_t number,std::vector<uint8_t>& out,std::string& error){
  if((operation!='I'&&operation!='R')||(operation=='I'&&number!=0)||(operation=='R'&&(number<1||number>4))){error="DAISY_CURRENCY_TRANSITION_REQUEST";return false;}out.clear();out.push_back(static_cast<uint8_t>(operation));if(operation=='R')append(out,std::to_string(number));return true;
}
bool buildDaisySaleAndDisplay(const SaleItemPayload& in,std::vector<uint8_t>& out,std::string& error){return buildDaisySaleItem(in,out,error);}
bool buildDaisyProgrammedItem(const DaisyProgrammedItemPayload& in,std::vector<uint8_t>& out,std::string& error){
  if(in.pluNumber.empty()||in.pluNumber.size()>32||!std::all_of(in.pluNumber.begin(),in.pluNumber.end(),[](unsigned char c){return std::isalnum(c)!=0;})||(!in.quantity.empty()&&!decimal(in.quantity,8,3,true))||(!in.price.empty()&&!decimal(in.price,8,2,true))||in.discountType>4||(in.correction&&in.discountType)||(in.discountType==0&&!in.discountValue.empty())||(in.discountType!=0&&!decimal(in.discountValue,8,2,true))){error="DAISY_PROGRAMMED_ITEM";return false;}out.clear();if(in.correction)out.push_back('-');append(out,in.pluNumber);if(!in.quantity.empty()&&in.quantity!="1.000"){out.push_back('*');append(out,in.quantity);}if(!in.price.empty()){out.push_back('@');append(out,in.price);}if(in.discountType){out.push_back(in.discountType<=2?',':'$');out.push_back((in.discountType==1||in.discountType==3)?'+':'-');append(out,in.discountValue);}return true;
}
bool buildDaisyFiscalMemoryNumberReport(uint16_t first,uint16_t last,bool payments,std::vector<uint8_t>& out,std::string& error){if(first<1||last<first||last>9999){error="DAISY_FM_NUMBER_REPORT";return false;}out.clear();append(out,std::to_string(first));out.push_back(',');append(out,std::to_string(last));if(payments)append(out,",PAY");return true;}
bool buildDaisyFiscalMemoryDateReport(const std::string& first,const std::string& last,bool payments,std::vector<uint8_t>& out,std::string& error){if(!daisyDate(first)||!daisyDate(last)||first.substr(4,2)+first.substr(2,2)+first.substr(0,2)>last.substr(4,2)+last.substr(2,2)+last.substr(0,2)){error="DAISY_FM_DATE_REPORT";return false;}out.clear();append(out,first);out.push_back(',');append(out,last);if(payments)append(out,",PAY");return true;}
bool buildDaisyDailyReportOption(uint8_t operation,bool keepOperatorTotals,std::vector<uint8_t>& out,std::string& error){const uint8_t allowed[]={0,1,2,3,5,6,8,9};if(std::find(std::begin(allowed),std::end(allowed),operation)==std::end(allowed)){error="DAISY_DAILY_REPORT_OPTION";return false;}out.clear();out.push_back(static_cast<uint8_t>('0'+operation));if(keepOperatorTotals)out.push_back('N');return true;}
bool buildDaisyPluReport(char type,std::vector<uint8_t>& out,std::string& error){if(type!='\0'&&type!='0'&&type!='1'&&type!='Z'){error="DAISY_PLU_REPORT";return false;}out.clear();if(type!='\0')out.push_back(static_cast<uint8_t>(type));return true;}
bool buildDaisyDepartmentReport(char type,std::vector<uint8_t>& out,std::string& error){if(type!='\0'&&type!='0'&&type!='1'&&type!='X'&&type!='Z'){error="DAISY_DEPARTMENT_REPORT";return false;}out.clear();if(type!='\0')out.push_back(static_cast<uint8_t>(type));return true;}
bool buildDaisySupportedNoData(uint16_t command,std::vector<uint8_t>& out,std::string& error){if(command!=105&&command!=128&&command!=130&&command!=153&&command!=166){error="DAISY_NO_DATA_COMMAND";return false;}out.clear();return true;}
bool buildDaisyCurrentDay(bool all,std::vector<uint8_t>& out){out.clear();if(all)out.push_back('A');return true;}
bool buildDaisyOperatorInfo(uint16_t operatorNumber,std::vector<uint8_t>& out,std::string& error){if(operatorNumber<1||operatorNumber>999){error="DAISY_OPERATOR_NUMBER";return false;}out.clear();append(out,std::to_string(operatorNumber));return true;}
bool buildDaisyFmInformationNumber(uint16_t first,uint8_t option,uint16_t last,std::vector<uint8_t>& out,std::string& error){const bool range=option>=4&&option<=6;if(first<1||first>9999||option>6||(range?(last<first||last>9999):last!=0)){error="DAISY_FM_INFO_NUMBER";return false;}out.clear();append(out,std::to_string(first));out.push_back(',');out.push_back(static_cast<uint8_t>('0'+option));if(range){out.push_back(',');append(out,std::to_string(last));}return true;}
bool buildDaisyQrDocument(uint32_t documentNumber,std::vector<uint8_t>& out,std::string& error){if(documentNumber>9999999){error="DAISY_QR_DOCUMENT";return false;}out.clear();if(documentNumber){const uint32_t selector=documentNumber==1?1:documentNumber-1;append(out,std::to_string(selector));}return true;}
bool buildDaisyIssuedDocument(uint32_t documentNumber,bool sha1,std::vector<uint8_t>& out,std::string& error){if(documentNumber>9999999){error="DAISY_ISSUED_DOCUMENT";return false;}out.clear();if(documentNumber)append(out,std::to_string(documentNumber));if(sha1){if(documentNumber)out.push_back(',');append(out,"S");}return true;}
bool buildDaisyFmInformationDate(const std::string& first,uint8_t option,const std::string& last,std::vector<uint8_t>& out,std::string& error){const bool range=option>=4&&option<=6;if(!daisyDate(first)||option>6||(range?(!daisyDate(last)||first.substr(4,2)+first.substr(2,2)+first.substr(0,2)>last.substr(4,2)+last.substr(2,2)+last.substr(0,2)):!last.empty())){error="DAISY_FM_INFO_DATE";return false;}out.clear();append(out,first);out.push_back(',');out.push_back(static_cast<uint8_t>('0'+option));if(range){out.push_back(',');append(out,last);}return true;}
bool buildDaisyDepartmentSale(const DaisyDepartmentSalePayload& in,std::vector<uint8_t>& out,std::string& error){if(in.department<1||in.department>99||!decimal(in.price,10,2,true)||!decimal(in.quantity,10,3,true)||in.discountType>4||(in.correction&&(in.discountType||!in.discountValue.empty()))||(!in.correction&&in.discountType==0&&!in.discountValue.empty())||(!in.correction&&in.discountType>0&&!decimal(in.discountValue,10,2,false))){error="DAISY_DEPARTMENT_SALE";return false;}out.clear();if(in.correction)out.push_back('-');append(out,std::to_string(in.department));out.push_back('@');append(out,in.price);if(in.quantity!="1.000"){out.push_back('*');append(out,in.quantity);}if(!in.correction&&in.discountType){if(in.discountType<=2)out.push_back(',');else out.push_back('$');if(in.discountType==2||in.discountType==4)out.push_back('-');append(out,in.discountValue);}return true;}
bool buildDaisyOptionalNoData(uint16_t command,std::vector<uint8_t>& out,std::string& error){if(command!=33&&command!=63&&command!=71&&command!=176){error="DAISY_OPTIONAL_NO_DATA";return false;}out.clear();return true;}
bool buildDaisyDisplayText(uint16_t command,const std::string& text,std::vector<uint8_t>& out,std::string& error){if((command!=35&&command!=47)||!safeText(text,160)){error="DAISY_DISPLAY_TEXT";return false;}out.assign(text.begin(),text.end());return true;}
bool buildDaisyPaperFeed(uint16_t lines,std::vector<uint8_t>& out,std::string& error){if(lines>999){error="DAISY_PAPER_FEED";return false;}out.clear();if(lines)append(out,std::to_string(lines));return true;}
bool buildDaisyPaperCut(uint8_t mode,std::vector<uint8_t>& out,std::string& error){if(mode>2){error="DAISY_PAPER_CUT";return false;}out.clear();if(mode)out.push_back(static_cast<uint8_t>('0'+mode));return true;}
bool buildDaisyDisplayLine(uint16_t line,const std::string& text,std::vector<uint8_t>& out,std::string& error){if(line<1||line>999||!safeText(text,160)){error="DAISY_DISPLAY_LINE";return false;}out.clear();append(out,std::to_string(line));out.push_back(',');append(out,text);return true;}
bool buildDaisyInvoiceCustomer(const DaisyInvoiceCustomerPayload& in,std::vector<uint8_t>& out,std::string& error){if(!safeText(in.identificationNumber,32)||!optionalSafeText(in.vatNumber,32)||!optionalSafeText(in.seller,64)||!optionalSafeText(in.receiver,64)||!optionalSafeText(in.customer,64)||in.addressLines.size()>4||std::any_of(in.addressLines.begin(),in.addressLines.end(),[](const std::string& v){return !safeText(v,64);})){error="DAISY_INVOICE_CUSTOMER";return false;}std::vector<std::string> fields={in.identificationNumber,in.vatNumber,in.seller,in.receiver,in.customer};fields.insert(fields.end(),in.addressLines.begin(),in.addressLines.end());while(fields.size()>1&&fields.back().empty())fields.pop_back();out.clear();for(size_t i=0;i<fields.size();i++){if(i)tab(out);append(out,fields[i]);}if(out.size()>220){error="DAISY_INVOICE_CUSTOMER";out.clear();return false;}return true;}
bool buildDaisyBarcode(const DaisyBarcodePayload& in,std::vector<uint8_t>& out,std::string& error){const bool numeric=digits(in.data,1,220);bool valid=false;switch(in.type){case 1:valid=digits(in.data,7,7);break;case 2:valid=digits(in.data,12,12);break;case 3:valid=printableAscii(in.data,numeric?18:80);break;case 4:valid=digits(in.data,8,8)&&in.data[0]=='0';break;case 5:valid=digits(in.data,11,11);break;case 6:valid=digits(in.data,1,9);break;case 7:case 8:valid=digits(in.data,1,18);break;case 9:valid=printableAscii(in.data,9);break;case 10:valid=printableAscii(in.data,8);break;case 11:valid=!in.data.empty()&&in.data.size()<=11&&std::all_of(in.data.begin(),in.data.end(),[](unsigned char c){return std::isdigit(c)||(c>='A'&&c<='Z');});break;case 12:valid=!in.data.empty()&&in.data.size()<=14&&std::all_of(in.data.begin(),in.data.end(),[](unsigned char c){return std::isdigit(c)||(c>='A'&&c<='D');});break;case 13:valid=digits(in.data,1,13);break;}if(!valid||(in.position!='C'&&in.position!='R'&&in.position!='L')||in.scale>999||in.heightMm>999){error="DAISY_BARCODE";return false;}out.clear();append(out,std::to_string(in.type));out.push_back(',');append(out,in.data);if(in.optionsSpecified){tab(out);out.push_back(static_cast<uint8_t>(in.position));out.push_back(',');append(out,std::to_string(in.scale));out.push_back(',');append(out,std::to_string(in.heightMm));out.push_back(',');out.push_back(static_cast<uint8_t>(in.printText?'1':'0'));}return true;}
bool buildDaisyCustomerQr(char operation,const std::vector<std::string>& fields,std::vector<uint8_t>& out,std::string& error){if(operation!='Q'&&operation!='P'&&operation!='R'){error="DAISY_CUSTOMER_QR";return false;}if((operation=='Q'&&(fields.size()!=1||!safeText(fields[0],180)))||(operation=='P'&&(fields.empty()||std::any_of(fields.begin(),fields.end(),[](const std::string& v){return !qrTemplateId(v);})))||(operation=='R'&&!fields.empty())){error="DAISY_CUSTOMER_QR";return false;}out.clear();out.push_back(static_cast<uint8_t>(operation));for(const auto& field:fields){out.push_back(',');append(out,field);}return true;}
bool buildDaisyDrawer(uint16_t milliseconds,std::vector<uint8_t>& out,std::string& error){if(milliseconds&&milliseconds<50){error="DAISY_DRAWER";return false;}out.clear();if(milliseconds)append(out,std::to_string(milliseconds));return true;}
bool buildDaisyDisplayConfiguration(char type,const std::string& data,std::vector<uint8_t>& out,std::string& error){bool valid=false;if(type=='R'||type=='C'||type=='S')valid=digits(data,1,6);else if(type>='0'&&type<='9'){if(data=="D")valid=true;else if(!data.empty()&&std::string("IBNEO").find(data[0])!=std::string::npos){const auto comma=data.find(',');const std::string body=data.substr(1,comma==std::string::npos?std::string::npos:comma-1);valid=upperHex(body,20);if(valid&&comma!=std::string::npos)valid=digits(data.substr(comma+1),1,6);}}if(!valid){error="DAISY_DISPLAY_CONFIGURATION";return false;}out.clear();out.push_back(static_cast<uint8_t>(type));out.push_back(',');append(out,data);return true;}
bool buildDaisyCustomerProgram(const DaisyCustomerRecord& in,std::vector<uint8_t>& out,std::string& error){const std::string fields[]={in.eik,in.vatNumber,in.receiver,in.buyer,in.address1,in.address2};if(!safeText(in.eik,32)||std::any_of(std::begin(fields)+1,std::end(fields),[](const std::string& v){return !optionalSafeText(v,64);})){error="DAISY_CUSTOMER_PROGRAM";return false;}out={'P'};for(const auto& field:fields){if(&field!=&fields[0])tab(out);append(out,field);}while(out.size()>1&&out.back()=='\t')out.pop_back();if(out.size()>220){error="DAISY_CUSTOMER_PROGRAM";out.clear();return false;}return true;}
bool buildDaisyCustomerDelete(const std::string& eik,bool all,std::vector<uint8_t>& out,std::string& error){if((all&&!eik.empty())||(!all&&!safeText(eik,32))){error="DAISY_CUSTOMER_DELETE";return false;}out={'D'};append(out,all?"A":eik);return true;}
bool buildDaisyCustomerRead(const std::string& eik,std::vector<uint8_t>& out,std::string& error){if(!safeText(eik,32)){error="DAISY_CUSTOMER_READ";return false;}out={'R'};append(out,eik);return true;}
bool buildDaisyCustomerIteration(char operation,std::vector<uint8_t>& out,std::string& error){if(operation!='F'&&operation!='N'){error="DAISY_CUSTOMER_ITERATION";return false;}out={static_cast<uint8_t>(operation)};return true;}
bool buildDaisyBattery(std::vector<uint8_t>& out){out={'1','5'};return true;}
bool buildDatecsSubtotal(const SubtotalPayload& in,std::vector<uint8_t>& out,std::string& error){
  if(in.discountType>4||(in.discountType!=0&&!decimal(in.discountValue,7,2,true))||(in.discountType==0&&!in.discountValue.empty())){error="DATECS_SUBTOTAL_FIELDS";return false;}out.clear();out.push_back(in.print?'1':'0');tab(out);out.push_back(in.display?'1':'0');tab(out);if(in.discountType)out.push_back(static_cast<uint8_t>('0'+in.discountType));tab(out);if(in.discountType)append(out,in.discountValue);tab(out);return true;
}
bool buildDatecsLastFiscalEntry(uint8_t type,std::vector<uint8_t>& out,std::string& error){if(type>3){error="DATECS_LAST_ENTRY_TYPE";return false;}out.clear();out.push_back(static_cast<uint8_t>('0'+type));tab(out);return true;}
bool buildDatecsErrorLookup(int code,std::vector<uint8_t>& out,std::string& error){if(code>=0||code < -999999){error="DATECS_ERROR_LOOKUP_CODE";return false;}out.clear();append(out,std::to_string(code));tab(out);return true;}
bool buildDatecsDeviceIdentity(std::vector<uint8_t>& out){out.clear();out.push_back('1');tab(out);return true;}
bool buildDatecsDailyTaxation(uint8_t type,std::vector<uint8_t>& out,std::string& error){if(type>3){error="DATECS_DAILY_TAXATION_TYPE";return false;}out.clear();out.push_back(static_cast<uint8_t>('0'+type));tab(out);return true;}
bool buildDatecsDiagnosticInfo(bool withChecksum,std::vector<uint8_t>& out){out.clear();if(withChecksum){out.push_back('1');tab(out);}return true;}
bool buildDatecsItemGroupInfo(uint8_t group,std::vector<uint8_t>& out,std::string& error){if(group>99){error="DATECS_ITEM_GROUP";return false;}out.clear();if(group){append(out,std::to_string(group));tab(out);}return true;}
bool buildDatecsDepartmentInfo(uint8_t department,std::vector<uint8_t>& out,std::string& error){if(department>99){error="DATECS_DEPARTMENT";return false;}out.clear();if(department){append(out,std::to_string(department));tab(out);}return true;}
bool buildDatecsFiscalMemoryTest(bool write,std::vector<uint8_t>& out){out.clear();out.push_back(write?'1':'0');tab(out);return true;}
bool buildDatecsAdditionalDailyInfo(uint8_t type,uint8_t operatorNumber,std::vector<uint8_t>& out,std::string& error){if(type>5||operatorNumber>30){error="DATECS_ADDITIONAL_DAILY_INFO";return false;}out.clear();out.push_back(static_cast<uint8_t>('0'+type));tab(out);if(operatorNumber){append(out,std::to_string(operatorNumber));tab(out);}return true;}
bool buildDatecsOperatorInfo(uint8_t operatorNumber,std::vector<uint8_t>& out,std::string& error){if(operatorNumber<1||operatorNumber>30){error="DATECS_OPERATOR_INFO";return false;}out.clear();append(out,std::to_string(operatorNumber));tab(out);return true;}
bool buildDatecsCurrencyConversion(const CurrencyConversionPayload& in,std::vector<uint8_t>& out,std::string& error){if(in.direction>1||!decimal(in.amount,9,2,true)){error="DATECS_CURRENCY_CONVERSION";return false;}out.clear();out.push_back(static_cast<uint8_t>('0'+in.direction));tab(out);append(out,in.amount);tab(out);return true;}
bool buildDatecsFiscalMemoryRead(const FiscalMemoryReadPayload& in,std::vector<uint8_t>& out,std::string& error){if(!hexAddress(in.address)||in.byteCount<1||in.byteCount>104){error="DATECS_FISCAL_MEMORY_READ";return false;}out.clear();out.push_back('0');tab(out);append(out,in.address);tab(out);append(out,std::to_string(in.byteCount));tab(out);return true;}
bool buildDatecsDeviceInfo(uint8_t option,std::vector<uint8_t>& out,std::string& error){if(option<1||option>5){error="DATECS_DEVICE_INFO_OPTION";return false;}out.clear();out.push_back(static_cast<uint8_t>('0'+option));tab(out);return true;}
bool buildDatecsReceiptPeriodSearch(const ReceiptPeriodSearchPayload& in,std::vector<uint8_t>& out,std::string& error){if((!in.startDateTime.empty()&&(!datePrefix(in.startDateTime,true)||!safeText(in.startDateTime,24)))||(!in.endDateTime.empty()&&(!datePrefix(in.endDateTime,true)||!safeText(in.endDateTime,24)))||in.documentType>10){error="DATECS_RECEIPT_PERIOD_SEARCH";return false;}out.clear();append(out,in.startDateTime);tab(out);append(out,in.endDateTime);tab(out);append(out,std::to_string(in.documentType));tab(out);return true;}
bool buildDatecsEjDocumentSelector(const EjDocumentSelector& in,std::vector<uint8_t>& out,std::string& error){if(in.option>3||in.recordType>10||(in.documentNumber==0&&in.recordType!=0)||in.documentNumber>documentLimit(in.recordType)){error="DATECS_EJ_DOCUMENT_SELECTOR";return false;}out.clear();append(out,std::to_string(in.option));tab(out);if(in.documentNumber){append(out,std::to_string(in.documentNumber));tab(out);append(out,std::to_string(in.recordType));tab(out);}return true;}
bool buildDatecsEjCsvRange(const EjCsvRange& in,std::vector<uint8_t>& out,std::string& error){if(in.firstDocument<1||in.lastDocument<in.firstDocument||in.lastDocument>99999999){error="DATECS_EJ_CSV_RANGE";return false;}out.clear();append(out,"9");tab(out);append(out,std::to_string(in.firstDocument));tab(out);append(out,std::to_string(in.lastDocument));tab(out);return true;}
bool buildDatecsEjCsvRead(std::vector<uint8_t>& out){out.clear();append(out,"8");tab(out);return true;}
bool buildDatecsFiscalMemoryStructured(uint8_t type,uint16_t record,std::vector<uint8_t>& out,std::string& error){if(type>9||record>9999){error="DATECS_FM_STRUCTURED";return false;}out.clear();append(out,std::to_string(type));tab(out);if(record)append(out,std::to_string(record));tab(out);return true;}
bool buildDatecsModemInfo(char option,std::vector<uint8_t>& out,std::string& error){if(option!='s'&&option!='i'&&option!='M'){error="DATECS_MODEM_OPTION";return false;}out.clear();out.push_back(static_cast<uint8_t>(option));tab(out);return true;}
bool buildDatecsOpenReversal(const ReversalOpenPayload& in,std::vector<uint8_t>& out,std::string& error){if(in.operatorNumber<1||in.operatorNumber>30||!digits(in.password,8,8)||in.tillNumber<1||in.tillNumber>99999||in.reason>2||in.originalDocument<1||in.originalDocument>9999999||!documentedDateTime(in.originalDateTime)||!digits(in.fiscalMemoryNumber,1,8)||(!in.unp.empty()&&!validUNP(in.unp))||(in.invoice&&(!digits(in.originalInvoiceNumber,1,10)||!safeText(in.invoiceReason,64)))||(!in.invoice&&(!in.originalInvoiceNumber.empty()||!in.invoiceReason.empty()))){error="DATECS_REVERSAL_FIELDS";return false;}out.clear();append(out,std::to_string(in.operatorNumber));tab(out);append(out,in.password);tab(out);append(out,std::to_string(in.tillNumber));tab(out);append(out,std::to_string(in.reason));tab(out);append(out,std::to_string(in.originalDocument));tab(out);append(out,in.originalDateTime);tab(out);append(out,in.fiscalMemoryNumber);tab(out);if(in.invoice)out.push_back('I');tab(out);append(out,in.originalInvoiceNumber);tab(out);append(out,in.invoiceReason);tab(out);append(out,in.unp);tab(out);return true;}
bool buildDatecsPcConnectionMode(int printing,std::vector<uint8_t>& out,std::string& error){if(printing < -1||printing>1){error="DATECS_PC_MODE";return false;}out.clear();if(printing>=0){out.push_back(static_cast<uint8_t>('0'+printing));tab(out);}return true;}
bool buildDatecsProgrammedItem(const ProgrammedItemPayload& in,std::vector<uint8_t>& out,std::string& error){if(in.pluCode<1||in.pluCode>100000||(!in.quantity.empty()&&!decimal(in.quantity,6,3,true))||(!in.price.empty()&&!decimal(in.price,7,2,false))||in.discountType>4||(in.discountType==0&&!in.discountValue.empty())||(in.discountType!=0&&!decimal(in.discountValue,7,2,true))){error="DATECS_PROGRAMMED_ITEM";return false;}out.clear();append(out,std::to_string(in.pluCode));tab(out);append(out,in.quantity);tab(out);append(out,in.price);tab(out);if(in.discountType)append(out,std::to_string(in.discountType));tab(out);append(out,in.discountValue);tab(out);return true;}
bool buildDatecsGeneralInfo(uint8_t type,std::vector<uint8_t>& out,std::string& error){const uint8_t allowed[]={0,1,2,3,4,6,9,10,11};if(std::find(std::begin(allowed),std::end(allowed),type)==std::end(allowed)){error="DATECS_GENERAL_INFO_TYPE";return false;}out.clear();append(out,std::to_string(type));tab(out);return true;}
bool buildDatecsFiscalMemoryDateReport(const FiscalMemoryDateReportPayload& in,std::vector<uint8_t>& out,std::string& error){const auto valid=[](const std::string& v){return v.empty()||(v.size()==8&&datePrefix(v,false));};if(in.type>1||!valid(in.startDate)||!valid(in.endDate)||(!in.startDate.empty()&&!in.endDate.empty()&&(in.startDate.substr(6,2)+in.startDate.substr(3,2)+in.startDate.substr(0,2)>in.endDate.substr(6,2)+in.endDate.substr(3,2)+in.endDate.substr(0,2)))){error="DATECS_FM_DATE_REPORT";return false;}out.clear();append(out,std::to_string(in.type));tab(out);append(out,in.startDate);tab(out);append(out,in.endDate);tab(out);return true;}
bool buildDatecsFiscalMemoryNumberReport(const FiscalMemoryNumberReportPayload& in,std::vector<uint8_t>& out,std::string& error){if(in.type>1||in.firstZReport>3650||in.lastZReport>3650||(in.firstZReport&&in.lastZReport&&in.lastZReport<in.firstZReport)){error="DATECS_FM_NUMBER_REPORT";return false;}out.clear();append(out,std::to_string(in.type));tab(out);if(in.firstZReport)append(out,std::to_string(in.firstZReport));tab(out);if(in.lastZReport)append(out,std::to_string(in.lastZReport));tab(out);return true;}
bool buildDatecsOperatorReport(const OperatorReportPayload& in,std::vector<uint8_t>& out,std::string& error){if(in.firstOperator>30||in.lastOperator>30||(in.firstOperator&&in.lastOperator&&in.lastOperator<in.firstOperator)){error="DATECS_OPERATOR_REPORT";return false;}out.clear();if(in.firstOperator)append(out,std::to_string(in.firstOperator));tab(out);if(in.lastOperator)append(out,std::to_string(in.lastOperator));tab(out);out.push_back(in.clear?'1':'0');tab(out);return true;}
bool buildDatecsPluReport(const PluReportPayload& in,std::vector<uint8_t>& out,std::string& error){if(in.type>3||in.firstPlu>100000||in.lastPlu>100000||(in.firstPlu&&in.lastPlu&&in.lastPlu<in.firstPlu)){error="DATECS_PLU_REPORT";return false;}out.clear();append(out,std::to_string(in.type));tab(out);if(in.firstPlu)append(out,std::to_string(in.firstPlu));tab(out);if(in.lastPlu)append(out,std::to_string(in.lastPlu));tab(out);return true;}
bool buildDatecsOptionalNoParameters(uint16_t command,std::vector<uint8_t>& out,std::string& error){if(command!=33&&command!=46&&command!=63){error="DATECS_OPTIONAL_EMPTY_COMMAND";return false;}out.clear();return true;}
bool buildDatecsDisplayText(uint16_t command,const std::string& text,std::vector<uint8_t>& out,std::string& error){if((command!=35&&command!=47)||!safeText(text,20)){error="DATECS_DISPLAY_TEXT";return false;}out.clear();append(out,text);tab(out);return true;}
bool buildDatecsPaperFeed(uint8_t lines,std::vector<uint8_t>& out,std::string& error){if(lines>99){error="DATECS_PAPER_FEED";return false;}out.clear();if(lines){append(out,std::to_string(lines));tab(out);}return true;}
bool buildDatecsSound(const SoundPayload& in,std::vector<uint8_t>& out){out.clear();append(out,std::to_string(in.frequencyHz));tab(out);append(out,std::to_string(in.durationMs));tab(out);return true;}
bool buildDatecsBarcode(const BarcodePayload& in,std::vector<uint8_t>& out,std::string& error){const auto ascii=[](const std::string& value,size_t min,size_t max){return value.size()>=min&&value.size()<=max&&std::all_of(value.begin(),value.end(),[](unsigned char c){return c>=32&&c<=127;});};bool valid=false;switch(in.type){case 1:valid=digits(in.data,8,8);break;case 2:valid=digits(in.data,13,13);break;case 3:valid=ascii(in.data,3,31);break;case 4:valid=ascii(in.data,3,279);break;case 5:valid=digits(in.data,3,22);break;case 6:case 7:valid=ascii(in.data,3,400);break;default:break;}if(!valid||(in.moduleSize&&(in.moduleSize<3||in.moduleSize>10||(in.type!=4&&in.type!=6&&in.type!=7)))){error="DATECS_BARCODE";return false;}out.clear();append(out,std::to_string(in.type));tab(out);append(out,in.data);tab(out);if(in.moduleSize)append(out,std::to_string(in.moduleSize));tab(out);return true;}
bool buildDatecsSeparator(uint8_t type,std::vector<uint8_t>& out,std::string& error){if(type<1||type>4){error="DATECS_SEPARATOR";return false;}out.clear();append(out,std::to_string(type));tab(out);return true;}
bool buildDatecsDrawer(uint16_t durationMs,std::vector<uint8_t>& out){out.clear();append(out,std::to_string(durationMs));tab(out);return true;}
bool buildDatecsInvoiceData(const InvoiceDataPayload& in,std::vector<uint8_t>& out,std::string& error){
  if(!optionalSafeText(in.seller,36)||!optionalSafeText(in.receiver,36)||!optionalSafeText(in.buyer,36)||!optionalSafeText(in.address1,36)||!optionalSafeText(in.address2,36)||in.taxNumberType>3||!digits(in.taxNumber,8,13)||!safeText(in.vatNumber,14)||in.vatNumber.size()<10){error="DATECS_INVOICE_DATA";return false;}
  out.clear();append(out,in.seller);tab(out);append(out,in.receiver);tab(out);append(out,in.buyer);tab(out);append(out,in.address1);tab(out);append(out,in.address2);tab(out);append(out,std::to_string(in.taxNumberType));tab(out);append(out,in.taxNumber);tab(out);append(out,in.vatNumber);tab(out);return true;
}
bool buildDatecsClientInfo(std::vector<uint8_t>& out){out.clear();out.push_back('I');tab(out);return true;}
bool buildDatecsClientProgram(const ClientRecordPayload& in,std::vector<uint8_t>& out,std::string& error){
  if(in.index<1||in.index>1000||!safeText(in.name,36)||in.taxNumberType>3||!digits(in.taxNumber,9,13)||!optionalSafeText(in.receiverName,36)||!optionalSafeText(in.vatNumber,14)||!optionalSafeText(in.address1,36)||!optionalSafeText(in.address2,36)){error="DATECS_CLIENT_PROGRAM";return false;}
  out.clear();out.push_back('P');tab(out);append(out,std::to_string(in.index));tab(out);append(out,in.name);tab(out);append(out,std::to_string(in.taxNumberType));tab(out);append(out,in.taxNumber);tab(out);append(out,in.receiverName);tab(out);append(out,in.vatNumber);tab(out);append(out,in.address1);tab(out);append(out,in.address2);tab(out);return true;
}
bool buildDatecsClientDelete(uint16_t first,uint16_t last,bool all,std::vector<uint8_t>& out,std::string& error){
  if((all&&(first!=0||last!=0))||(!all&&(first<1||first>1000||last>1000||(last&&last<first)))){error="DATECS_CLIENT_DELETE";return false;}
  out.clear();out.push_back('D');tab(out);if(all)out.push_back('A');else append(out,std::to_string(first));tab(out);if(!all&&last)append(out,std::to_string(last));tab(out);return true;
}
bool buildDatecsClientRead(uint16_t index,std::vector<uint8_t>& out,std::string& error){if(index<1||index>1000){error="DATECS_CLIENT_READ";return false;}out.clear();out.push_back('R');tab(out);append(out,std::to_string(index));tab(out);return true;}
bool buildDatecsClientSeek(char direction,uint16_t from,std::vector<uint8_t>& out,std::string& error){if((direction!='F'&&direction!='L')||from>1000){error="DATECS_CLIENT_SEEK";return false;}out.clear();out.push_back(static_cast<uint8_t>(direction));tab(out);if(from)append(out,std::to_string(from));tab(out);return true;}
bool buildDatecsClientNext(std::vector<uint8_t>& out){out.clear();out.push_back('N');tab(out);return true;}
bool buildDatecsClientFindByTaxNumber(const std::string& taxNumber,std::vector<uint8_t>& out,std::string& error){if(!digits(taxNumber,9,13)){error="DATECS_CLIENT_TAX_NUMBER";return false;}out.clear();out.push_back('T');tab(out);append(out,taxNumber);tab(out);return true;}
bool buildDatecsClientFindUnprogrammed(bool last,uint16_t from,std::vector<uint8_t>& out,std::string& error){if(from>1000){error="DATECS_CLIENT_UNPROGRAMMED";return false;}out.clear();out.push_back(last?'x':'X');tab(out);if(from)append(out,std::to_string(from));tab(out);return true;}
bool parseDatecsResult(const std::vector<uint8_t>& raw,DatecsResult& out,std::string& error){
  const auto fields=split(raw,'\t');if(fields.empty()){error="DATECS_EMPTY_RESULT";return false;}char* end=nullptr;long code=std::strtol(fields[0].c_str(),&end,10);if(!end||*end!='\0'||code<INT_MIN||code>0){error="DATECS_ERROR_CODE";return false;}out.errorCode=static_cast<int>(code);out.fields.assign(fields.begin()+1,fields.end());return true;
}
bool parseDatecsTaxRates(const std::vector<uint8_t>& raw,TaxRatesResult& out,std::string& error){DatecsResult r;if(!parseDatecsResult(raw,r,error)||r.fields.size()!=10||!uint32Value(r.fields[0],out.firstZReport)||!datePrefix(r.fields[9],false)){error="DATECS_TAX_RATES";return false;}for(size_t i=0;i<8;i++){if(!decimal(r.fields[i+1],3,2,false)){error="DATECS_TAX_RATES";return false;}out.rates[i]=r.fields[i+1];}out.effectiveDate=r.fields[9];return true;}
bool parseDatecsSubtotal(const std::vector<uint8_t>& raw,SubtotalResult& out,std::string& error){DatecsResult r;if(!parseDatecsResult(raw,r,error)||r.fields.size()!=10||!uint32Value(r.fields[0],out.slipNumber)||!decimal(r.fields[1],7,2,false)){error="DATECS_SUBTOTAL_RESULT";return false;}out.subtotal=r.fields[1];for(size_t i=0;i<8;i++){if(!decimal(r.fields[i+2],7,2,false)){error="DATECS_SUBTOTAL_RESULT";return false;}out.taxTotals[i]=r.fields[i+2];}return true;}
bool parseDatecsDateTime(const std::vector<uint8_t>& raw,std::string& out,std::string& error){DatecsResult r;if(!parseDatecsResult(raw,r,error)||r.fields.size()!=1||!datePrefix(r.fields[0],true)||!safeText(r.fields[0],24)){error="DATECS_DATE_TIME";return false;}out=r.fields[0];return true;}
bool parseDatecsLastFiscalEntry(const std::vector<uint8_t>& raw,LastFiscalEntryResult& out,std::string& error){DatecsResult r;if(!parseDatecsResult(raw,r,error)||r.fields.size()!=10||!uint32Value(r.fields[0],out.reportNumber)||!datePrefix(r.fields[9],false)){error="DATECS_LAST_ENTRY";return false;}for(size_t i=0;i<8;i++){if(!decimal(r.fields[i+1],9,2,false)){error="DATECS_LAST_ENTRY";return false;}out.taxValues[i]=r.fields[i+1];}out.date=r.fields[9];return true;}
bool parseDatecsTaxNumber(const std::vector<uint8_t>& raw,std::string& out,std::string& error){DatecsResult r;if(!parseDatecsResult(raw,r,error)||r.fields.size()!=1||!safeText(r.fields[0],13)){error="DATECS_TAX_NUMBER";return false;}out=r.fields[0];return true;}
bool parseDatecsErrorDescription(const std::vector<uint8_t>& raw,ErrorDescriptionResult& out,std::string& error){DatecsResult r;if(!parseDatecsResult(raw,r,error)||r.fields.size()!=2||!negativeInt(r.fields[0],out.code)||!safeText(r.fields[1],160)){error="DATECS_ERROR_DESCRIPTION";return false;}out.message=r.fields[1];return true;}
bool parseDatecsCurrentReceipt(const std::vector<uint8_t>& raw,CurrentReceiptResult& out,std::string& error){DatecsResult r;if(!parseDatecsResult(raw,r,error)||r.fields.size()!=11){error="DATECS_CURRENT_RECEIPT";return false;}for(size_t i=0;i<8;i++){if(!decimal(r.fields[i],9,2,false)){error="DATECS_CURRENT_RECEIPT";return false;}out.taxTotals[i]=r.fields[i];}if((r.fields[8]!="0"&&r.fields[8]!="1")||!digits(r.fields[9],1,10)||(r.fields[10]!="0"&&r.fields[10]!="1")){error="DATECS_CURRENT_RECEIPT";return false;}out.invoice=r.fields[8]=="1";out.nextInvoiceNumber=r.fields[9];out.reversal=r.fields[10]=="1";return true;}
bool parseDatecsDeviceIdentity(const std::vector<uint8_t>& raw,DeviceIdentityResult& out,std::string& error){DatecsResult r;if(!parseDatecsResult(raw,r,error)||r.fields.size()!=7||!safeText(r.fields[0],8)||!digits(r.fields[1],8,8)||!safeText(r.fields[2],64)||!safeText(r.fields[3],64)||!safeText(r.fields[4],13)||!safeText(r.fields[5],64)||!safeText(r.fields[6],64)){error="DATECS_DEVICE_IDENTITY";return false;}out={r.fields[0],r.fields[1],r.fields[2],r.fields[3],r.fields[4],r.fields[5],r.fields[6]};return true;}
bool parseDatecsDailyTaxation(const std::vector<uint8_t>& raw,DailyTaxationResult& out,std::string& error){DatecsResult r;if(!parseDatecsResult(raw,r,error)||r.fields.size()!=9||!uint32Value(r.fields[0],out.reportNumber)||out.reportNumber<1||out.reportNumber>3650){error="DATECS_DAILY_TAXATION";return false;}for(size_t i=0;i<8;i++){if(!decimal(r.fields[i+1],9,2,false)){error="DATECS_DAILY_TAXATION";return false;}out.taxValues[i]=r.fields[i+1];}return true;}
bool parseDatecsReportsLeft(const std::vector<uint8_t>& raw,uint32_t& out,std::string& error){DatecsResult r;if(!parseDatecsResult(raw,r,error)||r.fields.size()!=1||!uint32Value(r.fields[0],out)||out<1||out>3650){error="DATECS_REPORTS_LEFT";return false;}return true;}
bool parseDatecsLastFiscalRecordDateTime(const std::vector<uint8_t>& raw,std::string& out,std::string& error){DatecsResult r;if(!parseDatecsResult(raw,r,error)||r.fields.size()!=1||!fullDateTime(r.fields[0])){error="DATECS_LAST_FISCAL_DATETIME";return false;}out=r.fields[0];return true;}
bool parseDatecsDiagnosticInfo(const std::vector<uint8_t>& raw,DiagnosticInfoResult& out,std::string& error){DatecsResult r;if(!parseDatecsResult(raw,r,error)||r.fields.size()!=8||!safeText(r.fields[0],32)||!safeText(r.fields[1],6)||!safeText(r.fields[2],16)||!safeText(r.fields[3],16)||(r.fields[4].size()!=4&&!r.fields[4].empty())||(!r.fields[4].empty()&&!safeText(r.fields[4],4))||!safeText(r.fields[5],8)||!safeText(r.fields[6],8)||!digits(r.fields[7],8,8)){error="DATECS_DIAGNOSTIC_INFO";return false;}out={r.fields[0],r.fields[1],r.fields[2],r.fields[3],r.fields[4],r.fields[5],r.fields[6],r.fields[7]};return true;}
bool parseDatecsItemGroupInfo(const std::vector<uint8_t>& raw,ItemGroupInfoResult& out,std::string& error){DatecsResult r;if(!parseDatecsResult(raw,r,error)||r.fields.size()!=3||!decimal(r.fields[0],8,3,false)||!decimal(r.fields[1],9,2,false)||!safeText(r.fields[2],32)){error="DATECS_ITEM_GROUP_INFO";return false;}out={r.fields[0],r.fields[1],r.fields[2]};return true;}
bool parseDatecsDepartmentInfo(const std::vector<uint8_t>& raw,DepartmentInfoResult& out,std::string& error){DatecsResult r;if(!parseDatecsResult(raw,r,error)||r.fields.size()!=7||!uint32Value(r.fields[0],out.taxGroup)||!decimal(r.fields[1],9,2,false)||!decimal(r.fields[2],8,3,false)||!decimal(r.fields[3],9,2,false)||!decimal(r.fields[4],8,3,false)||!decimal(r.fields[5],9,2,false)||!safeText(r.fields[6],72)){error="DATECS_DEPARTMENT_INFO";return false;}out.price=r.fields[1];out.totalSales=r.fields[2];out.totalSum=r.fields[3];out.reversalSales=r.fields[4];out.reversalSum=r.fields[5];out.name=r.fields[6];return true;}
bool parseDatecsFiscalMemoryTest(const std::vector<uint8_t>& raw,uint32_t& out,std::string& error){DatecsResult r;if(!parseDatecsResult(raw,r,error)||r.fields.size()!=1||!uint32Value(r.fields[0],out)||out>16){error="DATECS_FISCAL_MEMORY_TEST";return false;}return true;}
bool parseDatecsDailyPayments(const std::vector<uint8_t>& raw,DailyPaymentsResult& out,std::string& error){DatecsResult r;if(!parseDatecsResult(raw,r,error)||r.fields.size()!=7){error="DATECS_DAILY_PAYMENTS";return false;}for(size_t i=0;i<7;i++){if(!decimal(r.fields[i],9,2,false)){error="DATECS_DAILY_PAYMENTS";return false;}out.amounts[i]=r.fields[i];}return true;}
bool parseDatecsDailySales(const std::vector<uint8_t>& raw,DailyCountSumResult& out,std::string& error){DatecsResult r;if(!parseDatecsResult(raw,r,error)||r.fields.size()!=2||!uint32Value(r.fields[0],out.count)||out.count>65535||!decimal(r.fields[1],9,2,false)){error="DATECS_DAILY_SALES";return false;}out.sum=r.fields[1];return true;}
bool parseDatecsDailyDualCountSum(const std::vector<uint8_t>& raw,DailyDualCountSumResult& out,std::string& error){DatecsResult r;if(!parseDatecsResult(raw,r,error)||r.fields.size()!=4){error="DATECS_DAILY_DUAL_TOTALS";return false;}for(size_t i=0;i<2;i++){if(!uint32Value(r.fields[i*2],out.counts[i])||out.counts[i]>999999||!signedDecimal(r.fields[i*2+1],9,2)){error="DATECS_DAILY_DUAL_TOTALS";return false;}out.sums[i]=r.fields[i*2+1];}return true;}
bool parseDatecsDailyCashMovements(const std::vector<uint8_t>& raw,DailyCashMovementResult& out,std::string& error){DatecsResult r;if(!parseDatecsResult(raw,r,error)||r.fields.size()!=8){error="DATECS_DAILY_CASH_MOVEMENTS";return false;}for(size_t i=0;i<4;i++){if(!uint32Value(r.fields[i*2],out.counts[i])||out.counts[i]>999999||!signedDecimal(r.fields[i*2+1],9,2)){error="DATECS_DAILY_CASH_MOVEMENTS";return false;}out.sums[i]=r.fields[i*2+1];}return true;}
bool parseDatecsOperatorInfo(const std::vector<uint8_t>& raw,OperatorInfoResult& out,std::string& error){DatecsResult r;if(!parseDatecsResult(raw,r,error)||r.fields.size()!=10){error="DATECS_OPERATOR_INFO";return false;}for(size_t i=0;i<5;i++){if(!uint32Value(r.fields[i*2],out.counts[i])||out.counts[i]>65535||!signedDecimal(r.fields[i*2+1],9,2)){error="DATECS_OPERATOR_INFO";return false;}out.sums[i]=r.fields[i*2+1];}return true;}
bool parseDatecsCurrencyConversion(const std::vector<uint8_t>& raw,std::string& out,std::string& error){DatecsResult r;if(!parseDatecsResult(raw,r,error)||r.fields.size()!=1||!decimal(r.fields[0],9,2,false)){error="DATECS_CURRENCY_CONVERSION";return false;}out=r.fields[0];return true;}
bool parseDatecsFiscalMemoryRead(const std::vector<uint8_t>& raw,uint8_t expectedBytes,std::vector<uint8_t>& out,std::string& error){DatecsResult r;if(expectedBytes<1||expectedBytes>104||!parseDatecsResult(raw,r,error)||r.fields.size()!=1||r.fields[0].size()!=static_cast<size_t>(expectedBytes)*2){error="DATECS_FISCAL_MEMORY_READ";return false;}out.clear();out.reserve(expectedBytes);for(size_t i=0;i<r.fields[0].size();i+=2){int high=hexNibble(r.fields[0][i]);int low=hexNibble(r.fields[0][i+1]);if(high<0||low<0){error="DATECS_FISCAL_MEMORY_READ";out.clear();return false;}out.push_back(static_cast<uint8_t>((high<<4)|low));}return true;}
bool parseDatecsDevicePowerNetwork(const std::vector<uint8_t>& raw,DevicePowerNetworkResult& out,std::string& error){DatecsResult r;if(!parseDatecsResult(raw,r,error)||r.fields.size()<2||r.fields.size()>4||!uint32Value(r.fields[0],out.mainBatteryMv)||out.mainBatteryMv>999999||!uint32Value(r.fields[1],out.ramBatteryMv)||out.ramBatteryMv>999999){error="DATECS_DEVICE_POWER_NETWORK";return false;}out.signalAvailable=r.fields.size()>2&&!r.fields[2].empty();out.networkAvailable=r.fields.size()>3&&!r.fields[3].empty();if(out.signalAvailable&&(!uint32Value(r.fields[2],out.signalPercent)||out.signalPercent>100)){error="DATECS_DEVICE_POWER_NETWORK";return false;}if(out.networkAvailable&&(r.fields[3]!="0"&&r.fields[3]!="1")){error="DATECS_DEVICE_POWER_NETWORK";return false;}out.networkRegistered=out.networkAvailable&&r.fields[3]=="1";return true;}
bool parseDatecsLastFiscalReceiptInfo(const std::vector<uint8_t>& raw,LastFiscalReceiptInfoResult& out,std::string& error){DatecsResult r;if(!parseDatecsResult(raw,r,error)||r.fields.size()!=4||!uint32Value(r.fields[0],out.receiptNumber)||out.receiptNumber<1||out.receiptNumber>9999||!documentedDateTime(r.fields[1])||!safeText(r.fields[1],24)||!uint32Value(r.fields[2],out.zReportNumber)||out.zReportNumber<1||out.zReportNumber>3650||!documentedDateTime(r.fields[3])||!safeText(r.fields[3],24)){error="DATECS_LAST_FISCAL_RECEIPT_INFO";return false;}out.receiptDateTime=r.fields[1];out.zReportDateTime=r.fields[3];return true;}
bool parseDatecsDeviceInfoVerification(const std::vector<uint8_t>& raw,std::string& error){DatecsResult r;if(!parseDatecsResult(raw,r,error)||!r.fields.empty()){error="DATECS_DEVICE_INFO_VERIFY";return false;}return true;}
bool parseDatecsDeviceBattery(const std::vector<uint8_t>& raw,DeviceBatteryResult& out,std::string& error){DatecsResult r;if(!parseDatecsResult(raw,r,error)||r.fields.size()!=2||!uint32Value(r.fields[0],out.mainBatteryMv)||out.mainBatteryMv>999999||!uint32Value(r.fields[1],out.chargePercent)||out.chargePercent>100){error="DATECS_DEVICE_BATTERY";return false;}return true;}
bool parseDatecsReceiptPeriodSearch(const std::vector<uint8_t>& raw,uint8_t documentType,ReceiptPeriodSearchResult& out,std::string& error){DatecsResult r;if(documentType>10||!parseDatecsResult(raw,r,error)||r.fields.size()!=4||!datePrefix(r.fields[0],true)||!safeText(r.fields[0],24)||!datePrefix(r.fields[1],true)||!safeText(r.fields[1],24)||!uint64Value(r.fields[2],out.firstDocument)||!uint64Value(r.fields[3],out.lastDocument)||out.firstDocument<1||out.lastDocument<out.firstDocument){error="DATECS_RECEIPT_PERIOD_SEARCH";return false;}const uint64_t max=documentLimit(documentType);if(out.firstDocument>max||out.lastDocument>max){error="DATECS_RECEIPT_PERIOD_SEARCH";return false;}out.startDateTime=r.fields[0];out.endDateTime=r.fields[1];return true;}
bool parseDatecsEjDocumentInfo(const std::vector<uint8_t>& raw,EjDocumentInfoResult& out,std::string& error){DatecsResult r;if(!parseDatecsResult(raw,r,error)||(r.fields.size()!=5&&r.fields.size()!=6)||!uint32Value(r.fields[0],out.globalDocumentNumber)||out.globalDocumentNumber<1||out.globalDocumentNumber>9999999||!uint64Value(r.fields[1],out.recordNumber)){error="DATECS_EJ_DOCUMENT_INFO";return false;}const bool splitDate=r.fields.size()==6;const std::string dt=splitDate?r.fields[2]+" "+r.fields[3]:r.fields[2];const size_t typeIndex=splitDate?4:3,zIndex=splitDate?5:4;uint32_t type=0;if(!documentedDateTime(dt)||!safeText(dt,24)||!uint32Value(r.fields[typeIndex],type)||type>9||!uint32Value(r.fields[zIndex],out.zReportNumber)||out.zReportNumber<1||out.zReportNumber>3650||out.recordNumber<1||out.recordNumber>documentLimit(static_cast<uint8_t>(type))){error="DATECS_EJ_DOCUMENT_INFO";return false;}out.dateTime=dt;out.documentType=static_cast<uint8_t>(type);return true;}
bool parseDatecsEjTextLine(const std::vector<uint8_t>& raw,std::string& out,std::string& error){DatecsResult r;if(!parseDatecsResult(raw,r,error)||r.fields.size()>1||(r.fields.size()==1&&(!safeText(r.fields[0],64)))){error="DATECS_EJ_TEXT_LINE";return false;}out=r.fields.empty()?"":r.fields[0];return true;}
bool parseDatecsEjBase64Data(const std::vector<uint8_t>& raw,std::string& out,std::string& error){DatecsResult r;if(!parseDatecsResult(raw,r,error)||r.fields.size()!=1||!base64Data(r.fields[0])){error="DATECS_EJ_BASE64";return false;}out=r.fields[0];return true;}
bool parseDatecsEjAcknowledge(const std::vector<uint8_t>& raw,std::string& error){return parseDatecsDeviceInfoVerification(raw,error);}
bool parseDatecsEjCsvRow(const std::vector<uint8_t>& raw,EjCsvRow& out,std::string& error){DatecsResult r;if(!parseDatecsResult(raw,r,error)||r.fields.empty()||r.fields.size()>14){error="DATECS_EJ_CSV_ROW";return false;}for(const auto& field:r.fields)if(!field.empty()&&!safeText(field,128)){error="DATECS_EJ_CSV_ROW";return false;}out.columns=r.fields;return true;}
bool parseDatecsFiscalMemoryCapacity(const std::vector<uint8_t>& raw,FiscalMemoryCapacityResult& out,std::string& error){DatecsResult r;if(!parseDatecsResult(raw,r,error)||r.fields.size()!=2||!uint32Value(r.fields[0],out.nonEmpty)||!uint32Value(r.fields[1],out.maximum)||out.nonEmpty>9999||out.maximum>9999||out.nonEmpty>out.maximum){error="DATECS_FM_CAPACITY";return false;}return true;}
bool parseDatecsFiscalMemoryZRecord(const std::vector<uint8_t>& raw,FiscalMemoryZRecordResult& out,std::string& error){DatecsResult r;if(!parseDatecsResult(raw,r,error)||r.fields.size()!=23||!uint32Value(r.fields[0],out.number)||out.number<1||out.number>9999||!fiscalMemoryDateTime(r.fields[1])){error="DATECS_FM_Z_RECORD";return false;}for(size_t i=0;i<8;i++){if(!decimal(r.fields[2+i],9,2,false)||!decimal(r.fields[11+i],9,2,false)){error="DATECS_FM_Z_RECORD";return false;}out.sales[i]=r.fields[2+i];out.reversals[i]=r.fields[11+i];}if(!decimal(r.fields[10],9,2,false)||!decimal(r.fields[19],9,2,false)||r.fields[20].size()!=40||!std::all_of(r.fields[20].begin(),r.fields[20].end(),[](unsigned char c){return std::isdigit(c)||(c>='A'&&c<='F');})||!uint32Value(r.fields[21],out.lastDocument)||out.lastDocument<1||out.lastDocument>9999999||!uint32Value(r.fields[22],out.klenNumber)||out.klenNumber<1||out.klenNumber>99){error="DATECS_FM_Z_RECORD";return false;}out.dateTime=r.fields[1];out.salesTotal=r.fields[10];out.reversalTotal=r.fields[19];out.hash=r.fields[20];return true;}
bool parseDatecsFiscalMemoryValueEvent(const std::vector<uint8_t>& raw,size_t maxValue,FiscalMemoryValueEventResult& out,std::string& error){DatecsResult r;if(!parseDatecsResult(raw,r,error)||(r.fields.size()!=2&&r.fields.size()!=3)||!safeText(r.fields[0],maxValue)){error="DATECS_FM_VALUE_EVENT";return false;}const std::string dt=r.fields.size()==3?r.fields[1]+" "+r.fields[2]:r.fields[1];if(!fiscalMemoryDateTime(dt)){error="DATECS_FM_VALUE_EVENT";return false;}out.value=r.fields[0];out.dateTime=dt;return true;}
bool parseDatecsFiscalMemoryDateEvent(const std::vector<uint8_t>& raw,std::string& out,std::string& error){DatecsResult r;if(!parseDatecsResult(raw,r,error)||(r.fields.size()!=1&&r.fields.size()!=2)){error="DATECS_FM_DATE_EVENT";return false;}out=r.fields.size()==2?r.fields[0]+" "+r.fields[1]:r.fields[0];if(!fiscalMemoryDateTime(out)){error="DATECS_FM_DATE_EVENT";return false;}return true;}
bool parseDatecsFiscalMemoryVatEvent(const std::vector<uint8_t>& raw,FiscalMemoryVatEventResult& out,std::string& error){DatecsResult r;if(!parseDatecsResult(raw,r,error)||(r.fields.size()!=11&&r.fields.size()!=12)){error="DATECS_FM_VAT_EVENT";return false;}for(size_t i=0;i<8;i++){if(!decimal(r.fields[i],3,2,false)){error="DATECS_FM_VAT_EVENT";return false;}out.rates[i]=r.fields[i];}uint32_t point=0;if(!uint32Value(r.fields[8],out.zReportNumber)||out.zReportNumber>9999||!uint32Value(r.fields[9],point)||(point!=0&&point!=2)){error="DATECS_FM_VAT_EVENT";return false;}out.decimalPoint=static_cast<uint8_t>(point);out.dateTime=r.fields.size()==12?r.fields[10]+" "+r.fields[11]:r.fields[10];if(!fiscalMemoryDateTime(out.dateTime)){error="DATECS_FM_VAT_EVENT";return false;}return true;}
bool parseDatecsFiscalMemoryCounterEvent(const std::vector<uint8_t>& raw,FiscalMemoryCounterEventResult& out,std::string& error){DatecsResult r;if(!parseDatecsResult(raw,r,error)||(r.fields.size()!=2&&r.fields.size()!=3)||!uint32Value(r.fields[0],out.zReportNumber)||out.zReportNumber>9999){error="DATECS_FM_COUNTER_EVENT";return false;}out.dateTime=r.fields.size()==3?r.fields[1]+" "+r.fields[2]:r.fields[1];if(!fiscalMemoryDateTime(out.dateTime)){error="DATECS_FM_COUNTER_EVENT";return false;}return true;}
bool parseDatecsFiscalMemoryKlenEvent(const std::vector<uint8_t>& raw,FiscalMemoryKlenEventResult& out,std::string& error){DatecsResult r;if(!parseDatecsResult(raw,r,error)||r.fields.size()<3||r.fields.size()>6||!uint32Value(r.fields[0],out.openLastReceipt)||out.openLastReceipt>9999999||!uint32Value(r.fields[1],out.openLastZReport)||out.openLastZReport>9999||!fiscalMemoryDateTime(r.fields[2])){error="DATECS_FM_KLEN_EVENT";return false;}out.openedAt=r.fields[2];out.closed=r.fields.size()==6;if(!out.closed)return true;if(!uint32Value(r.fields[3],out.closeLastReceipt)||out.closeLastReceipt>9999999||!uint32Value(r.fields[4],out.closeLastZReport)||out.closeLastZReport>9999||!fiscalMemoryDateTime(r.fields[5])){error="DATECS_FM_KLEN_EVENT";return false;}out.closedAt=r.fields[5];return true;}
bool parseDatecsModemIdentifier(const std::vector<uint8_t>& raw,std::string& out,std::string& error){DatecsResult r;if(!parseDatecsResult(raw,r,error)||r.fields.size()!=1||!digits(r.fields[0],1,15)){error="DATECS_MODEM_IDENTIFIER";return false;}out=r.fields[0];return true;}
bool parseDatecsModemStatus(const std::vector<uint8_t>& raw,ModemStatusResult& out,std::string& error){DatecsResult r;if(!parseDatecsResult(raw,r,error)||r.fields.size()!=4||!uint32Value(r.fields[0],out.signalPercent)||out.signalPercent>100||!digits(r.fields[1],1,15)||!digits(r.fields[2],1,15)||!safeText(r.fields[3],64)){error="DATECS_MODEM_STATUS";return false;}out.imei=r.fields[1];out.imsi=r.fields[2];out.mobileOperator=r.fields[3];return true;}
bool parseDatecsSlipNumber(const std::vector<uint8_t>& raw,uint32_t& out,std::string& error){DatecsResult r;if(!parseDatecsResult(raw,r,error)||r.fields.size()!=1||!uint32Value(r.fields[0],out)||out<1||out>9999999){error="DATECS_SLIP_NUMBER";return false;}return true;}
bool parseDatecsAcknowledge(const std::vector<uint8_t>& raw,std::string& error){DatecsResult r;if(!parseDatecsResult(raw,r,error)||!r.fields.empty()){error="DATECS_ACKNOWLEDGE";return false;}return true;}
bool parseDatecsNapConnection(const std::vector<uint8_t>& raw,NapConnectionResult& out,std::string& error){DatecsResult r;if(!parseDatecsResult(raw,r,error)||r.fields.size()!=13||!documentedDateTime(r.fields[0])||!documentedDateTime(r.fields[1])||!uint32Value(r.fields[2],out.lastZReport)||out.lastZReport>3650||!uint32Value(r.fields[3],out.zReportWithError)||out.zReportWithError>3650||!uint32Value(r.fields[4],out.zErrorCount)||out.zErrorCount>65535||!negativeOrZeroInt(r.fields[5],out.zErrorStatus,-99)||!uint32Value(r.fields[6],out.saleDocumentWithError)||out.saleDocumentWithError>9999999||!uint32Value(r.fields[7],out.saleErrorCount)||out.saleErrorCount>65535||!negativeOrZeroInt(r.fields[8],out.saleErrorStatus,-99)||!uint32Value(r.fields[9],out.lastReceivedSaleDocument)||out.lastReceivedSaleDocument>9999999||!documentedDateTime(r.fields[10])||!uint32Value(r.fields[11],out.lastError)||!uint32Value(r.fields[12],out.remainingMinutes)||out.remainingMinutes>255){error="DATECS_NAP_CONNECTION";return false;}out.lastConnection=r.fields[0];out.nextConnection=r.fields[1];out.lastReceivedSaleDateTime=r.fields[10];return true;}
bool parseDatecsClientInfo(const std::vector<uint8_t>& raw,ClientDirectoryInfoResult& out,std::string& error){DatecsResult r;uint32_t total=0,programmed=0,nameLength=0;if(!parseDatecsResult(raw,r,error)||r.fields.size()!=3||!uint32Value(r.fields[0],total)||total!=1000||!uint32Value(r.fields[1],programmed)||programmed>total||!uint32Value(r.fields[2],nameLength)||nameLength!=36){error="DATECS_CLIENT_INFO";return false;}out.total=static_cast<uint16_t>(total);out.programmed=static_cast<uint16_t>(programmed);out.nameLength=static_cast<uint8_t>(nameLength);return true;}
bool parseDatecsClientRecord(const std::vector<uint8_t>& raw,ClientRecordResult& out,std::string& error){DatecsResult r;uint32_t index=0,type=0;if(!parseDatecsResult(raw,r,error)||r.fields.size()<5||r.fields.size()>8){error="DATECS_CLIENT_RECORD";return false;}r.fields.resize(8);if(!uint32Value(r.fields[0],index)||index<1||index>1000||!digits(r.fields[1],9,13)||!uint32Value(r.fields[2],type)||type>3||!optionalSafeText(r.fields[3],14)||!safeText(r.fields[4],36)||!optionalSafeText(r.fields[5],36)||!optionalSafeText(r.fields[6],36)||!optionalSafeText(r.fields[7],36)){error="DATECS_CLIENT_RECORD";return false;}out.index=static_cast<uint16_t>(index);out.taxNumber=r.fields[1];out.taxNumberType=static_cast<uint8_t>(type);out.vatNumber=r.fields[3];out.name=r.fields[4];out.receiverName=r.fields[5];out.address1=r.fields[6];out.address2=r.fields[7];return true;}
bool parseDatecsClientIndex(const std::vector<uint8_t>& raw,uint16_t& out,std::string& error){DatecsResult r;uint32_t index=0;if(!parseDatecsResult(raw,r,error)||r.fields.size()!=1||!uint32Value(r.fields[0],index)||index<1||index>1000){error="DATECS_CLIENT_INDEX";return false;}out=static_cast<uint16_t>(index);return true;}
bool parseDaisyTaxRates(const std::vector<uint8_t>& raw,DaisyTaxRatesResult& out,std::string& error){
  const auto fields=split(raw,',');if(fields.empty()||(fields[0]!="F"&&fields[0]!="P")){error="DAISY_TAX_RATES";return false;}out={};out.found=fields[0]=="P";if(!out.found){if(fields.size()!=1){error="DAISY_TAX_RATES";return false;}return true;}if(fields.size()!=10||!daisyDate(fields[9])){error="DAISY_TAX_RATES";return false;}for(size_t i=0;i<8;i++){if(!decimal(fields[i+1],3,2,false)){error="DAISY_TAX_RATES";return false;}out.rates[i]=fields[i+1];}out.effectiveDate=fields[9];return true;
}
bool parseDaisySubtotal(const std::vector<uint8_t>& raw,DaisyFiscalTotalsResult& out,std::string& subtotal,std::string& error){
  const auto fields=split(raw,',');if(fields.size()!=9||!decimal(fields[0],10,2,false)){error="DAISY_SUBTOTAL_RESULT";return false;}subtotal=fields[0];for(size_t i=0;i<8;i++){if(!decimal(fields[i+1],10,2,false)){error="DAISY_SUBTOTAL_RESULT";return false;}out.sales[i]=fields[i+1];}out.reversals={};return true;
}
bool parseDaisyDateTime(const std::vector<uint8_t>& raw,std::string& out,std::string& error){out.assign(raw.begin(),raw.end());if(!daisyDateTime(out)){error="DAISY_DATE_TIME";return false;}return true;}
bool parseDaisyLastFiscalRecord(const std::vector<uint8_t>& raw,DaisyLastFiscalRecordResult& out,std::string& error){
  const auto fields=split(raw,',');if(fields.size()!=18||!uint32Value(fields[0],out.reportNumber)||out.reportNumber>999999||!daisyDate(fields[17])){error="DAISY_LAST_FISCAL_RECORD";return false;}for(size_t i=0;i<8;i++){if(!decimal(fields[i+1],10,2,false)||!decimal(fields[i+9],10,2,false)){error="DAISY_LAST_FISCAL_RECORD";return false;}out.sales[i]=fields[i+1];out.reversals[i]=fields[i+9];}out.date=fields[17];return true;
}
bool parseDaisyCurrentFiscalTotals(const std::vector<uint8_t>& raw,DaisyFiscalTotalsResult& out,std::string& error){
  const auto fields=split(raw,',');if(fields.size()!=16){error="DAISY_CURRENT_FISCAL_TOTALS";return false;}for(size_t i=0;i<8;i++){if(!decimal(fields[i],10,2,false)||!decimal(fields[i+8],10,2,false)){error="DAISY_CURRENT_FISCAL_TOTALS";return false;}out.sales[i]=fields[i];out.reversals[i]=fields[i+8];}return true;
}
bool parseDaisyFiscalization(const std::vector<uint8_t>& raw,DaisyFiscalizationResult& out,std::string& error){
  const auto fields=split(raw,',');if(fields.size()!=3||!daisyDate(fields[0])||!uint32Value(fields[1],out.lastBgnReport)||!uint32Value(fields[2],out.lastReport)||out.lastBgnReport>out.lastReport){error="DAISY_FISCALIZATION";return false;}out.date=fields[0];return true;
}
bool parseDaisyFreeFiscalRecords(const std::vector<uint8_t>& raw,DaisyFreeFiscalRecordsResult& out,std::string& error){
  const auto fields=split(raw,',');if(fields.size()!=2||!uint32Value(fields[0],out.logical)||!uint32Value(fields[1],out.physical)||out.logical!=out.physical){error="DAISY_FREE_FISCAL_RECORDS";return false;}return true;
}
bool parseDaisyDiagnostic(const std::vector<uint8_t>& raw,DaisyDiagnosticResult& out,std::string& error){
  const auto fields=split(raw,',');if(fields.size()!=6){error="DAISY_DIAGNOSTIC";return false;}const auto first=split(std::vector<uint8_t>(fields[0].begin(),fields[0].end()),' ');uint32_t country=0;if(first.size()!=3||first[0].size()<6||first[0].size()>30||!safeText(first[0],30)||!fullDateTime(first[1]+" 00:00:00")||fields[1].size()!=4||!std::all_of(fields[1].begin(),fields[1].end(),[](unsigned char c){return std::isdigit(c)||(c>='A'&&c<='F');})||!digits(fields[2],4,4)||!uint32Value(fields[3],country)||country>255||!safeText(fields[4],32)||!safeText(fields[5],32)){error="DAISY_DIAGNOSTIC";return false;}if(first[2].size()!=5||first[2][2]!=':'||!digits(first[2].substr(0,2),2,2)||!digits(first[2].substr(3,2),2,2)){error="DAISY_DIAGNOSTIC";return false;}out={first[0],first[1],first[2],fields[1],fields[2],static_cast<uint8_t>(country),fields[4],fields[5]};return true;
}
bool parseDaisyCurrentTaxRates(const std::vector<uint8_t>& raw,std::array<std::string,8>& out,std::string& error){const auto fields=split(raw,',');if(fields.size()!=8){error="DAISY_CURRENT_TAX_RATES";return false;}for(size_t i=0;i<8;i++){if(!decimal(fields[i],3,2,false)){error="DAISY_CURRENT_TAX_RATES";return false;}out[i]=fields[i];}return true;}
bool parseDaisyTaxNumber(const std::vector<uint8_t>& raw,std::string& out,bool& fiscalized,std::string& error){out.assign(raw.begin(),raw.end());if(out.size()<8||out.size()>13||!safeText(out,13)){error="DAISY_TAX_NUMBER";return false;}const bool allMinus=std::all_of(out.begin(),out.end(),[](char c){return c=='-';});const bool identifier=std::all_of(out.begin(),out.end(),[](unsigned char c){return std::isalnum(c)!=0;});if(!allMinus&&!identifier){error="DAISY_TAX_NUMBER";return false;}fiscalized=!allMinus;return true;}
bool parseDaisyReceiptInfo(const std::vector<uint8_t>& raw,DaisyReceiptInfoResult& out,std::string& error){const auto fields=split(raw,',');if(fields.size()!=10&&fields.size()!=11){error="DAISY_RECEIPT_INFO";return false;}if((fields[0]!="0"&&fields[0]!="1")||(fields[9]!="0"&&fields[9]!="1")){error="DAISY_RECEIPT_INFO";return false;}out.canVoid=fields[0]=="1";for(size_t i=0;i<8;i++){if(!decimal(fields[i+1],10,2,false)){error="DAISY_RECEIPT_INFO";return false;}out.taxTotals[i]=fields[i+1];}out.invoice=fields[9]=="1";out.nextInvoiceNumber=fields.size()==11?fields[10]:"";if((out.invoice&&!digits(out.nextInvoiceNumber,10,10))||(!out.invoice&&!out.nextInvoiceNumber.empty())){error="DAISY_RECEIPT_INFO";return false;}return true;}
bool parseDaisyLastDocumentNumber(const std::vector<uint8_t>& raw,uint32_t& out,std::string& error){const std::string value(raw.begin(),raw.end());if(!uint32Value(value,out)||out>9999999){error="DAISY_LAST_DOCUMENT";return false;}return true;}
bool parseDaisyFirstUnsentReceipt(const std::vector<uint8_t>& raw,uint32_t& document,bool& allSent,std::string& deviceError,std::string& error){const std::string value(raw.begin(),raw.end());document=0;allSent=false;deviceError.clear();if(value=="---"){allSent=true;return true;}if(value.size()>5&&value.rfind("error",0)==0&&digits(value.substr(5),1,3)){deviceError=value;return true;}if(!uint32Value(value,document)||document<1||document>9999999){error="DAISY_FIRST_UNSENT";return false;}return true;}
bool parseDaisyFirmware(const std::vector<uint8_t>& raw,DaisyFirmwareResult& out,std::string& error){const auto fields=split(raw,',');if(fields.size()!=3||fields[0].size()!=2||(fields[0][0]!='0'&&fields[0][0]!='1')||(fields[0][1]!='0'&&fields[0][1]!='1')||!safeText(fields[1],64)||!safeText(fields[2],64)){error="DAISY_FIRMWARE";return false;}out={fields[0][0]=='1',fields[0][1]=='1',fields[1],fields[2]};return true;}
bool parseDaisyErrorDescription(const std::vector<uint8_t>& raw,uint8_t requested,DaisyErrorDescriptionResult& out,std::string& error){const auto fields=split(raw,',');uint32_t code=0;if(requested<1||requested>127||fields.size()!=2||!uint32Value(fields[0],code)||code!=requested||!safeText(fields[1],160)){error="DAISY_ERROR_DESCRIPTION";return false;}out={static_cast<uint8_t>(code),fields[1]};return true;}
bool parseDaisyCurrencyTransitionInfo(const std::vector<uint8_t>& raw,DaisyCurrencyTransitionResult& out,std::string& error){const auto fields=split(raw,',');uint32_t zone=0;if(fields.size()!=8||!uint32Value(fields[0],zone)||zone>4||(fields[1]!="0"&&fields[1]!="1")){error="DAISY_CURRENCY_TRANSITION_INFO";return false;}for(size_t i=0;i<4;i++)if(!daisyDateOrUnset(fields[i+2])){error="DAISY_CURRENCY_TRANSITION_INFO";return false;}if(!exactDecimal(fields[6],2,5)||!daisyDateOrUnset(fields[7])){error="DAISY_CURRENCY_TRANSITION_INFO";return false;}out.zone=static_cast<uint8_t>(zone);out.dailyReportRequired=fields[1]=="1";for(size_t i=0;i<4;i++)out.dates[i]=fields[i+2];out.currencyRate=fields[6];out.lastFiscalMemoryDate=fields[7];return true;}
bool parseDaisyCurrencyTransitionDate(const std::vector<uint8_t>& raw,uint8_t number,DaisyCurrencyTransitionDateResult& out,std::string& error){const auto fields=split(raw,',');if(number<1||number>4||fields.empty()||fields.size()>2||!daisyDateOrUnset(fields[0])||(number==2&&(fields.size()!=2||!exactDecimal(fields[1],2,5)))||(number!=2&&fields.size()!=1)){error="DAISY_CURRENCY_TRANSITION_DATE";return false;}out.date=fields[0];out.currencyRate=fields.size()==2?fields[1]:"";return true;}
bool parseDaisyPassFail(const std::vector<uint8_t>& raw,bool& passed,std::string& error){if(raw.size()!=1||(raw[0]!='P'&&raw[0]!='F')){error="DAISY_PASS_FAIL";return false;}passed=raw[0]=='P';return true;}
bool parseDaisyDailyReport(const std::vector<uint8_t>& raw,DaisyDailyReportResult& out,std::string& error){const auto fields=split(raw,',');if(fields.size()!=17||!uint32Value(fields[0],out.closure)||out.closure>9999){error="DAISY_DAILY_REPORT";return false;}for(size_t i=0;i<8;i++){if(!decimal(fields[i+1],10,2,false)||!decimal(fields[i+9],10,2,false)){error="DAISY_DAILY_REPORT";return false;}out.totals.sales[i]=fields[i+1];out.totals.reversals[i]=fields[i+9];}return true;}
bool parseDaisyCurrentDay(const std::vector<uint8_t>& raw,DaisyCurrentDayResult& out,std::string& error){const auto fields=split(raw,',');if(fields.size()<8||!uint32Value(fields[fields.size()-3],out.lastZReport)||!uint32Value(fields[fields.size()-2],out.nextDocument)||!digits(fields.back(),10,10)){error="DAISY_CURRENT_DAY";return false;}out.payments.assign(fields.begin(),fields.end()-3);if(out.payments.size()<5||out.payments.size()>65||std::any_of(out.payments.begin(),out.payments.end(),[](const std::string& v){return !decimal(v,10,2,false);})){error="DAISY_CURRENT_DAY";return false;}out.nextInvoice=fields.back();return true;}
bool parseDaisyOperatorInfo(const std::vector<uint8_t>& raw,DaisyOperatorResult& out,std::string& error){const auto sections=split(raw,'\t');if(sections.size()!=2){error="DAISY_OPERATOR_INFO";return false;}const std::vector<uint8_t> firstRaw(sections[0].begin(),sections[0].end()),refundRaw(sections[1].begin(),sections[1].end());const auto first=split(firstRaw,','),refunds=split(refundRaw,',');if(first.size()!=6||refunds.size()!=6||!uint32Value(first[0],out.receipts)||!countAmount(first[1],out.sales)||!countAmount(first[2],out.discounts)||!countAmount(first[3],out.surcharges)||!countAmount(first[4],out.voids)||!safeText(first[5],64)){error="DAISY_OPERATOR_INFO";return false;}out.name=first[5];for(size_t i=0;i<3;i++){if(refunds[i]!="0"&&refunds[i]!="1"){error="DAISY_OPERATOR_INFO";return false;}out.refundEnabled[i]=refunds[i]=="1";if(!countAmount(refunds[i+3],out.refunds[i])){error="DAISY_OPERATOR_INFO";return false;}}return true;}
bool parseDaisyFmInformation(const std::vector<uint8_t>& raw,uint8_t option,DaisyFmQueryResult& out,std::string& error){const auto fields=split(raw,',');if(option>6||fields.empty()||fields[0].size()!=1){error="DAISY_FM_INFORMATION";return false;}if(fields[0]=="F"||fields[0]=="E"){if(fields.size()!=1){error="DAISY_FM_INFORMATION";return false;}out.state=fields[0]=="F"?DaisyFmQueryState::InvalidChecksum:DaisyFmQueryState::NoData;out.hasReversals=false;return true;}const size_t expected=option==3?9:17;if(fields[0]!="P"||fields.size()!=expected){error="DAISY_FM_INFORMATION";return false;}for(size_t i=0;i<8;i++){if(!decimal(fields[i+1],10,option==3?3:2,false)){error="DAISY_FM_INFORMATION";return false;}out.values[i]=fields[i+1];if(option!=3){if(!decimal(fields[i+9],10,2,false)){error="DAISY_FM_INFORMATION";return false;}out.reversals[i]=fields[i+9];}}out.state=DaisyFmQueryState::Valid;out.hasReversals=option!=3;return true;}
bool parseDaisyQrDocument(const std::vector<uint8_t>& raw,DaisyQrDocumentResult& out,std::string& error){if(raw.size()==1&&raw[0]=='F'){out={};return true;}if(raw.size()<4||raw[0]!='P'||(raw[1]!='F'&&raw[1]!='S')||raw[2]!=','){error="DAISY_QR_DOCUMENT";return false;}const std::string data(raw.begin()+3,raw.end());out.found=true;out.overallType=static_cast<char>(raw[1]);if(data=="XXXXX"){out.hasQr=false;out.qrData.clear();return true;}const auto comma=data.find(',');uint32_t type=0;if(comma==std::string::npos||!uint32Value(data.substr(0,comma),type)||type>255||!safeText(data.substr(comma+1),200)){error="DAISY_QR_DOCUMENT";return false;}out.hasQr=true;out.documentType=static_cast<uint8_t>(type);out.qrData=data.substr(comma+1);return true;}
bool parseDaisyIssuedDocument(const std::vector<uint8_t>& raw,bool requestedSha1,DaisyIssuedDocumentResult& out,std::string& error){if(raw.size()==1&&raw[0]=='F'){out={};return true;}if(raw.size()<2||raw[0]!='P'){error="DAISY_ISSUED_DOCUMENT";return false;}std::string value(raw.begin()+1,raw.end()),sha;const auto shaPos=value.find(",SHA1:");if(shaPos!=std::string::npos){sha=value.substr(shaPos+6);value.resize(shaPos);}if(requestedSha1?sha.empty():!sha.empty()){error="DAISY_ISSUED_DOCUMENT";return false;}const std::vector<uint8_t> valueRaw(value.begin(),value.end());const auto fields=split(valueRaw,'\t');if((fields.size()!=8&&fields.size()!=11)||!uint32Value(fields[0],out.number)||!daisyLongDateTime(fields[1])){error="DAISY_ISSUED_DOCUMENT";return false;}uint32_t desc=0,type=0,transactions=0;if(!uint32Value(fields[2],desc)||desc>255||!uint32Value(fields[3],type)||type>255||!uint32Value(fields[4],transactions)||(fields[5]!="0"&&fields[5]!="1")||(!fields[6].empty()&&!validUNP(fields[6]))||!digits(fields[7],1,10)){error="DAISY_ISSUED_DOCUMENT";return false;}out.found=true;out.issuedAt=fields[1];out.description=static_cast<uint8_t>(desc);out.type=static_cast<uint8_t>(type);out.transactions=transactions;out.multiplier100=fields[5]=="1";out.unp=fields[6];out.invoiceNumber=fields[7];out.linkedFiscalMemoryNumber.clear();out.linkedDocument=0;out.linkedInvoiceNumber.clear();if(fields.size()==11){if(!safeText(fields[8],13)||!uint32Value(fields[9],out.linkedDocument)||!digits(fields[10],1,10)){error="DAISY_ISSUED_DOCUMENT";return false;}out.linkedFiscalMemoryNumber=fields[8];out.linkedInvoiceNumber=fields[10];}if(!sha.empty()&&!sha1ReportValue(sha)){error="DAISY_ISSUED_DOCUMENT";return false;}out.sha1=sha;return true;}
bool parseDaisyConstants(const std::vector<uint8_t>& raw,DaisyConstantsResult& out,std::string& error){const auto fields=split(raw,',');uint32_t numbers[7]{};const size_t indexes[]={0,1,2,3,15,16,20};if(fields.size()!=26){error="DAISY_CONSTANTS";return false;}for(size_t i=0;i<26;i++)if(!fields[i].empty()&&!digits(fields[i],1,10)&&i!=6){error="DAISY_CONSTANTS";return false;}for(size_t i=0;i<7;i++)if(!uint32Value(fields[indexes[i]],numbers[i])){error="DAISY_CONSTANTS";return false;}if(numbers[0]>4096||numbers[1]>4096||numbers[2]<1||numbers[2]>64||numbers[3]!=8||numbers[4]>999||numbers[5]>1000000||numbers[6]>999){error="DAISY_CONSTANTS";return false;}out.values={};for(size_t i=0;i<26;i++)out.values[i]=fields[i];out.logoWidth=static_cast<uint16_t>(numbers[0]);out.logoHeight=static_cast<uint16_t>(numbers[1]);out.paymentCount=static_cast<uint8_t>(numbers[2]);out.taxGroupCount=static_cast<uint8_t>(numbers[3]);out.departmentCount=static_cast<uint16_t>(numbers[4]);out.pluCount=numbers[5];out.operatorCount=static_cast<uint16_t>(numbers[6]);return true;}
bool parseDaisyTextReportLine(const std::vector<uint8_t>& raw,DaisyTextReportLine& out,std::string& error){if(raw.size()==5&&raw[0]==0x1a&&raw[1]=='\t'&&raw[2]=='E'&&raw[3]=='\r'&&raw[4]=='\n'){out={};out.font='E';out.end=true;return true;}if(raw.size()<12||raw[0]!=0x1a||raw[7]!='\t'||(raw[8]!='N'&&raw[8]!='B')||raw[9]!='\t'||raw[raw.size()-2]!='\r'||raw.back()!='\n'){error="DAISY_TEXT_REPORT_LINE";return false;}const std::string line(raw.begin()+1,raw.begin()+7),text(raw.begin()+10,raw.end()-2);if(!digits(line,6,6)||text.empty()||text.size()>256||std::any_of(text.begin(),text.end(),[](char c){return c=='\r'||c=='\n';})||!uint32Value(line,out.lineNumber)){error="DAISY_TEXT_REPORT_LINE";return false;}out.font=static_cast<char>(raw[8]);out.text=text;out.end=false;return true;}
bool parseDaisyNoData(const std::vector<uint8_t>& raw,std::string& error){if(!raw.empty()){error="DAISY_EXPECTED_NO_DATA";return false;}return true;}
bool parseDaisyCustomerQr(const std::vector<uint8_t>& raw,char operation,bool& passed,std::vector<std::string>& fields,std::string& error){fields.clear();if(operation=='Q'){passed=raw.empty();if(!passed)error="DAISY_CUSTOMER_QR_RESPONSE";return passed;}const std::string value(raw.begin(),raw.end());if(operation=='P'){if(value=="P"){passed=true;return true;}if(value.size()>=2&&value[0]=='F'&&digits(value.substr(1),1,3)){passed=false;fields.push_back(value.substr(1));return true;}}else if(operation=='R'){const auto parsed=split(raw,',');if(!parsed.empty()&&std::all_of(parsed.begin(),parsed.end(),qrTemplateId)){passed=true;fields=parsed;return true;}}error="DAISY_CUSTOMER_QR_RESPONSE";return false;}
bool parseDaisyCustomerRecord(const std::vector<uint8_t>& raw,DaisyCustomerRecord& out,bool& found,std::string& error){if(raw.size()==1&&raw[0]=='F'){found=false;out={};return true;}if(raw.size()<4||raw[0]!='P'||raw[1]!=','||raw[2]!='P'){error="DAISY_CUSTOMER_RECORD";return false;}const std::vector<uint8_t> data(raw.begin()+3,raw.end());auto fields=split(data,'\t');if(fields.empty()||fields.size()>6){error="DAISY_CUSTOMER_RECORD";return false;}fields.resize(6);if(!safeText(fields[0],32)||std::any_of(fields.begin()+1,fields.end(),[](const std::string& v){return !optionalSafeText(v,64);})){error="DAISY_CUSTOMER_RECORD";return false;}out={fields[0],fields[1],fields[2],fields[3],fields[4],fields[5]};found=true;return true;}
bool parseDaisyBattery(const std::vector<uint8_t>& raw,DaisyBatteryResult& out,std::string& error){const auto fields=split(raw,' ');uint32_t voltage=0,capacity=0;if(fields.size()!=2||!uint32Value(fields[0],voltage)||voltage>4000||!uint32Value(fields[1],capacity)||capacity>100){error="DAISY_BATTERY";return false;}out={static_cast<uint16_t>(voltage),static_cast<uint8_t>(capacity)};return true;}
bool parseDaisyOpenReceiptResult(const std::vector<uint8_t>& raw,uint32_t& all,uint32_t& fiscal,std::string& error){
  const auto fields=split(raw,',');if(fields.size()!=2||!uint32Value(fields[0],all)||!uint32Value(fields[1],fiscal)){error="DAISY_OPEN_RESULT";return false;}return true;
}
bool parseDaisyReceiptStatus(const std::vector<uint8_t>& raw,ReceiptStatusResult& out,std::string& error){
  const auto fields=split(raw,',');if(fields.size()<3||fields[0].size()!=1||fields[0][0]<'0'||fields[0][0]>'1'||!uint32Value(fields[1],out.items)||!decimal(fields[2],10,2,false)){error="DAISY_RECEIPT_STATUS";return false;}out.openState=static_cast<uint8_t>(fields[0][0]-'0');out.receiptNumber=0;out.amount=fields[2];if(fields.size()>=5){out.paid=fields[3];}return true;
}
bool parseDatecsReceiptStatus(const std::vector<uint8_t>& raw,ReceiptStatusResult& out,std::string& error){
  DatecsResult result;if(!parseDatecsResult(raw,result,error)||result.errorCode!=0||result.fields.size()<5||!digits(result.fields[0],1,1)||!uint32Value(result.fields[1],out.receiptNumber)||!uint32Value(result.fields[2],out.items)||!decimal(result.fields[3],7,2,false)||!decimal(result.fields[4],7,2,false)){error="DATECS_RECEIPT_STATUS";return false;}out.openState=static_cast<uint8_t>(result.fields[0][0]-'0');if(out.openState>9){error="DATECS_RECEIPT_STATUS";return false;}out.amount=result.fields[3];out.paid=result.fields[4];return true;
}
}
