#include "CommandPayload.hpp"
#include <algorithm>
#include <cctype>
#include <climits>
#include <cstdlib>

namespace bee { namespace {
bool digits(const std::string& value, size_t min, size_t max) {
  return value.size() >= min && value.size() <= max &&
    std::all_of(value.begin(), value.end(), [](unsigned char c){ return std::isdigit(c) != 0; });
}
bool decimal(const std::string& value, size_t integerDigits, size_t fractionDigits, bool positive) {
  if(value.empty() || value[0]=='+' || value[0]=='-') return false;
  const auto dot=value.find('.');
  if(dot!=std::string::npos && value.find('.',dot+1)!=std::string::npos) return false;
  const auto integers=dot==std::string::npos?value.size():dot;
  const auto fraction=dot==std::string::npos?0:value.size()-dot-1;
  if(integers<1 || integers>integerDigits || fraction>fractionDigits || (dot!=std::string::npos&&fraction==0)) return false;
  for(size_t i=0;i<value.size();++i) if(i!=dot && !std::isdigit(static_cast<unsigned char>(value[i]))) return false;
  if(positive && std::all_of(value.begin(),value.end(),[](char c){return c=='0'||c=='.';})) return false;
  return true;
}
bool signedDecimal(const std::string& value,size_t integerDigits,size_t fractionDigits){if(value.empty()||value[0]=='+')return false;return value[0]=='-'?decimal(value.substr(1),integerDigits,fractionDigits,false):decimal(value,integerDigits,fractionDigits,false);}
bool safeText(const std::string& value,size_t max) {
  return !value.empty() && value.size()<=max && std::none_of(value.begin(),value.end(),[](char c){return c=='\t'||c=='\r'||c=='\n'||static_cast<unsigned char>(c)<0x20;});
}
bool validUNP(const std::string& value) {
  if(value.size()!=21 || value[8]!='-' || value[13]!='-') return false;
  if(!std::isupper(static_cast<unsigned char>(value[0])) || !std::isupper(static_cast<unsigned char>(value[1]))) return false;
  for(size_t i=2;i<8;i++) if(!std::isdigit(static_cast<unsigned char>(value[i]))) return false;
  for(size_t i=9;i<13;i++) if(!std::isupper(static_cast<unsigned char>(value[i]))&&!std::isdigit(static_cast<unsigned char>(value[i]))) return false;
  for(size_t i=14;i<21;i++) if(!std::isdigit(static_cast<unsigned char>(value[i]))) return false;
  return true;
}
void append(std::vector<uint8_t>& out,const std::string& value){out.insert(out.end(),value.begin(),value.end());}
void tab(std::vector<uint8_t>& out){out.push_back(0x09);}
std::vector<std::string> split(const std::vector<uint8_t>& raw,char separator){std::vector<std::string> out(1);for(uint8_t c:raw){if(c==static_cast<uint8_t>(separator))out.emplace_back();else out.back().push_back(static_cast<char>(c));}while(!out.empty()&&out.back().empty())out.pop_back();return out;}
bool uint32Value(const std::string& value,uint32_t& out){if(!digits(value,1,10))return false;unsigned long x=std::strtoul(value.c_str(),nullptr,10);if(x>UINT_MAX)return false;out=static_cast<uint32_t>(x);return true;}
bool uint64Value(const std::string& value,uint64_t& out){if(!digits(value,1,10))return false;char* end=nullptr;unsigned long long x=std::strtoull(value.c_str(),&end,10);if(!end||*end!='\0')return false;out=static_cast<uint64_t>(x);return true;}
bool datePrefix(const std::string& value,bool withTime){const size_t need=withTime?17:8;if(value.size()<need)return false;const size_t separators[]={2,5};for(size_t i=0;i<8;i++){if(i==separators[0]||i==separators[1]){if(value[i]!='-')return false;}else if(!std::isdigit(static_cast<unsigned char>(value[i])))return false;}if(!withTime)return true;if(value[8]!=' '||value[11]!=':'||value[14]!=':')return false;for(size_t i=9;i<17;i++)if(i!=11&&i!=14&&!std::isdigit(static_cast<unsigned char>(value[i])))return false;return true;}
bool fullDateTime(const std::string& value){if(value.size()!=19||value[2]!='-'||value[5]!='-'||value[10]!=' '||value[13]!=':'||value[16]!=':')return false;for(size_t i=0;i<value.size();i++)if(i!=2&&i!=5&&i!=10&&i!=13&&i!=16&&!std::isdigit(static_cast<unsigned char>(value[i])))return false;return true;}
bool documentedDateTime(const std::string& value){return datePrefix(value,true)||fullDateTime(value);}
bool fiscalMemoryDateTime(const std::string& value){if(documentedDateTime(value))return true;if(value.size()!=16||value[2]!='-'||value[5]!='-'||value[10]!=' '||value[13]!=':')return false;for(size_t i=0;i<value.size();i++)if(i!=2&&i!=5&&i!=10&&i!=13&&!std::isdigit(static_cast<unsigned char>(value[i])))return false;return true;}
bool negativeInt(const std::string& value,int& out){if(value.size()<2||value[0]!='-'||!digits(value.substr(1),1,6))return false;long x=std::strtol(value.c_str(),nullptr,10);if(x<INT_MIN||x>=0)return false;out=static_cast<int>(x);return true;}
bool negativeOrZeroInt(const std::string& value,int& out,int minimum){if(value=="0"){out=0;return true;}if(!negativeInt(value,out)||out<minimum)return false;return true;}
bool hexAddress(const std::string& value){return value.size()>=1&&value.size()<=6&&std::all_of(value.begin(),value.end(),[](unsigned char c){return std::isdigit(c)||(c>='A'&&c<='F');});}
int hexNibble(char c){if(c>='0'&&c<='9')return c-'0';if(c>='A'&&c<='F')return c-'A'+10;return -1;}
bool base64Data(const std::string& value){if(value.empty()||value.size()>4096||value.size()%4!=0)return false;size_t padding=0;for(size_t i=0;i<value.size();i++){char c=value[i];if(c=='='){padding++;if(i<value.size()-2||padding>2)return false;}else if(padding||!(std::isalnum(static_cast<unsigned char>(c))||c=='+'||c=='/'))return false;}return true;}
uint64_t documentLimit(uint8_t type){return type==2?3650:(type==3||type==7?9999999999ULL:9999999ULL);}
}

bool buildDaisyOpenReceipt(const OpenReceiptPayload& in,std::vector<uint8_t>& out,std::string& error){
  if(in.operatorNumber<1||in.operatorNumber>30||!digits(in.password,1,6)||!validUNP(in.unp)){error="DAISY_OPEN_FIELDS";return false;}
  out.clear();append(out,std::to_string(in.operatorNumber));out.push_back(',');append(out,in.password);out.push_back(',');append(out,in.unp);if(in.invoice){tab(out);out.push_back('I');}return true;
}
bool buildDatecsOpenReceipt(const OpenReceiptPayload& in,std::vector<uint8_t>& out,std::string& error){
  if(in.operatorNumber<1||in.operatorNumber>30||!digits(in.password,1,8)||!validUNP(in.unp)||in.tillNumber<1||in.tillNumber>99999){error="DATECS_OPEN_FIELDS";return false;}
  out.clear();append(out,std::to_string(in.operatorNumber));tab(out);append(out,in.password);tab(out);append(out,in.unp);tab(out);append(out,std::to_string(in.tillNumber));tab(out);if(in.invoice)out.push_back('I');tab(out);return true;
}
bool buildDaisySaleItem(const SaleItemPayload& in,std::vector<uint8_t>& out,std::string& error){
  if(!safeText(in.name,72)||in.taxGroup<'A'||in.taxGroup>'H'||!decimal(in.unitPrice,8,2,true)||!decimal(in.quantity,8,3,true)||in.discountType>4||(in.discountType&& !decimal(in.discountValue,8,2,true))){error="DAISY_ITEM_FIELDS";return false;}
  out.clear();append(out,in.name);tab(out);out.push_back(static_cast<uint8_t>(0xC0+(in.taxGroup-'A')));append(out,in.unitPrice);if(in.quantity!="1.000"){out.push_back('*');append(out,in.quantity);}if(in.discountType){out.push_back(in.discountType<=2?',':'$');out.push_back((in.discountType==1||in.discountType==3)?'+':'-');append(out,in.discountValue);}return true;
}
bool buildDatecsSaleItem(const SaleItemPayload& in,std::vector<uint8_t>& out,std::string& error){
  if(!safeText(in.name,72)||in.taxGroup<'A'||in.taxGroup>'H'||!decimal(in.unitPrice,7,2,true)||!decimal(in.quantity,6,3,true)||in.discountType>4||(in.discountType&& !decimal(in.discountValue,7,2,true))||in.department>99||(!in.unit.empty()&&!safeText(in.unit,6))){error="DATECS_ITEM_FIELDS";return false;}
  out.clear();append(out,in.name);tab(out);append(out,std::to_string(in.taxGroup-'A'+1));tab(out);append(out,in.unitPrice);tab(out);append(out,in.quantity);tab(out);if(in.discountType)append(out,std::to_string(in.discountType));tab(out);if(in.discountType)append(out,in.discountValue);tab(out);append(out,std::to_string(in.department));tab(out);append(out,in.unit);tab(out);return true;
}
bool buildDaisyPayment(const PaymentPayload& in,std::vector<uint8_t>& out,std::string& error){
  const std::string allowed="PNCDUBE";if(allowed.find(in.daisyPaymentCode)==std::string::npos||!decimal(in.amount,8,2,true)){error="DAISY_PAYMENT_FIELDS";return false;}out.clear();tab(out);out.push_back(static_cast<uint8_t>(in.daisyPaymentCode));append(out,in.amount);return true;
}
bool buildDatecsPayment(const PaymentPayload& in,std::vector<uint8_t>& out,std::string& error){
  if(in.datecsPaidMode>5||!decimal(in.amount,7,2,true)){error="DATECS_PAYMENT_FIELDS";return false;}out.clear();append(out,std::to_string(in.datecsPaidMode));tab(out);append(out,in.amount);tab(out);return true;
}
bool buildDaisyDailyReport(bool zReport,std::vector<uint8_t>& out){out.assign(1,static_cast<uint8_t>(zReport?'0':'2'));return true;}
bool buildDatecsDailyReport(bool zReport,std::vector<uint8_t>& out){out.assign(1,static_cast<uint8_t>(zReport?'Z':'X'));tab(out);return true;}
bool buildDaisyCashMovement(const CashMovementPayload& in,std::vector<uint8_t>& out,std::string& error){
  if(!decimal(in.amount,7,2,true)){error="DAISY_CASH_FIELDS";return false;}out.clear();if(in.cashOut)out.push_back('-');append(out,in.amount);out.push_back(',');tab(out);append(out,"$EUR");return true;
}
bool buildDatecsCashMovement(const CashMovementPayload& in,std::vector<uint8_t>& out,std::string& error){
  if(!decimal(in.amount,7,2,true)){error="DATECS_CASH_FIELDS";return false;}out.clear();out.push_back(in.cashOut?'1':'0');tab(out);append(out,in.amount);tab(out);return true;
}
bool buildDatecsSubtotal(const SubtotalPayload& in,std::vector<uint8_t>& out,std::string& error){
  if(in.discountType>4||(in.discountType!=0&&!decimal(in.discountValue,7,2,true))||(in.discountType==0&&!in.discountValue.empty())){error="DATECS_SUBTOTAL_FIELDS";return false;}out.clear();out.push_back(in.print?'1':'0');tab(out);out.push_back(in.display?'1':'0');tab(out);if(in.discountType)out.push_back(static_cast<uint8_t>('0'+in.discountType));tab(out);if(in.discountType)append(out,in.discountValue);tab(out);return true;
}
bool buildDatecsLastFiscalEntry(uint8_t type,std::vector<uint8_t>& out,std::string& error){if(type>3){error="DATECS_LAST_ENTRY_TYPE";return false;}out.clear();out.push_back(static_cast<uint8_t>('0'+type));tab(out);return true;}
bool buildDatecsErrorLookup(int code,std::vector<uint8_t>& out,std::string& error){if(code>=0||code < -999999){error="DATECS_ERROR_LOOKUP_CODE";return false;}out.clear();append(out,std::to_string(code));tab(out);return true;}
bool buildDatecsDeviceIdentity(std::vector<uint8_t>& out){out.clear();out.push_back('1');tab(out);return true;}
bool buildDatecsDailyTaxation(uint8_t type,std::vector<uint8_t>& out,std::string& error){if(type>3){error="DATECS_DAILY_TAXATION_TYPE";return false;}out.clear();out.push_back(static_cast<uint8_t>('0'+type));tab(out);return true;}
bool buildDatecsDiagnosticInfo(bool withChecksum,std::vector<uint8_t>& out){out.clear();if(withChecksum){out.push_back('1');tab(out);}return true;}
bool buildDatecsItemGroupInfo(uint8_t group,std::vector<uint8_t>& out,std::string& error){if(group>99){error="DATECS_ITEM_GROUP";return false;}out.clear();if(group){append(out,std::to_string(group));tab(out);}return true;}
bool buildDatecsDepartmentInfo(uint8_t department,std::vector<uint8_t>& out,std::string& error){if(department>99){error="DATECS_DEPARTMENT";return false;}out.clear();if(department){append(out,std::to_string(department));tab(out);}return true;}
bool buildDatecsFiscalMemoryTest(bool write,std::vector<uint8_t>& out){out.clear();out.push_back(write?'1':'0');tab(out);return true;}
bool buildDatecsAdditionalDailyInfo(uint8_t type,uint8_t operatorNumber,std::vector<uint8_t>& out,std::string& error){if(type>5||operatorNumber>30){error="DATECS_ADDITIONAL_DAILY_INFO";return false;}out.clear();out.push_back(static_cast<uint8_t>('0'+type));tab(out);if(operatorNumber){append(out,std::to_string(operatorNumber));tab(out);}return true;}
bool buildDatecsOperatorInfo(uint8_t operatorNumber,std::vector<uint8_t>& out,std::string& error){if(operatorNumber<1||operatorNumber>30){error="DATECS_OPERATOR_INFO";return false;}out.clear();append(out,std::to_string(operatorNumber));tab(out);return true;}
bool buildDatecsCurrencyConversion(const CurrencyConversionPayload& in,std::vector<uint8_t>& out,std::string& error){if(in.direction>1||!decimal(in.amount,9,2,true)){error="DATECS_CURRENCY_CONVERSION";return false;}out.clear();out.push_back(static_cast<uint8_t>('0'+in.direction));tab(out);append(out,in.amount);tab(out);return true;}
bool buildDatecsFiscalMemoryRead(const FiscalMemoryReadPayload& in,std::vector<uint8_t>& out,std::string& error){if(!hexAddress(in.address)||in.byteCount<1||in.byteCount>104){error="DATECS_FISCAL_MEMORY_READ";return false;}out.clear();out.push_back('0');tab(out);append(out,in.address);tab(out);append(out,std::to_string(in.byteCount));tab(out);return true;}
bool buildDatecsDeviceInfo(uint8_t option,std::vector<uint8_t>& out,std::string& error){if(option<1||option>5){error="DATECS_DEVICE_INFO_OPTION";return false;}out.clear();out.push_back(static_cast<uint8_t>('0'+option));tab(out);return true;}
bool buildDatecsReceiptPeriodSearch(const ReceiptPeriodSearchPayload& in,std::vector<uint8_t>& out,std::string& error){if((!in.startDateTime.empty()&&(!datePrefix(in.startDateTime,true)||!safeText(in.startDateTime,24)))||(!in.endDateTime.empty()&&(!datePrefix(in.endDateTime,true)||!safeText(in.endDateTime,24)))||in.documentType>10){error="DATECS_RECEIPT_PERIOD_SEARCH";return false;}out.clear();append(out,in.startDateTime);tab(out);append(out,in.endDateTime);tab(out);append(out,std::to_string(in.documentType));tab(out);return true;}
bool buildDatecsEjDocumentSelector(const EjDocumentSelector& in,std::vector<uint8_t>& out,std::string& error){if(in.option>3||in.recordType>10||(in.documentNumber==0&&in.recordType!=0)||in.documentNumber>documentLimit(in.recordType)){error="DATECS_EJ_DOCUMENT_SELECTOR";return false;}out.clear();append(out,std::to_string(in.option));tab(out);if(in.documentNumber){append(out,std::to_string(in.documentNumber));tab(out);append(out,std::to_string(in.recordType));tab(out);}return true;}
bool buildDatecsEjCsvRange(const EjCsvRange& in,std::vector<uint8_t>& out,std::string& error){if(in.firstDocument<1||in.lastDocument<in.firstDocument||in.lastDocument>99999999){error="DATECS_EJ_CSV_RANGE";return false;}out.clear();append(out,"9");tab(out);append(out,std::to_string(in.firstDocument));tab(out);append(out,std::to_string(in.lastDocument));tab(out);return true;}
bool buildDatecsEjCsvRead(std::vector<uint8_t>& out){out.clear();append(out,"8");tab(out);return true;}
bool buildDatecsFiscalMemoryStructured(uint8_t type,uint16_t record,std::vector<uint8_t>& out,std::string& error){if(type>9||record>9999){error="DATECS_FM_STRUCTURED";return false;}out.clear();append(out,std::to_string(type));tab(out);if(record)append(out,std::to_string(record));tab(out);return true;}
bool buildDatecsModemInfo(char option,std::vector<uint8_t>& out,std::string& error){if(option!='s'&&option!='i'&&option!='M'){error="DATECS_MODEM_OPTION";return false;}out.clear();out.push_back(static_cast<uint8_t>(option));tab(out);return true;}
bool buildDatecsOpenReversal(const ReversalOpenPayload& in,std::vector<uint8_t>& out,std::string& error){if(in.operatorNumber<1||in.operatorNumber>30||!digits(in.password,8,8)||in.tillNumber<1||in.tillNumber>99999||in.reason>2||in.originalDocument<1||in.originalDocument>9999999||!documentedDateTime(in.originalDateTime)||!digits(in.fiscalMemoryNumber,1,8)||(!in.unp.empty()&&!validUNP(in.unp))||(in.invoice&&(!digits(in.originalInvoiceNumber,1,10)||!safeText(in.invoiceReason,64)))||(!in.invoice&&(!in.originalInvoiceNumber.empty()||!in.invoiceReason.empty()))){error="DATECS_REVERSAL_FIELDS";return false;}out.clear();append(out,std::to_string(in.operatorNumber));tab(out);append(out,in.password);tab(out);append(out,std::to_string(in.tillNumber));tab(out);append(out,std::to_string(in.reason));tab(out);append(out,std::to_string(in.originalDocument));tab(out);append(out,in.originalDateTime);tab(out);append(out,in.fiscalMemoryNumber);tab(out);if(in.invoice)out.push_back('I');tab(out);append(out,in.originalInvoiceNumber);tab(out);append(out,in.invoiceReason);tab(out);append(out,in.unp);tab(out);return true;}
bool buildDatecsPcConnectionMode(int printing,std::vector<uint8_t>& out,std::string& error){if(printing < -1||printing>1){error="DATECS_PC_MODE";return false;}out.clear();if(printing>=0){out.push_back(static_cast<uint8_t>('0'+printing));tab(out);}return true;}
bool buildDatecsProgrammedItem(const ProgrammedItemPayload& in,std::vector<uint8_t>& out,std::string& error){if(in.pluCode<1||in.pluCode>100000||(!in.quantity.empty()&&!decimal(in.quantity,6,3,true))||(!in.price.empty()&&!decimal(in.price,7,2,false))||in.discountType>4||(in.discountType==0&&!in.discountValue.empty())||(in.discountType!=0&&!decimal(in.discountValue,7,2,true))){error="DATECS_PROGRAMMED_ITEM";return false;}out.clear();append(out,std::to_string(in.pluCode));tab(out);append(out,in.quantity);tab(out);append(out,in.price);tab(out);if(in.discountType)append(out,std::to_string(in.discountType));tab(out);append(out,in.discountValue);tab(out);return true;}
bool buildDatecsGeneralInfo(uint8_t type,std::vector<uint8_t>& out,std::string& error){const uint8_t allowed[]={0,1,2,3,4,6,9,10,11};if(std::find(std::begin(allowed),std::end(allowed),type)==std::end(allowed)){error="DATECS_GENERAL_INFO_TYPE";return false;}out.clear();append(out,std::to_string(type));tab(out);return true;}
bool buildDatecsFiscalMemoryDateReport(const FiscalMemoryDateReportPayload& in,std::vector<uint8_t>& out,std::string& error){const auto valid=[](const std::string& v){return v.empty()||(v.size()==8&&datePrefix(v,false));};if(in.type>1||!valid(in.startDate)||!valid(in.endDate)||(!in.startDate.empty()&&!in.endDate.empty()&&(in.startDate.substr(6,2)+in.startDate.substr(3,2)+in.startDate.substr(0,2)>in.endDate.substr(6,2)+in.endDate.substr(3,2)+in.endDate.substr(0,2)))){error="DATECS_FM_DATE_REPORT";return false;}out.clear();append(out,std::to_string(in.type));tab(out);append(out,in.startDate);tab(out);append(out,in.endDate);tab(out);return true;}
bool buildDatecsFiscalMemoryNumberReport(const FiscalMemoryNumberReportPayload& in,std::vector<uint8_t>& out,std::string& error){if(in.type>1||in.firstZReport>3650||in.lastZReport>3650||(in.firstZReport&&in.lastZReport&&in.lastZReport<in.firstZReport)){error="DATECS_FM_NUMBER_REPORT";return false;}out.clear();append(out,std::to_string(in.type));tab(out);if(in.firstZReport)append(out,std::to_string(in.firstZReport));tab(out);if(in.lastZReport)append(out,std::to_string(in.lastZReport));tab(out);return true;}
bool buildDatecsOperatorReport(const OperatorReportPayload& in,std::vector<uint8_t>& out,std::string& error){if(in.firstOperator>30||in.lastOperator>30||(in.firstOperator&&in.lastOperator&&in.lastOperator<in.firstOperator)){error="DATECS_OPERATOR_REPORT";return false;}out.clear();if(in.firstOperator)append(out,std::to_string(in.firstOperator));tab(out);if(in.lastOperator)append(out,std::to_string(in.lastOperator));tab(out);out.push_back(in.clear?'1':'0');tab(out);return true;}
bool buildDatecsPluReport(const PluReportPayload& in,std::vector<uint8_t>& out,std::string& error){if(in.type>3||in.firstPlu>100000||in.lastPlu>100000||(in.firstPlu&&in.lastPlu&&in.lastPlu<in.firstPlu)){error="DATECS_PLU_REPORT";return false;}out.clear();append(out,std::to_string(in.type));tab(out);if(in.firstPlu)append(out,std::to_string(in.firstPlu));tab(out);if(in.lastPlu)append(out,std::to_string(in.lastPlu));tab(out);return true;}
bool parseDatecsResult(const std::vector<uint8_t>& raw,DatecsResult& out,std::string& error){
  const auto fields=split(raw,'\t');if(fields.empty()){error="DATECS_EMPTY_RESULT";return false;}char* end=nullptr;long code=std::strtol(fields[0].c_str(),&end,10);if(!end||*end!='\0'||code<INT_MIN||code>0){error="DATECS_ERROR_CODE";return false;}out.errorCode=static_cast<int>(code);out.fields.assign(fields.begin()+1,fields.end());return true;
}
bool parseDatecsTaxRates(const std::vector<uint8_t>& raw,TaxRatesResult& out,std::string& error){DatecsResult r;if(!parseDatecsResult(raw,r,error)||r.fields.size()!=10||!uint32Value(r.fields[0],out.firstZReport)||!datePrefix(r.fields[9],false)){error="DATECS_TAX_RATES";return false;}for(size_t i=0;i<8;i++){if(!decimal(r.fields[i+1],3,2,false)){error="DATECS_TAX_RATES";return false;}out.rates[i]=r.fields[i+1];}out.effectiveDate=r.fields[9];return true;}
bool parseDatecsSubtotal(const std::vector<uint8_t>& raw,SubtotalResult& out,std::string& error){DatecsResult r;if(!parseDatecsResult(raw,r,error)||r.fields.size()!=10||!uint32Value(r.fields[0],out.slipNumber)||!decimal(r.fields[1],7,2,false)){error="DATECS_SUBTOTAL_RESULT";return false;}out.subtotal=r.fields[1];for(size_t i=0;i<8;i++){if(!decimal(r.fields[i+2],7,2,false)){error="DATECS_SUBTOTAL_RESULT";return false;}out.taxTotals[i]=r.fields[i+2];}return true;}
bool parseDatecsDateTime(const std::vector<uint8_t>& raw,std::string& out,std::string& error){DatecsResult r;if(!parseDatecsResult(raw,r,error)||r.fields.size()!=1||!datePrefix(r.fields[0],true)||!safeText(r.fields[0],24)){error="DATECS_DATE_TIME";return false;}out=r.fields[0];return true;}
bool parseDatecsLastFiscalEntry(const std::vector<uint8_t>& raw,LastFiscalEntryResult& out,std::string& error){DatecsResult r;if(!parseDatecsResult(raw,r,error)||r.fields.size()!=10||!uint32Value(r.fields[0],out.reportNumber)||!datePrefix(r.fields[9],false)){error="DATECS_LAST_ENTRY";return false;}for(size_t i=0;i<8;i++){if(!decimal(r.fields[i+1],9,2,false)){error="DATECS_LAST_ENTRY";return false;}out.taxValues[i]=r.fields[i+1];}out.date=r.fields[9];return true;}
bool parseDatecsTaxNumber(const std::vector<uint8_t>& raw,std::string& out,std::string& error){DatecsResult r;if(!parseDatecsResult(raw,r,error)||r.fields.size()!=1||!safeText(r.fields[0],13)){error="DATECS_TAX_NUMBER";return false;}out=r.fields[0];return true;}
bool parseDatecsErrorDescription(const std::vector<uint8_t>& raw,ErrorDescriptionResult& out,std::string& error){DatecsResult r;if(!parseDatecsResult(raw,r,error)||r.fields.size()!=2||!negativeInt(r.fields[0],out.code)||!safeText(r.fields[1],160)){error="DATECS_ERROR_DESCRIPTION";return false;}out.message=r.fields[1];return true;}
bool parseDatecsCurrentReceipt(const std::vector<uint8_t>& raw,CurrentReceiptResult& out,std::string& error){DatecsResult r;if(!parseDatecsResult(raw,r,error)||r.fields.size()!=11){error="DATECS_CURRENT_RECEIPT";return false;}for(size_t i=0;i<8;i++){if(!decimal(r.fields[i],9,2,false)){error="DATECS_CURRENT_RECEIPT";return false;}out.taxTotals[i]=r.fields[i];}if((r.fields[8]!="0"&&r.fields[8]!="1")||!digits(r.fields[9],1,10)||(r.fields[10]!="0"&&r.fields[10]!="1")){error="DATECS_CURRENT_RECEIPT";return false;}out.invoice=r.fields[8]=="1";out.nextInvoiceNumber=r.fields[9];out.reversal=r.fields[10]=="1";return true;}
bool parseDatecsDeviceIdentity(const std::vector<uint8_t>& raw,DeviceIdentityResult& out,std::string& error){DatecsResult r;if(!parseDatecsResult(raw,r,error)||r.fields.size()!=7||!safeText(r.fields[0],8)||!digits(r.fields[1],8,8)||!safeText(r.fields[2],64)||!safeText(r.fields[3],64)||!safeText(r.fields[4],13)||!safeText(r.fields[5],64)||!safeText(r.fields[6],64)){error="DATECS_DEVICE_IDENTITY";return false;}out={r.fields[0],r.fields[1],r.fields[2],r.fields[3],r.fields[4],r.fields[5],r.fields[6]};return true;}
bool parseDatecsDailyTaxation(const std::vector<uint8_t>& raw,DailyTaxationResult& out,std::string& error){DatecsResult r;if(!parseDatecsResult(raw,r,error)||r.fields.size()!=9||!uint32Value(r.fields[0],out.reportNumber)||out.reportNumber<1||out.reportNumber>3650){error="DATECS_DAILY_TAXATION";return false;}for(size_t i=0;i<8;i++){if(!decimal(r.fields[i+1],9,2,false)){error="DATECS_DAILY_TAXATION";return false;}out.taxValues[i]=r.fields[i+1];}return true;}
bool parseDatecsReportsLeft(const std::vector<uint8_t>& raw,uint32_t& out,std::string& error){DatecsResult r;if(!parseDatecsResult(raw,r,error)||r.fields.size()!=1||!uint32Value(r.fields[0],out)||out<1||out>3650){error="DATECS_REPORTS_LEFT";return false;}return true;}
bool parseDatecsLastFiscalRecordDateTime(const std::vector<uint8_t>& raw,std::string& out,std::string& error){DatecsResult r;if(!parseDatecsResult(raw,r,error)||r.fields.size()!=1||!fullDateTime(r.fields[0])){error="DATECS_LAST_FISCAL_DATETIME";return false;}out=r.fields[0];return true;}
bool parseDatecsDiagnosticInfo(const std::vector<uint8_t>& raw,DiagnosticInfoResult& out,std::string& error){DatecsResult r;if(!parseDatecsResult(raw,r,error)||r.fields.size()!=8||!safeText(r.fields[0],32)||!safeText(r.fields[1],6)||!safeText(r.fields[2],16)||!safeText(r.fields[3],16)||(r.fields[4].size()!=4&&!r.fields[4].empty())||(!r.fields[4].empty()&&!safeText(r.fields[4],4))||!safeText(r.fields[5],8)||!safeText(r.fields[6],8)||!digits(r.fields[7],8,8)){error="DATECS_DIAGNOSTIC_INFO";return false;}out={r.fields[0],r.fields[1],r.fields[2],r.fields[3],r.fields[4],r.fields[5],r.fields[6],r.fields[7]};return true;}
bool parseDatecsItemGroupInfo(const std::vector<uint8_t>& raw,ItemGroupInfoResult& out,std::string& error){DatecsResult r;if(!parseDatecsResult(raw,r,error)||r.fields.size()!=3||!decimal(r.fields[0],8,3,false)||!decimal(r.fields[1],9,2,false)||!safeText(r.fields[2],32)){error="DATECS_ITEM_GROUP_INFO";return false;}out={r.fields[0],r.fields[1],r.fields[2]};return true;}
bool parseDatecsDepartmentInfo(const std::vector<uint8_t>& raw,DepartmentInfoResult& out,std::string& error){DatecsResult r;if(!parseDatecsResult(raw,r,error)||r.fields.size()!=7||!uint32Value(r.fields[0],out.taxGroup)||!decimal(r.fields[1],9,2,false)||!decimal(r.fields[2],8,3,false)||!decimal(r.fields[3],9,2,false)||!decimal(r.fields[4],8,3,false)||!decimal(r.fields[5],9,2,false)||!safeText(r.fields[6],72)){error="DATECS_DEPARTMENT_INFO";return false;}out.price=r.fields[1];out.totalSales=r.fields[2];out.totalSum=r.fields[3];out.reversalSales=r.fields[4];out.reversalSum=r.fields[5];out.name=r.fields[6];return true;}
bool parseDatecsFiscalMemoryTest(const std::vector<uint8_t>& raw,uint32_t& out,std::string& error){DatecsResult r;if(!parseDatecsResult(raw,r,error)||r.fields.size()!=1||!uint32Value(r.fields[0],out)||out>16){error="DATECS_FISCAL_MEMORY_TEST";return false;}return true;}
bool parseDatecsDailyPayments(const std::vector<uint8_t>& raw,DailyPaymentsResult& out,std::string& error){DatecsResult r;if(!parseDatecsResult(raw,r,error)||r.fields.size()!=7){error="DATECS_DAILY_PAYMENTS";return false;}for(size_t i=0;i<7;i++){if(!decimal(r.fields[i],9,2,false)){error="DATECS_DAILY_PAYMENTS";return false;}out.amounts[i]=r.fields[i];}return true;}
bool parseDatecsDailySales(const std::vector<uint8_t>& raw,DailyCountSumResult& out,std::string& error){DatecsResult r;if(!parseDatecsResult(raw,r,error)||r.fields.size()!=2||!uint32Value(r.fields[0],out.count)||out.count>65535||!decimal(r.fields[1],9,2,false)){error="DATECS_DAILY_SALES";return false;}out.sum=r.fields[1];return true;}
bool parseDatecsDailyDualCountSum(const std::vector<uint8_t>& raw,DailyDualCountSumResult& out,std::string& error){DatecsResult r;if(!parseDatecsResult(raw,r,error)||r.fields.size()!=4){error="DATECS_DAILY_DUAL_TOTALS";return false;}for(size_t i=0;i<2;i++){if(!uint32Value(r.fields[i*2],out.counts[i])||out.counts[i]>999999||!signedDecimal(r.fields[i*2+1],9,2)){error="DATECS_DAILY_DUAL_TOTALS";return false;}out.sums[i]=r.fields[i*2+1];}return true;}
bool parseDatecsDailyCashMovements(const std::vector<uint8_t>& raw,DailyCashMovementResult& out,std::string& error){DatecsResult r;if(!parseDatecsResult(raw,r,error)||r.fields.size()!=8){error="DATECS_DAILY_CASH_MOVEMENTS";return false;}for(size_t i=0;i<4;i++){if(!uint32Value(r.fields[i*2],out.counts[i])||out.counts[i]>999999||!signedDecimal(r.fields[i*2+1],9,2)){error="DATECS_DAILY_CASH_MOVEMENTS";return false;}out.sums[i]=r.fields[i*2+1];}return true;}
bool parseDatecsOperatorInfo(const std::vector<uint8_t>& raw,OperatorInfoResult& out,std::string& error){DatecsResult r;if(!parseDatecsResult(raw,r,error)||r.fields.size()!=10){error="DATECS_OPERATOR_INFO";return false;}for(size_t i=0;i<5;i++){if(!uint32Value(r.fields[i*2],out.counts[i])||out.counts[i]>65535||!signedDecimal(r.fields[i*2+1],9,2)){error="DATECS_OPERATOR_INFO";return false;}out.sums[i]=r.fields[i*2+1];}return true;}
bool parseDatecsCurrencyConversion(const std::vector<uint8_t>& raw,std::string& out,std::string& error){DatecsResult r;if(!parseDatecsResult(raw,r,error)||r.fields.size()!=1||!decimal(r.fields[0],9,2,false)){error="DATECS_CURRENCY_CONVERSION";return false;}out=r.fields[0];return true;}
bool parseDatecsFiscalMemoryRead(const std::vector<uint8_t>& raw,uint8_t expectedBytes,std::vector<uint8_t>& out,std::string& error){DatecsResult r;if(expectedBytes<1||expectedBytes>104||!parseDatecsResult(raw,r,error)||r.fields.size()!=1||r.fields[0].size()!=static_cast<size_t>(expectedBytes)*2){error="DATECS_FISCAL_MEMORY_READ";return false;}out.clear();out.reserve(expectedBytes);for(size_t i=0;i<r.fields[0].size();i+=2){int high=hexNibble(r.fields[0][i]);int low=hexNibble(r.fields[0][i+1]);if(high<0||low<0){error="DATECS_FISCAL_MEMORY_READ";out.clear();return false;}out.push_back(static_cast<uint8_t>((high<<4)|low));}return true;}
bool parseDatecsDevicePowerNetwork(const std::vector<uint8_t>& raw,DevicePowerNetworkResult& out,std::string& error){DatecsResult r;if(!parseDatecsResult(raw,r,error)||r.fields.size()<2||r.fields.size()>4||!uint32Value(r.fields[0],out.mainBatteryMv)||out.mainBatteryMv>999999||!uint32Value(r.fields[1],out.ramBatteryMv)||out.ramBatteryMv>999999){error="DATECS_DEVICE_POWER_NETWORK";return false;}out.signalAvailable=r.fields.size()>2&&!r.fields[2].empty();out.networkAvailable=r.fields.size()>3&&!r.fields[3].empty();if(out.signalAvailable&&(!uint32Value(r.fields[2],out.signalPercent)||out.signalPercent>100)){error="DATECS_DEVICE_POWER_NETWORK";return false;}if(out.networkAvailable&&(r.fields[3]!="0"&&r.fields[3]!="1")){error="DATECS_DEVICE_POWER_NETWORK";return false;}out.networkRegistered=out.networkAvailable&&r.fields[3]=="1";return true;}
bool parseDatecsLastFiscalReceiptInfo(const std::vector<uint8_t>& raw,LastFiscalReceiptInfoResult& out,std::string& error){DatecsResult r;if(!parseDatecsResult(raw,r,error)||r.fields.size()!=4||!uint32Value(r.fields[0],out.receiptNumber)||out.receiptNumber<1||out.receiptNumber>9999||!documentedDateTime(r.fields[1])||!safeText(r.fields[1],24)||!uint32Value(r.fields[2],out.zReportNumber)||out.zReportNumber<1||out.zReportNumber>3650||!documentedDateTime(r.fields[3])||!safeText(r.fields[3],24)){error="DATECS_LAST_FISCAL_RECEIPT_INFO";return false;}out.receiptDateTime=r.fields[1];out.zReportDateTime=r.fields[3];return true;}
bool parseDatecsDeviceInfoVerification(const std::vector<uint8_t>& raw,std::string& error){DatecsResult r;if(!parseDatecsResult(raw,r,error)||!r.fields.empty()){error="DATECS_DEVICE_INFO_VERIFY";return false;}return true;}
bool parseDatecsDeviceBattery(const std::vector<uint8_t>& raw,DeviceBatteryResult& out,std::string& error){DatecsResult r;if(!parseDatecsResult(raw,r,error)||r.fields.size()!=2||!uint32Value(r.fields[0],out.mainBatteryMv)||out.mainBatteryMv>999999||!uint32Value(r.fields[1],out.chargePercent)||out.chargePercent>100){error="DATECS_DEVICE_BATTERY";return false;}return true;}
bool parseDatecsReceiptPeriodSearch(const std::vector<uint8_t>& raw,uint8_t documentType,ReceiptPeriodSearchResult& out,std::string& error){DatecsResult r;if(documentType>10||!parseDatecsResult(raw,r,error)||r.fields.size()!=4||!datePrefix(r.fields[0],true)||!safeText(r.fields[0],24)||!datePrefix(r.fields[1],true)||!safeText(r.fields[1],24)||!uint64Value(r.fields[2],out.firstDocument)||!uint64Value(r.fields[3],out.lastDocument)||out.firstDocument<1||out.lastDocument<out.firstDocument){error="DATECS_RECEIPT_PERIOD_SEARCH";return false;}const uint64_t max=documentLimit(documentType);if(out.firstDocument>max||out.lastDocument>max){error="DATECS_RECEIPT_PERIOD_SEARCH";return false;}out.startDateTime=r.fields[0];out.endDateTime=r.fields[1];return true;}
bool parseDatecsEjDocumentInfo(const std::vector<uint8_t>& raw,EjDocumentInfoResult& out,std::string& error){DatecsResult r;if(!parseDatecsResult(raw,r,error)||(r.fields.size()!=5&&r.fields.size()!=6)||!uint32Value(r.fields[0],out.globalDocumentNumber)||out.globalDocumentNumber<1||out.globalDocumentNumber>9999999||!uint64Value(r.fields[1],out.recordNumber)){error="DATECS_EJ_DOCUMENT_INFO";return false;}const bool splitDate=r.fields.size()==6;const std::string dt=splitDate?r.fields[2]+" "+r.fields[3]:r.fields[2];const size_t typeIndex=splitDate?4:3,zIndex=splitDate?5:4;uint32_t type=0;if(!documentedDateTime(dt)||!safeText(dt,24)||!uint32Value(r.fields[typeIndex],type)||type>9||!uint32Value(r.fields[zIndex],out.zReportNumber)||out.zReportNumber<1||out.zReportNumber>3650||out.recordNumber<1||out.recordNumber>documentLimit(static_cast<uint8_t>(type))){error="DATECS_EJ_DOCUMENT_INFO";return false;}out.dateTime=dt;out.documentType=static_cast<uint8_t>(type);return true;}
bool parseDatecsEjTextLine(const std::vector<uint8_t>& raw,std::string& out,std::string& error){DatecsResult r;if(!parseDatecsResult(raw,r,error)||r.fields.size()>1||(r.fields.size()==1&&(!safeText(r.fields[0],64)))){error="DATECS_EJ_TEXT_LINE";return false;}out=r.fields.empty()?"":r.fields[0];return true;}
bool parseDatecsEjBase64Data(const std::vector<uint8_t>& raw,std::string& out,std::string& error){DatecsResult r;if(!parseDatecsResult(raw,r,error)||r.fields.size()!=1||!base64Data(r.fields[0])){error="DATECS_EJ_BASE64";return false;}out=r.fields[0];return true;}
bool parseDatecsEjAcknowledge(const std::vector<uint8_t>& raw,std::string& error){return parseDatecsDeviceInfoVerification(raw,error);}
bool parseDatecsEjCsvRow(const std::vector<uint8_t>& raw,EjCsvRow& out,std::string& error){DatecsResult r;if(!parseDatecsResult(raw,r,error)||r.fields.empty()||r.fields.size()>14){error="DATECS_EJ_CSV_ROW";return false;}for(const auto& field:r.fields)if(!field.empty()&&!safeText(field,128)){error="DATECS_EJ_CSV_ROW";return false;}out.columns=r.fields;return true;}
bool parseDatecsFiscalMemoryCapacity(const std::vector<uint8_t>& raw,FiscalMemoryCapacityResult& out,std::string& error){DatecsResult r;if(!parseDatecsResult(raw,r,error)||r.fields.size()!=2||!uint32Value(r.fields[0],out.nonEmpty)||!uint32Value(r.fields[1],out.maximum)||out.nonEmpty>9999||out.maximum>9999||out.nonEmpty>out.maximum){error="DATECS_FM_CAPACITY";return false;}return true;}
bool parseDatecsFiscalMemoryZRecord(const std::vector<uint8_t>& raw,FiscalMemoryZRecordResult& out,std::string& error){DatecsResult r;if(!parseDatecsResult(raw,r,error)||r.fields.size()!=23||!uint32Value(r.fields[0],out.number)||out.number<1||out.number>9999||!fiscalMemoryDateTime(r.fields[1])){error="DATECS_FM_Z_RECORD";return false;}for(size_t i=0;i<8;i++){if(!decimal(r.fields[2+i],9,2,false)||!decimal(r.fields[11+i],9,2,false)){error="DATECS_FM_Z_RECORD";return false;}out.sales[i]=r.fields[2+i];out.reversals[i]=r.fields[11+i];}if(!decimal(r.fields[10],9,2,false)||!decimal(r.fields[19],9,2,false)||r.fields[20].size()!=40||!std::all_of(r.fields[20].begin(),r.fields[20].end(),[](unsigned char c){return std::isdigit(c)||(c>='A'&&c<='F');})||!uint32Value(r.fields[21],out.lastDocument)||out.lastDocument<1||out.lastDocument>9999999||!uint32Value(r.fields[22],out.klenNumber)||out.klenNumber<1||out.klenNumber>99){error="DATECS_FM_Z_RECORD";return false;}out.dateTime=r.fields[1];out.salesTotal=r.fields[10];out.reversalTotal=r.fields[19];out.hash=r.fields[20];return true;}
bool parseDatecsFiscalMemoryValueEvent(const std::vector<uint8_t>& raw,size_t maxValue,FiscalMemoryValueEventResult& out,std::string& error){DatecsResult r;if(!parseDatecsResult(raw,r,error)||(r.fields.size()!=2&&r.fields.size()!=3)||!safeText(r.fields[0],maxValue)){error="DATECS_FM_VALUE_EVENT";return false;}const std::string dt=r.fields.size()==3?r.fields[1]+" "+r.fields[2]:r.fields[1];if(!fiscalMemoryDateTime(dt)){error="DATECS_FM_VALUE_EVENT";return false;}out.value=r.fields[0];out.dateTime=dt;return true;}
bool parseDatecsFiscalMemoryDateEvent(const std::vector<uint8_t>& raw,std::string& out,std::string& error){DatecsResult r;if(!parseDatecsResult(raw,r,error)||(r.fields.size()!=1&&r.fields.size()!=2)){error="DATECS_FM_DATE_EVENT";return false;}out=r.fields.size()==2?r.fields[0]+" "+r.fields[1]:r.fields[0];if(!fiscalMemoryDateTime(out)){error="DATECS_FM_DATE_EVENT";return false;}return true;}
bool parseDatecsFiscalMemoryVatEvent(const std::vector<uint8_t>& raw,FiscalMemoryVatEventResult& out,std::string& error){DatecsResult r;if(!parseDatecsResult(raw,r,error)||(r.fields.size()!=11&&r.fields.size()!=12)){error="DATECS_FM_VAT_EVENT";return false;}for(size_t i=0;i<8;i++){if(!decimal(r.fields[i],3,2,false)){error="DATECS_FM_VAT_EVENT";return false;}out.rates[i]=r.fields[i];}uint32_t point=0;if(!uint32Value(r.fields[8],out.zReportNumber)||out.zReportNumber>9999||!uint32Value(r.fields[9],point)||(point!=0&&point!=2)){error="DATECS_FM_VAT_EVENT";return false;}out.decimalPoint=static_cast<uint8_t>(point);out.dateTime=r.fields.size()==12?r.fields[10]+" "+r.fields[11]:r.fields[10];if(!fiscalMemoryDateTime(out.dateTime)){error="DATECS_FM_VAT_EVENT";return false;}return true;}
bool parseDatecsFiscalMemoryCounterEvent(const std::vector<uint8_t>& raw,FiscalMemoryCounterEventResult& out,std::string& error){DatecsResult r;if(!parseDatecsResult(raw,r,error)||(r.fields.size()!=2&&r.fields.size()!=3)||!uint32Value(r.fields[0],out.zReportNumber)||out.zReportNumber>9999){error="DATECS_FM_COUNTER_EVENT";return false;}out.dateTime=r.fields.size()==3?r.fields[1]+" "+r.fields[2]:r.fields[1];if(!fiscalMemoryDateTime(out.dateTime)){error="DATECS_FM_COUNTER_EVENT";return false;}return true;}
bool parseDatecsFiscalMemoryKlenEvent(const std::vector<uint8_t>& raw,FiscalMemoryKlenEventResult& out,std::string& error){DatecsResult r;if(!parseDatecsResult(raw,r,error)||r.fields.size()<3||r.fields.size()>6||!uint32Value(r.fields[0],out.openLastReceipt)||out.openLastReceipt>9999999||!uint32Value(r.fields[1],out.openLastZReport)||out.openLastZReport>9999||!fiscalMemoryDateTime(r.fields[2])){error="DATECS_FM_KLEN_EVENT";return false;}out.openedAt=r.fields[2];out.closed=r.fields.size()==6;if(!out.closed)return true;if(!uint32Value(r.fields[3],out.closeLastReceipt)||out.closeLastReceipt>9999999||!uint32Value(r.fields[4],out.closeLastZReport)||out.closeLastZReport>9999||!fiscalMemoryDateTime(r.fields[5])){error="DATECS_FM_KLEN_EVENT";return false;}out.closedAt=r.fields[5];return true;}
bool parseDatecsModemIdentifier(const std::vector<uint8_t>& raw,std::string& out,std::string& error){DatecsResult r;if(!parseDatecsResult(raw,r,error)||r.fields.size()!=1||!digits(r.fields[0],1,15)){error="DATECS_MODEM_IDENTIFIER";return false;}out=r.fields[0];return true;}
bool parseDatecsModemStatus(const std::vector<uint8_t>& raw,ModemStatusResult& out,std::string& error){DatecsResult r;if(!parseDatecsResult(raw,r,error)||r.fields.size()!=4||!uint32Value(r.fields[0],out.signalPercent)||out.signalPercent>100||!digits(r.fields[1],1,15)||!digits(r.fields[2],1,15)||!safeText(r.fields[3],64)){error="DATECS_MODEM_STATUS";return false;}out.imei=r.fields[1];out.imsi=r.fields[2];out.mobileOperator=r.fields[3];return true;}
bool parseDatecsSlipNumber(const std::vector<uint8_t>& raw,uint32_t& out,std::string& error){DatecsResult r;if(!parseDatecsResult(raw,r,error)||r.fields.size()!=1||!uint32Value(r.fields[0],out)||out<1||out>9999999){error="DATECS_SLIP_NUMBER";return false;}return true;}
bool parseDatecsAcknowledge(const std::vector<uint8_t>& raw,std::string& error){DatecsResult r;if(!parseDatecsResult(raw,r,error)||!r.fields.empty()){error="DATECS_ACKNOWLEDGE";return false;}return true;}
bool parseDatecsNapConnection(const std::vector<uint8_t>& raw,NapConnectionResult& out,std::string& error){DatecsResult r;if(!parseDatecsResult(raw,r,error)||r.fields.size()!=13||!documentedDateTime(r.fields[0])||!documentedDateTime(r.fields[1])||!uint32Value(r.fields[2],out.lastZReport)||out.lastZReport>3650||!uint32Value(r.fields[3],out.zReportWithError)||out.zReportWithError>3650||!uint32Value(r.fields[4],out.zErrorCount)||out.zErrorCount>65535||!negativeOrZeroInt(r.fields[5],out.zErrorStatus,-99)||!uint32Value(r.fields[6],out.saleDocumentWithError)||out.saleDocumentWithError>9999999||!uint32Value(r.fields[7],out.saleErrorCount)||out.saleErrorCount>65535||!negativeOrZeroInt(r.fields[8],out.saleErrorStatus,-99)||!uint32Value(r.fields[9],out.lastReceivedSaleDocument)||out.lastReceivedSaleDocument>9999999||!documentedDateTime(r.fields[10])||!uint32Value(r.fields[11],out.lastError)||!uint32Value(r.fields[12],out.remainingMinutes)||out.remainingMinutes>255){error="DATECS_NAP_CONNECTION";return false;}out.lastConnection=r.fields[0];out.nextConnection=r.fields[1];out.lastReceivedSaleDateTime=r.fields[10];return true;}
bool parseDaisyOpenReceiptResult(const std::vector<uint8_t>& raw,uint32_t& all,uint32_t& fiscal,std::string& error){
  const auto fields=split(raw,',');if(fields.size()!=2||!uint32Value(fields[0],all)||!uint32Value(fields[1],fiscal)){error="DAISY_OPEN_RESULT";return false;}return true;
}
bool parseDaisyReceiptStatus(const std::vector<uint8_t>& raw,ReceiptStatusResult& out,std::string& error){
  const auto fields=split(raw,',');if(fields.size()<3||fields[0].size()!=1||fields[0][0]<'0'||fields[0][0]>'1'||!uint32Value(fields[1],out.items)||!decimal(fields[2],10,2,false)){error="DAISY_RECEIPT_STATUS";return false;}out.openState=static_cast<uint8_t>(fields[0][0]-'0');out.receiptNumber=0;out.amount=fields[2];if(fields.size()>=5){out.paid=fields[3];}return true;
}
bool parseDatecsReceiptStatus(const std::vector<uint8_t>& raw,ReceiptStatusResult& out,std::string& error){
  DatecsResult result;if(!parseDatecsResult(raw,result,error)||result.errorCode!=0||result.fields.size()<5||!digits(result.fields[0],1,1)||!uint32Value(result.fields[1],out.receiptNumber)||!uint32Value(result.fields[2],out.items)||!decimal(result.fields[3],7,2,false)||!decimal(result.fields[4],7,2,false)){error="DATECS_RECEIPT_STATUS";return false;}out.openState=static_cast<uint8_t>(result.fields[0][0]-'0');if(out.openState>9){error="DATECS_RECEIPT_STATUS";return false;}out.amount=result.fields[3];out.paid=result.fields[4];return true;
}
}
