package integration_test

import (
 "fmt"
 "os"
 "testing"
 "fiscalisation/fiscal-backend/internal/domain"
 "fiscalisation/fiscal-backend/internal/persistence"
)
func active(t *testing.T,s *domain.Service,kind,model,serial string)map[string]any{t.Helper();d,e:=s.CreateResource("device","tenant-composite",map[string]any{"kind":kind,"vendor":"Datecs","model":model,"serial":serial,"status":"DRAFT","environment":"DEV","simulated":true});if e!=nil{t.Fatal(e)};p,e:=s.UpdateResource("device",d["id"].(string),"tenant-composite",1,map[string]any{"kind":kind,"vendor":"Datecs","model":model,"serial":serial,"status":"PENDING_SERVICE_ACTIVATION","environment":"DEV","simulated":true});if e!=nil{t.Fatal(e)};a,e:=s.UpdateResource("device",d["id"].(string),"tenant-composite",p["version"].(int64),map[string]any{"kind":kind,"vendor":"Datecs","model":model,"serial":serial,"status":"ACTIVE","environment":"DEV","simulated":true});if e!=nil{t.Fatal(e)};return a}
func TestCompositeBindingPersistsApplyAckRouteDisableAndRebind(t *testing.T){url:=os.Getenv("PG_INTEGRATION_URL");if url==""{t.Skip("PG_INTEGRATION_URL required")};store,e:=persistence.Open(url);if e!=nil{t.Fatal(e)};defer store.Close();repo,e:=domain.NewPersistentRepository(store);if e!=nil{t.Fatal(e)};s:=domain.NewService(repo,domain.NewSimulator(true));l,e:=s.CreateResource("location","tenant-composite",map[string]any{"code":"CMP","name":"Composite","address":"A","status":"ACTIVE"});if e!=nil{t.Fatal(e)};r,e:=s.CreateResource("register","tenant-composite",map[string]any{"location_id":l["id"],"code":"C01","status":"ACTIVE"});if e!=nil{t.Fatal(e)};adapter:=active(t,s,"SMART_DEVICE","EDGE_AGENT_S3","EDGE-CMP");fiscal:=active(t,s,"FISCAL_DEVICE","DP-150 MX","F-CMP");payment:=active(t,s,"PAYMENT_TERMINAL","BLUEPAD-50 PLUS","P-CMP");b,e:=s.CreateCompositeBinding(r["id"].(string),"tenant-composite","DATECS_DP150_BLUEPAD50",adapter["id"].(string),fiscal["id"].(string),payment["id"].(string),r["version"].(int64));if e!=nil{t.Fatal(e)};if _,e=s.ApplyCompositeBinding(r["id"].(string),b["binding_id"].(string),"tenant-composite",adapter["id"].(string),b["generation"].(int64));e!=nil{t.Fatal(e)};store.Close();store,e=persistence.Open(url);if e!=nil{t.Fatal(e)};repo,e=domain.NewPersistentRepository(store);if e!=nil{t.Fatal(e)};s=domain.NewService(repo,domain.NewSimulator(true));route,e:=s.GetResource("register",r["id"].(string),"tenant-composite");if e!=nil||route["fiscal_device_id"]!=fiscal["id"]||route["payment_terminal_id"]!=payment["id"]||fmt.Sprint(route["version"])!=fmt.Sprint(b["generation"]){t.Fatal("applied generation did not survive PostgreSQL restart",route,e)};list,e:=s.CompositeBindings(r["id"].(string),"tenant-composite");if e!=nil||len(list)!=1||fmt.Sprint(list[0]["applied_generation"])!=fmt.Sprint(b["generation"]){t.Fatal(list,e)};disabled,e:=s.DisableCompositeBinding(r["id"].(string),b["binding_id"].(string),"tenant-composite",list[0]["version"].(int64));if e!=nil||disabled["status"]!="REVOKED"{t.Fatal(disabled,e)};current,e:=s.GetResource("register",r["id"].(string),"tenant-composite");if e!=nil{t.Fatal(e)};if _,e=s.CreateCompositeBinding(r["id"].(string),"tenant-composite","DATECS_DP150_BLUEPAD50",adapter["id"].(string),fiscal["id"].(string),payment["id"].(string),current["version"].(int64));e!=nil{t.Fatal("rebind failed",e)}}
