package com.beeloy.fiscal.bluecash
import org.junit.Assert.*
import org.junit.Test
import java.time.Instant

class Signer:TransactionSigner{override val keyId="test";override fun sign(hash:ByteArray)=hash}
class Fiscal:DatecsFiscalPort{val calls=mutableListOf<Pair<Int,String>>();var fail=false;override fun reachable()=true;override fun execute(command:Int,payload:ByteArray):DatecsResponse{calls+=command to String(payload);if(fail)error("DATECS_EOF");return DatecsResponse(32,command,if(command==56)"0\tBON-42\t".toByteArray() else "0\t".toByteArray(),byteArrayOf())}}
class Card:DatecsPaymentPort{var calls=0;var reversals=0;var reversedOperation:String?=null;override fun reachable()=true;override fun purchaseEur(amountMinor:Long,operationId:String)=mapOf("approved" to "true","rrn" to "1").also{calls++};override fun reverse(operationId:String)=mapOf("approved" to "true").also{reversals++;reversedOperation=operationId}}
class BlueCashEngineTest{
 private fun sale()=BlueCashSale("op-1","DY000600-OP01-0000001",1,"1",24,listOf(FiscalLine("Coffee",'B',"2.65","1.000")),listOf(SalePayment("p","CARD","2.65")))
 @Test fun `card and fiscal receipt execute once in documented order`(){val f=Fiscal();val c=Card();val j=SignedMemoryJournal(Signer());val p=BlueCashCommandProcessor(f,c,j);assertEquals("FISCALIZED",p.sale(sale())["state"]);assertEquals(listOf(48,49,53,56),f.calls.map{it.first});assertEquals(1,c.calls);assertEquals("FISCALIZED",p.sale(sale())["state"]);assertEquals(1,c.calls);assertEquals(listOf("ACCEPTED","EXECUTING","FISCALIZED"),j.find("op-1").map{it.type})}
 @Test fun `ambiguous socket failure becomes unknown and is never replayed`(){val f=Fiscal().apply{fail=true};val p=BlueCashCommandProcessor(f,Card(),SignedMemoryJournal(Signer()));assertEquals("UNKNOWN",p.sale(sale())["state"]);val calls=f.calls.size;assertEquals("UNKNOWN",p.sale(sale())["state"]);assertEquals(calls,f.calls.size)}
 @Test fun `restart after executing fails closed without repeating device side effect`(){val f=Fiscal();val j=SignedMemoryJournal(Signer());j.append("op-1","ACCEPTED","state=ACCEPTED");j.append("op-1","EXECUTING","state=EXECUTING");val result=BlueCashCommandProcessor(f,Card(),j).sale(sale());assertEquals("UNKNOWN",result["state"]);assertEquals("RECOVERY_REQUIRED",result["error_code"]);assertTrue(f.calls.isEmpty())}
 @Test fun `same operation id with different accepted payload is rejected`(){val j=SignedMemoryJournal(Signer());val p=BlueCashCommandProcessor(Fiscal(),Card(),j);p.sale(sale(),"payload-a");assertThrows(IllegalArgumentException::class.java){p.sale(sale(),"payload-b")}}
 @Test fun `card reversal and Datecs storno execute once in documented order`(){val f=Fiscal();val c=Card();val j=SignedMemoryJournal(Signer());val p=BlueCashCommandProcessor(f,c,j);val d=DatecsStornoDocument(1,42,"11-08-26 12:30:45","12345678","DY000600-OP01-0000001");val cmd=BlueCashReversal("rev-1","op-1",1,"1",24,d,sale().lines,sale().payments);assertEquals("REVERSED",p.reverse(cmd)["state"]);assertEquals(listOf(43,49,53,56),f.calls.map{it.first});assertEquals("op-1",c.reversedOperation);assertEquals("REVERSED",p.reverse(cmd)["state"]);assertEquals(1,c.reversals);assertEquals(listOf("ACCEPTED","EXECUTING","REVERSED"),j.find("rev-1").map{it.type})}
 @Test fun `retention removes only business acknowledged old records and keeps anchor`(){var now=Instant.parse("2026-01-01T00:00:00Z");val j=SignedMemoryJournal(Signer()){now};j.append("op","ACCEPTED","state=ACCEPTED");val anchor=j.append("op","FISCALIZED","state=FISCALIZED");now=Instant.parse("2026-05-01T00:00:00Z");assertEquals(0,j.purgeBefore(now.minusSeconds(90L*86400)));val transportHash="a".repeat(64);j.acknowledge(anchor.sequence,transportHash,"ack");assertEquals(transportHash,j.checkpoint().second);assertEquals(1,j.purgeBefore(now.minusSeconds(90L*86400)));assertEquals(listOf(anchor.sequence),j.find("op").map{it.sequence})}
}
