package com.beeloy.fiscal.bluecash
import org.junit.Assert.*
import org.junit.Test

class BlueCashComplianceIntentTest {
 private fun intent(id:String,action:String,version:Long,line:Map<String,Any?>?=null,payment:Map<String,Any?>?=null)=linkedMapOf<String,Any?>("intent_id" to id,"action" to action,"client_sale_surrogate_id" to "sale-1","operator_code" to "A001","app_instance_id" to "app-1","expected_version" to version).apply{if(line!=null)put("line",line);if(payment!=null)put("payment",payment)}
 private val line=mapOf<String,Any?>("line_id" to "line-1","name" to "Coffee","quantity" to "1.000","unit_price" to "2.65","tax_group" to "B")
 @Test fun `offline aggregate fiscalizes once and replays stored result`() {val fiscal=Fiscal();val card=Card();val processor=BlueCashCommandProcessor(fiscal,card,SignedMemoryJournal(Signer()));val executor=BlueCashComplianceIntentExecutor(MemoryBleLocalSaleStore(),RangeBleUnpAllocator("DY000600",1,10),processor,1,"1",24);assertEquals("OPEN",executor.execute(intent("open","OPEN_WITH_LINE",0,line))["state"]);val pay=intent("pay","PAYMENT",1,payment=mapOf("payment_id" to "p1","type" to "CARD","amount" to "2.65"));assertEquals("FISCALIZED",executor.execute(pay)["state"]);assertEquals(1,card.calls);assertEquals("FISCALIZED",executor.execute(pay)["state"]);assertEquals(1,card.calls);assertEquals(listOf(48,49,53,56),fiscal.calls.map{it.first})}
 @Test fun `version conflict and changed duplicate fail closed`() {val executor=BlueCashComplianceIntentExecutor(MemoryBleLocalSaleStore(),RangeBleUnpAllocator("D",1,2),BlueCashCommandProcessor(Fiscal(),Card(),SignedMemoryJournal(Signer())),1,"1",1);executor.execute(intent("open","OPEN_WITH_LINE",0,line));assertThrows(IllegalArgumentException::class.java){executor.execute(intent("add","ADD_LINE",0,line))};assertThrows(IllegalArgumentException::class.java){executor.execute(intent("open","OPEN_WITH_LINE",0,line+mapOf("name" to "Tea")))}}
 @Test fun `BLE reverse invokes card reversal and command 43 once`(){val fiscal=Fiscal();val card=Card();val executor=BlueCashComplianceIntentExecutor(MemoryBleLocalSaleStore(),RangeBleUnpAllocator("DY000600",1,10),BlueCashCommandProcessor(fiscal,card,SignedMemoryJournal(Signer())),1,"1",24);executor.execute(intent("open","OPEN_WITH_LINE",0,line));executor.execute(intent("pay","PAYMENT",1,payment=mapOf("payment_id" to "p1","type" to "CARD","amount" to "2.65")));val reverse=intent("reverse","REVERSE",2)+mapOf<String,Any?>("reason_code" to "CUSTOMER_RETURN","original_document" to mapOf("document_number" to 42L,"document_datetime" to "11-08-26 12:30:45","fiscal_memory_number" to "12345678"));assertEquals("FISCALIZED",executor.execute(reverse)["state"]);assertEquals(listOf(48,49,53,56,43,49,53,56),fiscal.calls.map{it.first});assertEquals("pay",card.reversedOperation);assertEquals("FISCALIZED",executor.execute(reverse)["state"]);assertEquals(1,card.reversals)}
}
