// Code generated by scripts/generate_response_contracts.rb; DO NOT EDIT.
package api

import (
	"encoding/json"
	"errors"
	"fmt"
	"math"
	"net/http"
	"net/url"
	"reflect"
	"regexp"
	"strconv"
	"strings"
	"time"
	"unicode/utf8"
)

type generatedRequestParameter struct {
	Name     string         `json:"name"`
	In       string         `json:"in"`
	Required bool           `json:"required"`
	Schema   map[string]any `json:"schema"`
}

func validateGeneratedRequestParameters(raw, template, actual string, query url.Values, headers http.Header) error {
	var parameters []generatedRequestParameter
	if err := json.Unmarshal([]byte(raw), &parameters); err != nil {
		return fmt.Errorf("invalid generated parameters: %w", err)
	}
	pathValues, err := requestPathValues(template, actual)
	if err != nil {
		return err
	}
	for _, parameter := range parameters {
		values := []string{}
		switch parameter.In {
		case "path":
			if value, ok := pathValues[parameter.Name]; ok {
				values = []string{value}
			}
		case "query":
			values = query[parameter.Name]
		case "header":
			values = headers.Values(parameter.Name)
		default:
			continue
		}
		if len(values) == 0 || (len(values) == 1 && values[0] == "") {
			if parameter.Required {
				return fmt.Errorf("%s parameter %s is required", parameter.In, parameter.Name)
			}
			continue
		}
		value, conversionErr := requestParameterValue(parameter.Schema, values)
		if conversionErr != nil {
			return fmt.Errorf("%s parameter %s: %w", parameter.In, parameter.Name, conversionErr)
		}
		if err := validateSchemaNode(parameter.Schema, value, "$parameter."+parameter.Name); err != nil {
			return err
		}
	}
	return nil
}

func requestPathValues(template, actual string) (map[string]string, error) {
	templateParts, actualParts := strings.Split(strings.Trim(template, "/"), "/"), strings.Split(strings.Trim(actual, "/"), "/")
	if len(templateParts) != len(actualParts) {
		return nil, errors.New("request path does not match template")
	}
	out := map[string]string{}
	for index, part := range templateParts {
		if strings.HasPrefix(part, "{") && strings.HasSuffix(part, "}") {
			out[strings.TrimSuffix(strings.TrimPrefix(part, "{"), "}")] = actualParts[index]
		}
	}
	return out, nil
}

func requestParameterValue(schema map[string]any, values []string) (any, error) {
	rawType := schema["type"]
	if rawType == "array" {
		itemSchema, _ := schema["items"].(map[string]any)
		out := make([]any, 0, len(values))
		for _, value := range values {
			converted, err := requestParameterValue(itemSchema, []string{value})
			if err != nil {
				return nil, err
			}
			out = append(out, converted)
		}
		return out, nil
	}
	value := values[len(values)-1]
	switch rawType {
	case "integer":
		number, err := strconv.ParseInt(value, 10, 64)
		if err != nil {
			return nil, errors.New("invalid integer")
		}
		return float64(number), nil
	case "number":
		number, err := strconv.ParseFloat(value, 64)
		if err != nil {
			return nil, errors.New("invalid number")
		}
		return number, nil
	case "boolean":
		boolean, err := strconv.ParseBool(value)
		if err != nil {
			return nil, errors.New("invalid boolean")
		}
		return boolean, nil
	default:
		return value, nil
	}
}

func validateResponseSchema(raw string, value any) error {
	if raw == "" {
		return errors.New("missing response schema")
	}
	var schema map[string]any
	if err := json.Unmarshal([]byte(raw), &schema); err != nil {
		return fmt.Errorf("invalid generated schema: %w", err)
	}
	return validateSchemaNode(schema, value, "$")
}

func responseSchemaIsBinary(raw string) bool {
	var schema map[string]any
	return json.Unmarshal([]byte(raw), &schema) == nil && schema["type"] == "string" && schema["format"] == "binary"
}

func validateSchemaNode(schema map[string]any, value any, path string) error {
	if constant, ok := schema["const"]; ok && !reflect.DeepEqual(constant, value) {
		return fmt.Errorf("%s: const mismatch", path)
	}
	if values, ok := schema["enum"].([]any); ok {
		matched := false
		for _, candidate := range values {
			matched = matched || reflect.DeepEqual(candidate, value)
		}
		if !matched {
			return fmt.Errorf("%s: enum mismatch", path)
		}
	}
	if branches, ok := schema["allOf"].([]any); ok {
		for _, rawBranch := range branches {
			branch, valid := rawBranch.(map[string]any)
			if !valid {
				return fmt.Errorf("%s: invalid allOf", path)
			}
			if err := validateSchemaNode(branch, value, path); err != nil {
				return err
			}
		}
	}
	if branches, ok := schema["oneOf"].([]any); ok {
		matches := 0
		for _, rawBranch := range branches {
			if branch, valid := rawBranch.(map[string]any); valid && validateSchemaNode(branch, value, path) == nil {
				matches++
			}
		}
		if matches != 1 {
			return fmt.Errorf("%s: oneOf matched %d branches", path, matches)
		}
	}
	if rawType, ok := schema["type"]; ok && !schemaTypeMatches(rawType, value) {
		return fmt.Errorf("%s: type mismatch", path)
	}
	switch typed := value.(type) {
	case map[string]any:
		if required, ok := schema["required"].([]any); ok {
			for _, rawName := range required {
				name, valid := rawName.(string)
				if !valid {
					return fmt.Errorf("%s: invalid required", path)
				}
				if _, present := typed[name]; !present {
					return fmt.Errorf("%s.%s: required", path, name)
				}
			}
		}
		properties, _ := schema["properties"].(map[string]any)
		for name, child := range typed {
			if rawChild, documented := properties[name]; documented {
				childSchema, valid := rawChild.(map[string]any)
				if !valid {
					return fmt.Errorf("%s.%s: invalid schema", path, name)
				}
				if err := validateSchemaNode(childSchema, child, path+"."+name); err != nil {
					return err
				}
				continue
			}
			switch additional := schema["additionalProperties"].(type) {
			case bool:
				if !additional {
					return fmt.Errorf("%s.%s: additional property", path, name)
				}
			case map[string]any:
				if err := validateSchemaNode(additional, child, path+"."+name); err != nil {
					return err
				}
			}
		}
	case []any:
		if minimum, ok := numeric(schema["minItems"]); ok && float64(len(typed)) < minimum {
			return fmt.Errorf("%s: too few items", path)
		}
		if maximum, ok := numeric(schema["maxItems"]); ok && float64(len(typed)) > maximum {
			return fmt.Errorf("%s: too many items", path)
		}
		if unique, _ := schema["uniqueItems"].(bool); unique {
			seen := map[string]bool{}
			for _, item := range typed {
				encoded, _ := json.Marshal(item)
				key := string(encoded)
				if seen[key] {
					return fmt.Errorf("%s: duplicate item", path)
				}
				seen[key] = true
			}
		}
		if itemSchema, ok := schema["items"].(map[string]any); ok {
			for index, item := range typed {
				if err := validateSchemaNode(itemSchema, item, fmt.Sprintf("%s[%d]", path, index)); err != nil {
					return err
				}
			}
		}
	case string:
		length := float64(utf8.RuneCountInString(typed))
		if minimum, ok := numeric(schema["minLength"]); ok && length < minimum {
			return fmt.Errorf("%s: string too short", path)
		}
		if maximum, ok := numeric(schema["maxLength"]); ok && length > maximum {
			return fmt.Errorf("%s: string too long", path)
		}
		if pattern, ok := schema["pattern"].(string); ok {
			compiled, err := regexp.Compile(pattern)
			if err != nil || !compiled.MatchString(typed) {
				return fmt.Errorf("%s: pattern mismatch", path)
			}
		}
		if format, ok := schema["format"].(string); ok {
			if err := validateStringFormat(format, typed); err != nil {
				return fmt.Errorf("%s: %w", path, err)
			}
		}
	case float64:
		if minimum, ok := numeric(schema["minimum"]); ok && typed < minimum {
			return fmt.Errorf("%s: below minimum", path)
		}
		if maximum, ok := numeric(schema["maximum"]); ok && typed > maximum {
			return fmt.Errorf("%s: above maximum", path)
		}
	}
	return nil
}

func schemaTypeMatches(raw any, value any) bool {
	if alternatives, ok := raw.([]any); ok {
		for _, alternative := range alternatives {
			if schemaTypeMatches(alternative, value) {
				return true
			}
		}
		return false
	}
	typeName, ok := raw.(string)
	if !ok {
		return false
	}
	switch typeName {
	case "null":
		return value == nil
	case "object":
		_, ok = value.(map[string]any)
		return ok
	case "array":
		_, ok = value.([]any)
		return ok
	case "string":
		_, ok = value.(string)
		return ok
	case "boolean":
		_, ok = value.(bool)
		return ok
	case "number":
		_, ok = value.(float64)
		return ok
	case "integer":
		number, valid := value.(float64)
		return valid && number == math.Trunc(number)
	}
	return false
}
func numeric(value any) (float64, bool) { number, ok := value.(float64); return number, ok }
func validateStringFormat(format, value string) error {
	switch format {
	case "uuid":
		if !regexp.MustCompile(`^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$`).MatchString(value) {
			return errors.New("invalid uuid")
		}
	case "date-time":
		if _, err := time.Parse(time.RFC3339Nano, value); err != nil {
			return errors.New("invalid date-time")
		}
	case "uri":
		parsed, err := url.Parse(value)
		if err != nil || parsed.Scheme == "" {
			return errors.New("invalid uri")
		}
	case "binary":
		return nil
	default:
		if strings.TrimSpace(format) == "" {
			return errors.New("empty format")
		}
	}
	return nil
}
