package com.beeloy.fiscal.bluecash

import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
import java.nio.ByteOrder

/** Strict deterministic CBOR subset used by BeeFiscal BLE v1 contracts. */
object BlueCashCanonicalCbor {
 fun encode(value:Any?):ByteArray {val out=ByteArrayOutputStream();write(out,value);return out.toByteArray()}
 fun decode(raw:ByteArray):Any? {val d=Decoder(raw);val value=d.read();require(d.done){"CBOR_TRAILING_DATA"};return value}
 @Suppress("UNCHECKED_CAST") fun decodeMap(raw:ByteArray)=decode(raw) as? Map<String,Any?>?:error("CBOR_MAP_REQUIRED")
 private fun write(out:ByteArrayOutputStream,value:Any?){when(value){null->out.write(0xf6);is Boolean->out.write(if(value)0xf5 else 0xf4);is ByteArray->{head(out,2,value.size.toLong());out.write(value)};is String->{val b=value.toByteArray(Charsets.UTF_8);head(out,3,b.size.toLong());out.write(b)};is Byte,is Short,is Int,is Long->{val n=(value as Number).toLong();if(n>=0)head(out,0,n)else head(out,1,-1-n)};is List<*>->{head(out,4,value.size.toLong());value.forEach{write(out,it)}};is Map<*,*>->{val entries=value.entries.map{require(it.key is String){"CBOR_STRING_KEY_REQUIRED"};val key=encode(it.key);Triple(key,it.key as String,it.value)}.sortedWith{a,b->if(a.first.size!=b.first.size)a.first.size-b.first.size else compareBytes(a.first,b.first)};head(out,5,entries.size.toLong());entries.forEach{out.write(it.first);write(out,it.third)}};else->error("CBOR_TYPE_UNSUPPORTED")}}
 private fun compareBytes(a:ByteArray,b:ByteArray):Int{for(i in a.indices){val d=(a[i].toInt()and 255)-(b[i].toInt()and 255);if(d!=0)return d};return 0}
 private fun head(out:ByteArrayOutputStream,major:Int,n:Long){require(n>=0){"CBOR_LENGTH"};when{n<24->out.write((major shl 5)or n.toInt());n<=255->{out.write((major shl 5)or 24);out.write(n.toInt())};n<=65535->{out.write((major shl 5)or 25);out.write((n ushr 8).toInt());out.write(n.toInt())};n<=0xffffffffL->{out.write((major shl 5)or 26);out.write(ByteBuffer.allocate(4).order(ByteOrder.BIG_ENDIAN).putInt(n.toInt()).array())};else->{out.write((major shl 5)or 27);out.write(ByteBuffer.allocate(8).order(ByteOrder.BIG_ENDIAN).putLong(n).array())}}}
 private class Decoder(private val raw:ByteArray){private var p=0;val done get()=p==raw.size;fun read():Any?{require(p<raw.size){"CBOR_EOF"};val first=u8();val major=first ushr 5;val ai=first and 31;require(ai!=31){"CBOR_INDEFINITE_FORBIDDEN"};return when(major){0->length(ai);1->-1L-length(ai);2->{val n=size(length(ai));bytes(n)};3->{val n=size(length(ai));bytes(n).toString(Charsets.UTF_8)};4->List(size(length(ai))){read()};5->{val result=linkedMapOf<String,Any?>();repeat(size(length(ai))){val key=read() as? String?:error("CBOR_STRING_KEY_REQUIRED");require(!result.containsKey(key)){"CBOR_DUPLICATE_KEY"};result[key]=read()};result};6->error("CBOR_TAG_FORBIDDEN");7->when(ai){20->false;21->true;22->null;else->error("CBOR_SIMPLE_FORBIDDEN")};else->error("CBOR_INVALID")}}
 private fun length(ai:Int):Long=when{ai<24->ai.toLong();ai==24->u8().toLong().also{require(it>=24){"CBOR_NON_CANONICAL"}};ai==25->u16().toLong().also{require(it>255){"CBOR_NON_CANONICAL"}};ai==26->u32().also{require(it>65535){"CBOR_NON_CANONICAL"}};ai==27->u64().also{require(it>0xffffffffL){"CBOR_NON_CANONICAL"}};else->error("CBOR_RESERVED")}
 private fun size(n:Long)=n.also{require(it<=1_048_576){"CBOR_SIZE_LIMIT"}}.toInt();private fun bytes(n:Int)=raw.copyOfRange(p,p+n).also{require(p+n<=raw.size){"CBOR_EOF"};p+=n};private fun u8()=(raw[p++].toInt()and 255);private fun u16()=(u8()shl 8)or u8();private fun u32()=((u8().toLong()shl 24)or(u8().toLong()shl 16)or(u8().toLong()shl 8)or u8().toLong());private fun u64():Long{var v=0L;repeat(8){v=(v shl 8)or u8().toLong()};require(v>=0){"CBOR_INTEGER_RANGE"};return v}}
}
