[platformio]
default_envs = edge-agent-s3-idf
src_dir = main

[env:edge-agent-s3-idf]
platform = espressif32@6.10.0
board = esp32-s3-devkitc-1
framework = espidf
monitor_speed = 115200
board_upload.flash_size = 8MB
board_build.flash_size = 8MB
board_build.partitions = partitions_8mb.csv
build_flags =
    -std=gnu++17
    -DEDGE_SD_CLK=39
    -DEDGE_SD_CMD=38
    -DEDGE_SD_D0=40
board_build.sdkconfig = sdkconfig.defaults
