#include "durable_storage.h"
#include "driver/sdmmc_host.h"
#include "esp_vfs_fat.h"
#include "sdmmc_cmd.h"
#include "sqlite3.h"
#include "cJSON.h"
#include "mbedtls/sha256.h"
#include <cstring>
#include <sys/stat.h>

namespace beefiscal::idf {namespace{
constexpr const char*kSchema=R"sql(
PRAGMA journal_mode=DELETE;PRAGMA synchronous=FULL;PRAGMA foreign_keys=ON;
CREATE TABLE IF NOT EXISTS schema_version(version INTEGER PRIMARY KEY,applied_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS operations(
 operation_id TEXT PRIMARY KEY,payload_digest TEXT NOT NULL,first_transport TEXT NOT NULL,
 route_snapshot TEXT NOT NULL,state TEXT NOT NULL DEFAULT 'RESERVED',result_payload TEXT,
 created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL,
 CHECK(length(operation_id) BETWEEN 1 AND 128),CHECK(length(payload_digest)=64));
CREATE TABLE IF NOT EXISTS receipts(
 receipt_id TEXT PRIMARY KEY,operation_id TEXT NOT NULL REFERENCES operations(operation_id),
 state TEXT NOT NULL,canonical_payload TEXT NOT NULL,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS payments(
 payment_id TEXT PRIMARY KEY,operation_id TEXT NOT NULL REFERENCES operations(operation_id),
 receipt_id TEXT REFERENCES receipts(receipt_id),state TEXT NOT NULL,amount_minor INTEGER NOT NULL,
 terminal_reference TEXT,rrn TEXT,auth_code TEXT,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS event_outbox(
 sequence INTEGER PRIMARY KEY AUTOINCREMENT,event_id TEXT NOT NULL UNIQUE,
 operation_id TEXT NOT NULL REFERENCES operations(operation_id),kind TEXT NOT NULL,
 payload TEXT NOT NULL,payload_digest TEXT NOT NULL,created_at INTEGER NOT NULL,
 attempt_count INTEGER NOT NULL DEFAULT 0,last_attempt_at INTEGER,last_error TEXT,
 acknowledged_at INTEGER,ack_id TEXT,CHECK(length(payload_digest)=64));
CREATE INDEX IF NOT EXISTS idx_event_pending ON event_outbox(acknowledged_at,sequence);
CREATE INDEX IF NOT EXISTS idx_event_retention ON event_outbox(acknowledged_at,created_at);
CREATE TABLE IF NOT EXISTS sync_cursor(singleton INTEGER PRIMARY KEY CHECK(singleton=1),
 acknowledged_sequence INTEGER NOT NULL DEFAULT 0,ack_id TEXT,committed_event_hash TEXT,
 updated_at INTEGER NOT NULL DEFAULT 0);
INSERT OR IGNORE INTO sync_cursor(singleton)VALUES(1);
CREATE TABLE IF NOT EXISTS local_sales(
 surrogate_id TEXT PRIMARY KEY,version INTEGER NOT NULL,state TEXT NOT NULL,
 payload TEXT NOT NULL,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS authority_state(singleton INTEGER PRIMARY KEY CHECK(singleton=1),
 prefix TEXT NOT NULL,range_start INTEGER NOT NULL,range_end INTEGER NOT NULL,
 next_unp INTEGER NOT NULL,next_operation INTEGER NOT NULL,generation INTEGER NOT NULL,
 CHECK(range_start>0),CHECK(range_end>=range_start),CHECK(next_unp>=range_start));
INSERT OR IGNORE INTO schema_version(version,applied_at)VALUES(3,CAST(strftime('%s','now')AS INTEGER));
)sql";
struct Statement{sqlite3_stmt*v{};~Statement(){if(v)sqlite3_finalize(v);}};
esp_err_t exec(sqlite3*db,const char*sql){char*message=nullptr;int rc=sqlite3_exec(db,sql,nullptr,nullptr,&message);if(message)sqlite3_free(message);return rc==SQLITE_OK?ESP_OK:ESP_FAIL;}
}
struct DurableStorage::Impl{sqlite3*db{};bool mounted{};std::string mount;sdmmc_card_t*card{};};
DurableStorage::DurableStorage():impl_(new Impl){}DurableStorage::~DurableStorage(){close();delete impl_;}
esp_err_t DurableStorage::open_database_for_test(const char*path){if(!path||!*path||impl_->db)return ESP_ERR_INVALID_ARG;if(sqlite3_initialize()!=SQLITE_OK)return ESP_FAIL;if(sqlite3_open_v2(path,&impl_->db,SQLITE_OPEN_READWRITE|SQLITE_OPEN_CREATE|SQLITE_OPEN_FULLMUTEX,nullptr)!=SQLITE_OK){close();return ESP_FAIL;}sqlite3_busy_timeout(impl_->db,5000);if(exec(impl_->db,"BEGIN IMMEDIATE;")!=ESP_OK||exec(impl_->db,kSchema)!=ESP_OK||exec(impl_->db,"COMMIT;")!=ESP_OK){exec(impl_->db,"ROLLBACK;");close();return ESP_FAIL;}/* Idempotent forward migration from schema v3 deployed before hash-bound ACKs. */char*message=nullptr;const int migration=sqlite3_exec(impl_->db,"ALTER TABLE sync_cursor ADD COLUMN committed_event_hash TEXT",nullptr,nullptr,&message);if(message)sqlite3_free(message);if(migration!=SQLITE_OK){/* duplicate column is the expected steady state */}return ESP_OK;}
esp_err_t DurableStorage::open(const StorageConfig&c){if(!c.mount_point||!c.database_relative_path||c.database_relative_path[0]!='/'||impl_->db)return ESP_ERR_INVALID_ARG;sdmmc_host_t host=SDMMC_HOST_DEFAULT();sdmmc_slot_config_t slot=SDMMC_SLOT_CONFIG_DEFAULT();slot.width=c.one_bit?1:4;if(c.clk_pin>=0&&c.cmd_pin>=0&&c.d0_pin>=0){slot.clk=(gpio_num_t)c.clk_pin;slot.cmd=(gpio_num_t)c.cmd_pin;slot.d0=(gpio_num_t)c.d0_pin;}esp_vfs_fat_sdmmc_mount_config_t mount{.format_if_mount_failed=false,.max_files=8,.allocation_unit_size=16*1024,.disk_status_check_enable=true,.use_one_fat=false};esp_err_t e=esp_vfs_fat_sdmmc_mount(c.mount_point,&host,&slot,&mount,&impl_->card);if(e!=ESP_OK)return e;impl_->mounted=true;impl_->mount=c.mount_point;std::string path=impl_->mount+c.database_relative_path;auto slash=path.rfind('/');if(slash!=std::string::npos&&mkdir(path.substr(0,slash).c_str(),0755)!=0){struct stat st{};if(stat(path.substr(0,slash).c_str(),&st)!=0){close();return ESP_FAIL;}}return open_database_for_test(path.c_str());}
void DurableStorage::close(){if(impl_->db){sqlite3_close_v2(impl_->db);impl_->db=nullptr;}sqlite3_shutdown();if(impl_->mounted){esp_vfs_fat_sdcard_unmount(impl_->mount.c_str(),impl_->card);impl_->mounted=false;impl_->card=nullptr;}impl_->mount.clear();}
bool DurableStorage::ready()const{return impl_->db!=nullptr;}
bool DurableStorage::can_accept_operation(int64_t reserve_bytes)const{
  if(!ready()||reserve_bytes<65536)return false;
  // ESP-IDF/newlib does not expose statvfs.  The VFS FAT component provides
  // the authoritative free-space query for the mounted SD volume instead.
  // Host-only SQLite tests have no mounted card, so database readiness is the
  // storage admission signal there.
  if(!impl_->mounted)return true;
  uint64_t total_bytes=0,free_bytes=0;
  if(esp_vfs_fat_info(impl_->mount.c_str(),&total_bytes,&free_bytes)!=ESP_OK)return false;
  return free_bytes>=(size_t)reserve_bytes;
}
ReservationResult DurableStorage::reserve(const char*id,const char*digest,const char*transport,const char*route,int64_t now){
  if(!ready()||!id||!*id||!digest||strlen(digest)!=64||!transport||!*transport||!route||!*route||now<=0)return{ReservationStatus::Invalid,{}};
  if(exec(impl_->db,"BEGIN IMMEDIATE;")!=ESP_OK)return{ReservationStatus::StorageFailure,{}};
  Statement q;
  if(sqlite3_prepare_v2(impl_->db,"SELECT payload_digest,state,result_payload FROM operations WHERE operation_id=?",-1,&q.v,nullptr)!=SQLITE_OK){exec(impl_->db,"ROLLBACK;");return{ReservationStatus::StorageFailure,{}};}
  sqlite3_bind_text(q.v,1,id,-1,SQLITE_TRANSIENT);
  int rc=sqlite3_step(q.v);
  if(rc==SQLITE_ROW){std::string prior=(const char*)sqlite3_column_text(q.v,0),result;const auto*r=sqlite3_column_text(q.v,2);if(r)result=(const char*)r;exec(impl_->db,"COMMIT;");return{prior==digest?ReservationStatus::Duplicate:ReservationStatus::PayloadConflict,result};}
  if(rc!=SQLITE_DONE){exec(impl_->db,"ROLLBACK;");return{ReservationStatus::StorageFailure,{}};}
  Statement i;
  if(sqlite3_prepare_v2(impl_->db,"INSERT INTO operations(operation_id,payload_digest,first_transport,route_snapshot,created_at,updated_at)VALUES(?,?,?,?,?,?)",-1,&i.v,nullptr)!=SQLITE_OK){exec(impl_->db,"ROLLBACK;");return{ReservationStatus::StorageFailure,{}};}
  sqlite3_bind_text(i.v,1,id,-1,SQLITE_TRANSIENT);sqlite3_bind_text(i.v,2,digest,-1,SQLITE_TRANSIENT);sqlite3_bind_text(i.v,3,transport,-1,SQLITE_TRANSIENT);sqlite3_bind_text(i.v,4,route,-1,SQLITE_TRANSIENT);sqlite3_bind_int64(i.v,5,now);sqlite3_bind_int64(i.v,6,now);rc=sqlite3_step(i.v);
  if(rc!=SQLITE_DONE||exec(impl_->db,"COMMIT;")!=ESP_OK){exec(impl_->db,"ROLLBACK;");return{ReservationStatus::StorageFailure,{}};}
  return{ReservationStatus::New,{}};
}
ReservationResult DurableStorage::reserve_with_received_event(const char*id,const char*digest,const char*transport,const char*route,const char*event_id,const char*event_payload,int64_t now){
  if(!ready()||!id||!*id||!digest||strlen(digest)!=64||!transport||!*transport||!route||!*route||!event_id||!*event_id||!event_payload||now<=0)return{ReservationStatus::Invalid,{}};
  if(exec(impl_->db,"BEGIN IMMEDIATE;")!=ESP_OK)return{ReservationStatus::StorageFailure,{}};
  Statement q;
  if(sqlite3_prepare_v2(impl_->db,"SELECT payload_digest,result_payload FROM operations WHERE operation_id=?",-1,&q.v,nullptr)!=SQLITE_OK){exec(impl_->db,"ROLLBACK;");return{ReservationStatus::StorageFailure,{}};}
  sqlite3_bind_text(q.v,1,id,-1,SQLITE_TRANSIENT);int rc=sqlite3_step(q.v);
  if(rc==SQLITE_ROW){std::string prior=(const char*)sqlite3_column_text(q.v,0),result;const auto*r=sqlite3_column_text(q.v,1);if(r)result=(const char*)r;exec(impl_->db,"COMMIT;");return{prior==digest?ReservationStatus::Duplicate:ReservationStatus::PayloadConflict,result};}
  if(rc!=SQLITE_DONE){exec(impl_->db,"ROLLBACK;");return{ReservationStatus::StorageFailure,{}};}
  Statement operation,event;
  if(sqlite3_prepare_v2(impl_->db,"INSERT INTO operations(operation_id,payload_digest,first_transport,route_snapshot,created_at,updated_at)VALUES(?,?,?,?,?,?)",-1,&operation.v,nullptr)!=SQLITE_OK||sqlite3_prepare_v2(impl_->db,"INSERT INTO event_outbox(event_id,operation_id,kind,payload,payload_digest,created_at)VALUES(?,?,'COMMAND_RECEIVED',?,?,?)",-1,&event.v,nullptr)!=SQLITE_OK){exec(impl_->db,"ROLLBACK;");return{ReservationStatus::StorageFailure,{}};}
  sqlite3_bind_text(operation.v,1,id,-1,SQLITE_TRANSIENT);sqlite3_bind_text(operation.v,2,digest,-1,SQLITE_TRANSIENT);sqlite3_bind_text(operation.v,3,transport,-1,SQLITE_TRANSIENT);sqlite3_bind_text(operation.v,4,route,-1,SQLITE_TRANSIENT);sqlite3_bind_int64(operation.v,5,now);sqlite3_bind_int64(operation.v,6,now);
  sqlite3_bind_text(event.v,1,event_id,-1,SQLITE_TRANSIENT);sqlite3_bind_text(event.v,2,id,-1,SQLITE_TRANSIENT);sqlite3_bind_text(event.v,3,event_payload,-1,SQLITE_TRANSIENT);sqlite3_bind_text(event.v,4,digest,-1,SQLITE_TRANSIENT);sqlite3_bind_int64(event.v,5,now);
  if(sqlite3_step(operation.v)!=SQLITE_DONE||sqlite3_step(event.v)!=SQLITE_DONE||exec(impl_->db,"COMMIT;")!=ESP_OK){exec(impl_->db,"ROLLBACK;");return{ReservationStatus::StorageFailure,{}};}
  return{ReservationStatus::New,{}};
}
AtomicReservationResult DurableStorage::reserve_command(const char*id,const char*digest,const char*transport,const char*route,const char*event_id,const char*receipt_id,const char*canonical,const std::vector<InitialPayment>&payments,int64_t now,const std::function<std::string(const AuthorityReservation&)>&make_event){
  AtomicReservationResult failure{ReservationStatus::Invalid,{},{}};
  if(!ready()||!id||!*id||!digest||strlen(digest)!=64||!transport||!*transport||!route||!*route||!event_id||!*event_id||!receipt_id||!*receipt_id||!canonical||!make_event||now<=0)return failure;
  if(exec(impl_->db,"BEGIN IMMEDIATE;")!=ESP_OK){failure.status=ReservationStatus::StorageFailure;return failure;}
  auto rollback=[&](){exec(impl_->db,"ROLLBACK;");failure.status=ReservationStatus::StorageFailure;return failure;};
  Statement existing;if(sqlite3_prepare_v2(impl_->db,"SELECT payload_digest,result_payload FROM operations WHERE operation_id=?",-1,&existing.v,nullptr)!=SQLITE_OK)return rollback();sqlite3_bind_text(existing.v,1,id,-1,SQLITE_TRANSIENT);int rc=sqlite3_step(existing.v);
  if(rc==SQLITE_ROW){std::string prior=(const char*)sqlite3_column_text(existing.v,0),result;auto*r=sqlite3_column_text(existing.v,1);if(r)result=(const char*)r;if(exec(impl_->db,"COMMIT;")!=ESP_OK)return rollback();return{prior==digest?ReservationStatus::Duplicate:ReservationStatus::PayloadConflict,result,{}};}if(rc!=SQLITE_DONE)return rollback();
  Statement authority;if(sqlite3_prepare_v2(impl_->db,"SELECT prefix,next_unp,range_end,next_operation FROM authority_state WHERE singleton=1",-1,&authority.v,nullptr)!=SQLITE_OK||sqlite3_step(authority.v)!=SQLITE_ROW){exec(impl_->db,"ROLLBACK;");return failure;}const int64_t unp=sqlite3_column_int64(authority.v,1),last=sqlite3_column_int64(authority.v,2),opseq=sqlite3_column_int64(authority.v,3);if(unp>last){exec(impl_->db,"ROLLBACK;");return failure;}AuthorityReservation allocated{opseq,unp,std::string((const char*)sqlite3_column_text(authority.v,0))+std::to_string(unp)};
  const std::string payload=make_event(allocated);if(payload.empty())return rollback();uint8_t bytes[32]{};if(mbedtls_sha256((const uint8_t*)payload.data(),payload.size(),bytes,0)!=0)return rollback();static constexpr char hex[]="0123456789abcdef";std::string event_digest(64,'0');for(size_t i=0;i<32;i++){event_digest[i*2]=hex[bytes[i]>>4];event_digest[i*2+1]=hex[bytes[i]&15];}
  Statement operation,advance,receipt,event;const bool prepared=sqlite3_prepare_v2(impl_->db,"INSERT INTO operations(operation_id,payload_digest,first_transport,route_snapshot,created_at,updated_at)VALUES(?,?,?,?,?,?)",-1,&operation.v,nullptr)==SQLITE_OK&&sqlite3_prepare_v2(impl_->db,"UPDATE authority_state SET next_unp=next_unp+1,next_operation=next_operation+1 WHERE singleton=1 AND next_unp=? AND next_operation=?",-1,&advance.v,nullptr)==SQLITE_OK&&sqlite3_prepare_v2(impl_->db,"INSERT INTO receipts(receipt_id,operation_id,state,canonical_payload,created_at,updated_at)VALUES(?,?,'RESERVED',?,?,?)",-1,&receipt.v,nullptr)==SQLITE_OK&&sqlite3_prepare_v2(impl_->db,"INSERT INTO event_outbox(event_id,operation_id,kind,payload,payload_digest,created_at)VALUES(?,?,'COMMAND_RECEIVED',?,?,?)",-1,&event.v,nullptr)==SQLITE_OK;if(!prepared)return rollback();
  sqlite3_bind_text(operation.v,1,id,-1,SQLITE_TRANSIENT);sqlite3_bind_text(operation.v,2,digest,-1,SQLITE_TRANSIENT);sqlite3_bind_text(operation.v,3,transport,-1,SQLITE_TRANSIENT);sqlite3_bind_text(operation.v,4,route,-1,SQLITE_TRANSIENT);sqlite3_bind_int64(operation.v,5,now);sqlite3_bind_int64(operation.v,6,now);sqlite3_bind_int64(advance.v,1,unp);sqlite3_bind_int64(advance.v,2,opseq);sqlite3_bind_text(receipt.v,1,receipt_id,-1,SQLITE_TRANSIENT);sqlite3_bind_text(receipt.v,2,id,-1,SQLITE_TRANSIENT);sqlite3_bind_text(receipt.v,3,canonical,-1,SQLITE_TRANSIENT);sqlite3_bind_int64(receipt.v,4,now);sqlite3_bind_int64(receipt.v,5,now);sqlite3_bind_text(event.v,1,event_id,-1,SQLITE_TRANSIENT);sqlite3_bind_text(event.v,2,id,-1,SQLITE_TRANSIENT);sqlite3_bind_text(event.v,3,payload.c_str(),-1,SQLITE_TRANSIENT);sqlite3_bind_text(event.v,4,event_digest.c_str(),-1,SQLITE_TRANSIENT);sqlite3_bind_int64(event.v,5,now);
  if(sqlite3_step(operation.v)!=SQLITE_DONE||sqlite3_step(advance.v)!=SQLITE_DONE||sqlite3_changes(impl_->db)!=1||sqlite3_step(receipt.v)!=SQLITE_DONE||sqlite3_step(event.v)!=SQLITE_DONE)return rollback();
  for(const auto&p:payments){Statement payment;if(p.payment_id.empty()||p.amount_minor<0||sqlite3_prepare_v2(impl_->db,"INSERT INTO payments(payment_id,operation_id,receipt_id,state,amount_minor,created_at,updated_at)VALUES(?,?,?,'RESERVED',?,?,?)",-1,&payment.v,nullptr)!=SQLITE_OK)return rollback();sqlite3_bind_text(payment.v,1,p.payment_id.c_str(),-1,SQLITE_TRANSIENT);sqlite3_bind_text(payment.v,2,id,-1,SQLITE_TRANSIENT);sqlite3_bind_text(payment.v,3,receipt_id,-1,SQLITE_TRANSIENT);sqlite3_bind_int64(payment.v,4,p.amount_minor);sqlite3_bind_int64(payment.v,5,now);sqlite3_bind_int64(payment.v,6,now);if(sqlite3_step(payment.v)!=SQLITE_DONE)return rollback();}
  if(exec(impl_->db,"COMMIT;")!=ESP_OK)return rollback();
  return{ReservationStatus::New,{},allocated};
}
esp_err_t DurableStorage::set_operation_state(const char*id,const char*state,const char*result,int64_t now){if(!ready()||!id||!state||now<=0)return ESP_ERR_INVALID_ARG;Statement s;if(sqlite3_prepare_v2(impl_->db,"UPDATE operations SET state=?,result_payload=?,updated_at=? WHERE operation_id=?",-1,&s.v,nullptr)!=SQLITE_OK)return ESP_FAIL;sqlite3_bind_text(s.v,1,state,-1,SQLITE_TRANSIENT);if(result)sqlite3_bind_text(s.v,2,result,-1,SQLITE_TRANSIENT);else sqlite3_bind_null(s.v,2);sqlite3_bind_int64(s.v,3,now);sqlite3_bind_text(s.v,4,id,-1,SQLITE_TRANSIENT);return sqlite3_step(s.v)==SQLITE_DONE&&sqlite3_changes(impl_->db)==1?ESP_OK:ESP_ERR_NOT_FOUND;}
esp_err_t DurableStorage::operation(const char*id,OperationRecord&out)const{out={};if(!ready()||!id||!*id)return ESP_ERR_INVALID_ARG;Statement s;if(sqlite3_prepare_v2(impl_->db,"SELECT operation_id,payload_digest,state,COALESCE(result_payload,''),updated_at FROM operations WHERE operation_id=?",-1,&s.v,nullptr)!=SQLITE_OK)return ESP_FAIL;sqlite3_bind_text(s.v,1,id,-1,SQLITE_TRANSIENT);const int rc=sqlite3_step(s.v);if(rc==SQLITE_DONE)return ESP_ERR_NOT_FOUND;if(rc!=SQLITE_ROW)return ESP_FAIL;out.operation_id=(const char*)sqlite3_column_text(s.v,0);out.payload_digest=(const char*)sqlite3_column_text(s.v,1);out.state=(const char*)sqlite3_column_text(s.v,2);out.result_payload=(const char*)sqlite3_column_text(s.v,3);out.updated_at=sqlite3_column_int64(s.v,4);return ESP_OK;}
esp_err_t DurableStorage::upsert_receipt(const char*rid,const char*oid,const char*state,const char*payload,int64_t now){if(!ready()||!rid||!oid||!state||!payload||now<=0)return ESP_ERR_INVALID_ARG;Statement s;const char*sql="INSERT INTO receipts(receipt_id,operation_id,state,canonical_payload,created_at,updated_at)VALUES(?,?,?,?,?,?) ON CONFLICT(receipt_id)DO UPDATE SET state=excluded.state,canonical_payload=excluded.canonical_payload,updated_at=excluded.updated_at WHERE receipts.operation_id=excluded.operation_id";if(sqlite3_prepare_v2(impl_->db,sql,-1,&s.v,nullptr)!=SQLITE_OK)return ESP_FAIL;sqlite3_bind_text(s.v,1,rid,-1,SQLITE_TRANSIENT);sqlite3_bind_text(s.v,2,oid,-1,SQLITE_TRANSIENT);sqlite3_bind_text(s.v,3,state,-1,SQLITE_TRANSIENT);sqlite3_bind_text(s.v,4,payload,-1,SQLITE_TRANSIENT);sqlite3_bind_int64(s.v,5,now);sqlite3_bind_int64(s.v,6,now);return sqlite3_step(s.v)==SQLITE_DONE&&sqlite3_changes(impl_->db)==1?ESP_OK:ESP_FAIL;}
esp_err_t DurableStorage::upsert_payment(const char*pid,const char*oid,const char*rid,const char*state,int64_t amount,const char*reference,const char*rrn,const char*auth,int64_t now){if(!ready()||!pid||!oid||!state||amount<0||now<=0)return ESP_ERR_INVALID_ARG;Statement s;const char*sql="INSERT INTO payments(payment_id,operation_id,receipt_id,state,amount_minor,terminal_reference,rrn,auth_code,created_at,updated_at)VALUES(?,?,?,?,?,?,?,?,?,?) ON CONFLICT(payment_id)DO UPDATE SET state=excluded.state,terminal_reference=COALESCE(excluded.terminal_reference,payments.terminal_reference),rrn=COALESCE(excluded.rrn,payments.rrn),auth_code=COALESCE(excluded.auth_code,payments.auth_code),updated_at=excluded.updated_at WHERE payments.operation_id=excluded.operation_id";if(sqlite3_prepare_v2(impl_->db,sql,-1,&s.v,nullptr)!=SQLITE_OK)return ESP_FAIL;sqlite3_bind_text(s.v,1,pid,-1,SQLITE_TRANSIENT);sqlite3_bind_text(s.v,2,oid,-1,SQLITE_TRANSIENT);if(rid)sqlite3_bind_text(s.v,3,rid,-1,SQLITE_TRANSIENT);else sqlite3_bind_null(s.v,3);sqlite3_bind_text(s.v,4,state,-1,SQLITE_TRANSIENT);sqlite3_bind_int64(s.v,5,amount);const char*values[]={reference,rrn,auth};for(int n=0;n<3;n++)if(values[n])sqlite3_bind_text(s.v,6+n,values[n],-1,SQLITE_TRANSIENT);else sqlite3_bind_null(s.v,6+n);sqlite3_bind_int64(s.v,9,now);sqlite3_bind_int64(s.v,10,now);return sqlite3_step(s.v)==SQLITE_DONE&&sqlite3_changes(impl_->db)==1?ESP_OK:ESP_FAIL;}
esp_err_t DurableStorage::append_event(const char*eid,const char*oid,const char*kind,const char*payload,const char*digest,int64_t now){if(!ready()||!eid||!oid||!kind||!payload||!digest||strlen(digest)!=64||now<=0)return ESP_ERR_INVALID_ARG;Statement s;if(sqlite3_prepare_v2(impl_->db,"INSERT OR IGNORE INTO event_outbox(event_id,operation_id,kind,payload,payload_digest,created_at)VALUES(?,?,?,?,?,?)",-1,&s.v,nullptr)!=SQLITE_OK)return ESP_FAIL;sqlite3_bind_text(s.v,1,eid,-1,SQLITE_TRANSIENT);sqlite3_bind_text(s.v,2,oid,-1,SQLITE_TRANSIENT);sqlite3_bind_text(s.v,3,kind,-1,SQLITE_TRANSIENT);sqlite3_bind_text(s.v,4,payload,-1,SQLITE_TRANSIENT);sqlite3_bind_text(s.v,5,digest,-1,SQLITE_TRANSIENT);sqlite3_bind_int64(s.v,6,now);return sqlite3_step(s.v)==SQLITE_DONE?ESP_OK:ESP_FAIL;}
esp_err_t DurableStorage::pending(size_t limit,const std::function<bool(const PendingEvent&)>&visitor){if(!ready()||!visitor||!limit)return ESP_ERR_INVALID_ARG;Statement s;if(sqlite3_prepare_v2(impl_->db,"SELECT sequence,event_id,operation_id,kind,payload,payload_digest,created_at,attempt_count FROM event_outbox WHERE acknowledged_at IS NULL ORDER BY sequence LIMIT ?",-1,&s.v,nullptr)!=SQLITE_OK)return ESP_FAIL;sqlite3_bind_int64(s.v,1,limit);int rc;while((rc=sqlite3_step(s.v))==SQLITE_ROW){PendingEvent e{sqlite3_column_int64(s.v,0),(const char*)sqlite3_column_text(s.v,1),(const char*)sqlite3_column_text(s.v,2),(const char*)sqlite3_column_text(s.v,3),(const char*)sqlite3_column_text(s.v,4),(const char*)sqlite3_column_text(s.v,5),sqlite3_column_int64(s.v,6),(uint32_t)sqlite3_column_int64(s.v,7)};if(!visitor(e))break;}return rc==SQLITE_DONE||rc==SQLITE_ROW?ESP_OK:ESP_FAIL;}
esp_err_t DurableStorage::record_publish_attempt(const char*eid,const char*error,int64_t now){if(!ready()||!eid||now<=0)return ESP_ERR_INVALID_ARG;Statement s;if(sqlite3_prepare_v2(impl_->db,"UPDATE event_outbox SET attempt_count=attempt_count+1,last_attempt_at=?,last_error=? WHERE event_id=? AND acknowledged_at IS NULL",-1,&s.v,nullptr)!=SQLITE_OK)return ESP_FAIL;sqlite3_bind_int64(s.v,1,now);if(error)sqlite3_bind_text(s.v,2,error,-1,SQLITE_TRANSIENT);else sqlite3_bind_null(s.v,2);sqlite3_bind_text(s.v,3,eid,-1,SQLITE_TRANSIENT);return sqlite3_step(s.v)==SQLITE_DONE?ESP_OK:ESP_FAIL;}
esp_err_t DurableStorage::acknowledge_through(int64_t seq,const char*ack,const char*event_hash,int64_t now){if(!ready()||seq<1||!ack||!*ack||!event_hash||strlen(event_hash)!=64||now<=0)return ESP_ERR_INVALID_ARG;if(exec(impl_->db,"BEGIN IMMEDIATE;")!=ESP_OK)return ESP_FAIL;Statement verify,a,c;if(sqlite3_prepare_v2(impl_->db,"SELECT COALESCE(MAX(sequence),0) FROM event_outbox",-1,&verify.v,nullptr)!=SQLITE_OK||sqlite3_step(verify.v)!=SQLITE_ROW||seq>sqlite3_column_int64(verify.v,0)){exec(impl_->db,"ROLLBACK;");return ESP_ERR_INVALID_ARG;}if(sqlite3_prepare_v2(impl_->db,"UPDATE event_outbox SET acknowledged_at=?,ack_id=?,last_error=NULL WHERE sequence<=? AND acknowledged_at IS NULL",-1,&a.v,nullptr)!=SQLITE_OK){exec(impl_->db,"ROLLBACK;");return ESP_FAIL;}sqlite3_bind_int64(a.v,1,now);sqlite3_bind_text(a.v,2,ack,-1,SQLITE_TRANSIENT);sqlite3_bind_int64(a.v,3,seq);if(sqlite3_step(a.v)!=SQLITE_DONE||sqlite3_prepare_v2(impl_->db,"UPDATE sync_cursor SET acknowledged_sequence=MAX(acknowledged_sequence,?),ack_id=?,committed_event_hash=?,updated_at=? WHERE singleton=1",-1,&c.v,nullptr)!=SQLITE_OK){exec(impl_->db,"ROLLBACK;");return ESP_FAIL;}sqlite3_bind_int64(c.v,1,seq);sqlite3_bind_text(c.v,2,ack,-1,SQLITE_TRANSIENT);sqlite3_bind_text(c.v,3,event_hash,-1,SQLITE_TRANSIENT);sqlite3_bind_int64(c.v,4,now);if(sqlite3_step(c.v)!=SQLITE_DONE||exec(impl_->db,"COMMIT;")!=ESP_OK){exec(impl_->db,"ROLLBACK;");return ESP_FAIL;}return ESP_OK;}
esp_err_t DurableStorage::recovery(size_t limit,const std::function<bool(const RecoveryItem&)>&visitor){if(!ready()||!visitor||!limit)return ESP_ERR_INVALID_ARG;Statement s;const char*sql="SELECT o.operation_id,COALESCE(r.receipt_id,''),o.state,o.route_snapshot,COALESCE(r.canonical_payload,''),COALESCE(json_extract(r.canonical_payload,'$.unp'),''),COALESCE(p.payment_id,''),COALESCE(p.amount_minor,0),COALESCE(p.state,''),COALESCE(p.terminal_reference,''),COALESCE(p.rrn,''),COALESCE(p.auth_code,''),o.updated_at FROM operations o LEFT JOIN receipts r ON r.operation_id=o.operation_id LEFT JOIN payments p ON p.payment_id=(SELECT p1.payment_id FROM payments p1 WHERE p1.operation_id=o.operation_id AND (p1.terminal_reference IS NOT NULL OR p1.state IN('CARD_UNKNOWN','CARD_APPROVED','EXECUTING')) ORDER BY CASE WHEN p1.terminal_reference IS NOT NULL THEN 0 ELSE 1 END,p1.updated_at DESC,p1.payment_id LIMIT 1) WHERE o.state NOT IN('COMMITTED','COMPENSATED','REJECTED') ORDER BY o.updated_at LIMIT ?";if(sqlite3_prepare_v2(impl_->db,sql,-1,&s.v,nullptr)!=SQLITE_OK)return ESP_FAIL;sqlite3_bind_int64(s.v,1,limit);int rc;while((rc=sqlite3_step(s.v))==SQLITE_ROW){RecoveryItem item{(const char*)sqlite3_column_text(s.v,0),(const char*)sqlite3_column_text(s.v,1),(const char*)sqlite3_column_text(s.v,2),(const char*)sqlite3_column_text(s.v,3),(const char*)sqlite3_column_text(s.v,4),(const char*)sqlite3_column_text(s.v,5),(const char*)sqlite3_column_text(s.v,6),sqlite3_column_int64(s.v,7),(const char*)sqlite3_column_text(s.v,8),(const char*)sqlite3_column_text(s.v,9),(const char*)sqlite3_column_text(s.v,10),(const char*)sqlite3_column_text(s.v,11),sqlite3_column_int64(s.v,12)};if(!visitor(item))break;}return rc==SQLITE_DONE||rc==SQLITE_ROW?ESP_OK:ESP_FAIL;}
esp_err_t DurableStorage::prune_acknowledged(int64_t now,uint32_t days){if(!ready()||now<=0||days<90)return ESP_ERR_INVALID_ARG;Statement s;if(sqlite3_prepare_v2(impl_->db,"DELETE FROM event_outbox WHERE acknowledged_at IS NOT NULL AND created_at<?",-1,&s.v,nullptr)!=SQLITE_OK)return ESP_FAIL;sqlite3_bind_int64(s.v,1,now-(int64_t)days*86400);return sqlite3_step(s.v)==SQLITE_DONE?ESP_OK:ESP_FAIL;}
int64_t DurableStorage::acknowledged_cursor()const{if(!ready())return-1;Statement s;if(sqlite3_prepare_v2(impl_->db,"SELECT acknowledged_sequence FROM sync_cursor WHERE singleton=1",-1,&s.v,nullptr)!=SQLITE_OK)return-1;return sqlite3_step(s.v)==SQLITE_ROW?sqlite3_column_int64(s.v,0):-1;}
std::string DurableStorage::acknowledged_event_hash()const{if(!ready())return{};Statement s;if(sqlite3_prepare_v2(impl_->db,"SELECT COALESCE(committed_event_hash,'') FROM sync_cursor WHERE singleton=1",-1,&s.v,nullptr)!=SQLITE_OK)return{};if(sqlite3_step(s.v)!=SQLITE_ROW)return{};auto*v=sqlite3_column_text(s.v,0);return v?(const char*)v:"";}
esp_err_t DurableStorage::configure_authority(const char*prefix,int64_t first,int64_t last,int64_t generation){if(!ready()||!prefix||!*prefix||first<1||last<first||generation<1)return ESP_ERR_INVALID_ARG;Statement s;const char*sql="INSERT INTO authority_state(singleton,prefix,range_start,range_end,next_unp,next_operation,generation)VALUES(1,?,?,?,?,1,?) ON CONFLICT(singleton)DO UPDATE SET prefix=excluded.prefix,range_start=excluded.range_start,range_end=excluded.range_end,next_unp=CASE WHEN authority_state.generation=excluded.generation THEN authority_state.next_unp ELSE excluded.range_start END,generation=excluded.generation WHERE authority_state.generation<=excluded.generation";if(sqlite3_prepare_v2(impl_->db,sql,-1,&s.v,nullptr)!=SQLITE_OK)return ESP_FAIL;sqlite3_bind_text(s.v,1,prefix,-1,SQLITE_TRANSIENT);sqlite3_bind_int64(s.v,2,first);sqlite3_bind_int64(s.v,3,last);sqlite3_bind_int64(s.v,4,first);sqlite3_bind_int64(s.v,5,generation);return sqlite3_step(s.v)==SQLITE_DONE&&sqlite3_changes(impl_->db)==1?ESP_OK:ESP_ERR_INVALID_VERSION;}
esp_err_t DurableStorage::reserve_authority(AuthorityReservation&out){out={};if(!ready()||exec(impl_->db,"BEGIN IMMEDIATE;")!=ESP_OK)return ESP_FAIL;Statement q,u;if(sqlite3_prepare_v2(impl_->db,"SELECT prefix,next_unp,range_end,next_operation FROM authority_state WHERE singleton=1",-1,&q.v,nullptr)!=SQLITE_OK||sqlite3_step(q.v)!=SQLITE_ROW){exec(impl_->db,"ROLLBACK;");return ESP_ERR_INVALID_STATE;}const int64_t unp=sqlite3_column_int64(q.v,1),last=sqlite3_column_int64(q.v,2),operation=sqlite3_column_int64(q.v,3);if(unp>last){exec(impl_->db,"ROLLBACK;");return ESP_ERR_NO_MEM;}const char*prefix=(const char*)sqlite3_column_text(q.v,0);out={operation,unp,std::string(prefix)+std::to_string(unp)};if(sqlite3_prepare_v2(impl_->db,"UPDATE authority_state SET next_unp=next_unp+1,next_operation=next_operation+1 WHERE singleton=1",-1,&u.v,nullptr)!=SQLITE_OK||sqlite3_step(u.v)!=SQLITE_DONE||exec(impl_->db,"COMMIT;")!=ESP_OK){exec(impl_->db,"ROLLBACK;");out={};return ESP_FAIL;}return ESP_OK;}
esp_err_t DurableStorage::load_local_sale(const char*id,std::string&payload,int64_t&version,std::string&state)const{payload.clear();state.clear();version=0;if(!ready()||!id||!*id)return ESP_ERR_INVALID_ARG;Statement s;if(sqlite3_prepare_v2(impl_->db,"SELECT version,state,payload FROM local_sales WHERE surrogate_id=?",-1,&s.v,nullptr)!=SQLITE_OK)return ESP_FAIL;sqlite3_bind_text(s.v,1,id,-1,SQLITE_TRANSIENT);int rc=sqlite3_step(s.v);if(rc==SQLITE_DONE)return ESP_ERR_NOT_FOUND;if(rc!=SQLITE_ROW)return ESP_FAIL;version=sqlite3_column_int64(s.v,0);state=(const char*)sqlite3_column_text(s.v,1);payload=(const char*)sqlite3_column_text(s.v,2);return ESP_OK;}
esp_err_t DurableStorage::save_local_sale(const char*id,int64_t version,const char*state,const char*payload,int64_t now){if(!ready()||!id||!*id||version<1||!state||!*state||!payload||now<=0)return ESP_ERR_INVALID_ARG;Statement s;const char*sql="INSERT INTO local_sales(surrogate_id,version,state,payload,created_at,updated_at)VALUES(?,?,?,?,?,?) ON CONFLICT(surrogate_id)DO UPDATE SET version=excluded.version,state=excluded.state,payload=excluded.payload,updated_at=excluded.updated_at WHERE local_sales.version<excluded.version";if(sqlite3_prepare_v2(impl_->db,sql,-1,&s.v,nullptr)!=SQLITE_OK)return ESP_FAIL;sqlite3_bind_text(s.v,1,id,-1,SQLITE_TRANSIENT);sqlite3_bind_int64(s.v,2,version);sqlite3_bind_text(s.v,3,state,-1,SQLITE_TRANSIENT);sqlite3_bind_text(s.v,4,payload,-1,SQLITE_TRANSIENT);sqlite3_bind_int64(s.v,5,now);sqlite3_bind_int64(s.v,6,now);return sqlite3_step(s.v)==SQLITE_DONE&&sqlite3_changes(impl_->db)==1?ESP_OK:ESP_ERR_INVALID_STATE;}
}
