#include "intent_processor.h"
#include "canonical_cbor.h"
#include "cJSON.h"
#include <ctime>
#include "mbedtls/sha256.h"
#include "mbedtls/base64.h"
#include "mbedtls/md.h"
#include <cstdio>
#include <cstring>
#include <memory>
#include <algorithm>

namespace beefiscal::idf{namespace{
struct Del{void operator()(cJSON*v)const{cJSON_Delete(v);}};using Json=std::unique_ptr<cJSON,Del>;
bool text(const cJSON*p,const char*n,std::string&o,size_t max=4096){auto*v=cJSON_GetObjectItemCaseSensitive(p,n);if(!cJSON_IsString(v)||!v->valuestring)return false;size_t z=strlen(v->valuestring);if(!z||z>max)return false;o.assign(v->valuestring,z);return true;}
bool uuid(const std::string&s){if(s.size()!=36)return false;for(size_t i=0;i<s.size();i++){if(i==8||i==13||i==18||i==23){if(s[i]!='-')return false;}else if(!isxdigit((unsigned char)s[i]))return false;}return true;}
bool money(const std::string&s,int64_t&minor){if(s.size()<4)return false;auto dot=s.find('.');if(dot==std::string::npos||s.size()-dot!=3)return false;int64_t whole=0,fraction=0;for(size_t i=0;i<dot;i++){if(!isdigit((unsigned char)s[i]))return false;whole=whole*10+s[i]-'0';if(whole>1000000000)return false;}if(!isdigit(s[dot+1])||!isdigit(s[dot+2]))return false;fraction=(s[dot+1]-'0')*10+s[dot+2]-'0';minor=whole*100+fraction;return minor>0;}
std::string hash(const char*d,size_t z){uint8_t out[32]{};if(mbedtls_sha256((const uint8_t*)d,z,out,0)!=0)return{};static constexpr char h[]="0123456789abcdef";std::string s(64,'0');for(size_t i=0;i<32;i++){s[i*2]=h[out[i]>>4];s[i*2+1]=h[out[i]&15];}return s;}
int64_t now(){const auto value=std::time(nullptr);return value>=1704067200?value:0;}
const char*state(ExecutionCertainty c){switch(c){case ExecutionCertainty::Committed:return"COMMITTED";case ExecutionCertainty::Compensated:return"COMPENSATED";case ExecutionCertainty::Unknown:return"RECOVERY_REQUIRED";case ExecutionCertainty::DeviceUnavailable:return"RECOVERY_REQUIRED";default:return"REJECTED";}}
std::string result_json(const ReceiptPlan&p,const ExecutionResult&r){char b[1024];snprintf(b,sizeof(b),"{\"error_code\":\"%s\",\"fiscal_reference\":\"%s\",\"operation_id\":\"%s\",\"state\":\"%s\"}",r.error_code.c_str(),r.fiscal_reference.c_str(),p.operation_id.c_str(),state(r.certainty));return b;}
std::string accepted_json(const ReceiptPlan&p,const CompositeBinding&b,const AuthorityReservation&a){cJSON*root=cJSON_CreateObject();cJSON_AddNumberToObject(root,"operation_sequence",a.operation_sequence);cJSON_AddNumberToObject(root,"unp_sequence",a.unp_sequence);cJSON*command=cJSON_AddObjectToObject(root,"command");cJSON_AddStringToObject(command,"operation_id",p.operation_id.c_str());cJSON_AddStringToObject(command,"tenant_id",b.tenant_id.c_str());cJSON_AddStringToObject(command,"register_id",b.register_id.c_str());cJSON_AddStringToObject(command,"device_id",b.edge_device_id.c_str());cJSON_AddStringToObject(command,"command_type",p.command_type.c_str());cJSON*payload=cJSON_Parse(p.canonical_payload.c_str());cJSON_AddItemToObject(command,"payload",payload?payload:cJSON_CreateObject());char*raw=cJSON_PrintUnformatted(root);std::string out=raw?raw:"";cJSON_free(raw);cJSON_Delete(root);return out;}
bool verify_hmac(cJSON*root,const std::string&key){auto*signature=cJSON_DetachItemFromObjectCaseSensitive(root,"signature");if(!cJSON_IsString(signature)){cJSON_Delete(signature);return false;}std::string supplied=signature->valuestring;cJSON_Delete(signature);char*raw=cJSON_PrintUnformatted(root);if(!raw)return false;std::string canonical=raw;cJSON_free(raw);for(char&c:supplied){if(c=='-')c='+';else if(c=='_')c='/';}while(supplied.size()%4)supplied+='=';uint8_t got[64],expected[32];size_t n=0;if(mbedtls_base64_decode(got,sizeof(got),&n,(uint8_t*)supplied.data(),supplied.size())||n!=32)return false;std::string decoded_key=key;for(char&c:decoded_key){if(c=='-')c='+';else if(c=='_')c='/';}while(decoded_key.size()%4)decoded_key+='=';uint8_t key_bytes[64];size_t key_size=0;if(mbedtls_base64_decode(key_bytes,sizeof(key_bytes),&key_size,(uint8_t*)decoded_key.data(),decoded_key.size())||key_size<32)return false;auto*info=mbedtls_md_info_from_type(MBEDTLS_MD_SHA256);if(mbedtls_md_hmac(info,key_bytes,key_size,(uint8_t*)canonical.data(),canonical.size(),expected))return false;uint8_t difference=0;for(size_t i=0;i<32;i++)difference|=got[i]^expected[i];return difference==0;}
}
IntentProcessor::IntentProcessor(DurableStorage&s,const CompositeBinding&b,ReceiptExecutor&e,const std::string&key,ResultSink sink,void*context):storage_(s),binding_(b),executor_(e),command_hmac_key_(key),result_sink_(sink),result_context_(context){}
esp_err_t IntentProcessor::decode(const CommandView&view,ReceiptPlan&p){if(!view.data||!view.size||view.size>8192)return ESP_ERR_INVALID_ARG;cJSON*decoded=nullptr;if(view.ingress==Ingress::Ble){if(canonical_cbor_to_json(view.data,view.size,&decoded)!=ESP_OK)return ESP_ERR_INVALID_ARG;}else decoded=cJSON_ParseWithLengthOpts((const char*)view.data,view.size,nullptr,false);Json root(decoded);if(!root||!cJSON_IsObject(root.get()))return ESP_ERR_INVALID_ARG;if(view.ingress==Ingress::Mqtt&&!verify_hmac(root.get(),command_hmac_key_))return ESP_ERR_INVALID_CRC;std::string tenant,reg,device,provided;const bool local=view.ingress==Ingress::Ble;auto*payload=local?root.get():cJSON_GetObjectItemCaseSensitive(root.get(),"payload");auto*fence=cJSON_GetObjectItemCaseSensitive(root.get(),local?"binding_generation":"fencing_token");if(!cJSON_IsObject(payload)||!cJSON_IsNumber(fence)||fence->valuedouble!=fence->valueint||fence->valueint!=binding_.generation||!text(root.get(),"tenant_id",tenant)||!text(root.get(),"register_id",reg)||!(local?text(root.get(),"edge_device_id",device):text(root.get(),"device_id",device))||tenant!=binding_.tenant_id||reg!=binding_.register_id||device!=binding_.edge_device_id)return ESP_ERR_INVALID_STATE;if(local){if(!text(root.get(),"intent_id",p.operation_id)||!text(root.get(),"action",p.command_type))return ESP_ERR_INVALID_ARG;if(!text(root.get(),"receipt_session_id",p.receipt_session_id))return ESP_ERR_INVALID_ARG;}else{if(!text(root.get(),"client_operation_id",p.operation_id)&&!text(root.get(),"operation_id",p.operation_id))return ESP_ERR_INVALID_ARG;if(!text(root.get(),"receipt_session_id",p.receipt_session_id)||!text(root.get(),"command_type",p.command_type)||!text(root.get(),"payload_sha256",provided,64))return ESP_ERR_INVALID_ARG;}if(!uuid(p.operation_id)||!uuid(p.receipt_session_id))return ESP_ERR_INVALID_ARG;const std::vector<std::string>allowed={"SALE_FINALIZE","SALE_REVERSE","REPORT_X","REPORT_Z","CASH_IN","CASH_OUT","DEVICE_IDENTITY","DEVICE_TIME"};if(std::find(allowed.begin(),allowed.end(),p.command_type)==allowed.end())return ESP_ERR_NOT_SUPPORTED;
  char*canonical=cJSON_PrintUnformatted(payload);if(!canonical)return ESP_ERR_NO_MEM;p.canonical_payload=canonical;cJSON_free(canonical);p.payload_digest=hash(p.canonical_payload.data(),p.canonical_payload.size());if(!local&&p.payload_digest!=provided)return ESP_ERR_INVALID_CRC;
  // Non-sale commands are first-class operations. UNP is allocated durably by
  // reserve_command() and is never accepted as client authority.
  if(p.command_type=="SALE_FINALIZE"&&!text(payload,"server_sale_id",p.sale_id))return ESP_ERR_INVALID_ARG;
  p.route_snapshot="{\"binding_generation\":"+std::to_string(binding_.generation)+",\"edge_device_id\":\""+binding_.edge_device_id+"\",\"fiscal_device_id\":\""+binding_.fiscal.device_id+"\""+(binding_.payment.present?",\"payment_device_id\":\""+binding_.payment.device_id+"\"":"")+"}";
  if(p.command_type=="REPORT_X"||p.command_type=="REPORT_Z"||p.command_type=="DEVICE_IDENTITY"||p.command_type=="DEVICE_TIME")return ESP_OK;
  if(p.command_type=="CASH_IN"||p.command_type=="CASH_OUT"){auto*a=cJSON_GetObjectItemCaseSensitive(payload,"amount");std::string currency;int64_t minor=0;if(!cJSON_IsObject(a)||!text(a,"amount",p.amount,32)||!text(a,"currency",currency,3)||currency!="EUR"||!money(p.amount,minor))return ESP_ERR_INVALID_ARG;return ESP_OK;}
  if(p.command_type=="SALE_REVERSE"){auto*original=cJSON_GetObjectItemCaseSensitive(payload,"original_document");auto*number=cJSON_GetObjectItemCaseSensitive(original,"document_number");auto*reason=cJSON_GetObjectItemCaseSensitive(payload,"reason");if(!cJSON_IsObject(original)||!cJSON_IsNumber(number)||number->valueint<1||!text(original,"document_datetime",p.original_datetime,32)||!text(original,"fiscal_memory_number",p.original_fmin,16)||!cJSON_IsNumber(reason)||reason->valueint<0||reason->valueint>2)return ESP_ERR_INVALID_ARG;p.original_document=number->valueint;p.reversal_reason=reason->valueint;}
  auto*items=cJSON_GetObjectItemCaseSensitive(payload,"items");auto*payments=cJSON_GetObjectItemCaseSensitive(payload,"payments");if(!cJSON_IsArray(items)||!cJSON_IsArray(payments)||cJSON_GetArraySize(items)<1||cJSON_GetArraySize(payments)<1)return ESP_ERR_INVALID_ARG;
  cJSON*item=nullptr;cJSON_ArrayForEach(item,items){IntentLine l;auto*price=cJSON_GetObjectItemCaseSensitive(item,"unit_price");if(!text(item,"line_id",l.id)||!uuid(l.id)||!text(item,"name",l.name,240)||!text(item,"quantity",l.quantity,32)||!cJSON_IsObject(price)||!text(price,"amount",l.unit_price,32)||!text(item,"tax_group",l.tax_group,8))return ESP_ERR_INVALID_ARG;p.items.push_back(std::move(l));}
  int64_t total=0;cJSON*payment=nullptr;cJSON_ArrayForEach(payment,payments){IntentPayment v;auto*amount=cJSON_GetObjectItemCaseSensitive(payment,"amount");std::string currency;if(!text(payment,"payment_id",v.id)||!uuid(v.id)||!text(payment,"type",v.type,8)||(v.type!="CASH"&&v.type!="CARD")||!cJSON_IsObject(amount)||!text(amount,"amount",v.amount,32)||!text(amount,"currency",currency,3)||currency!="EUR"||!money(v.amount,v.amount_minor))return ESP_ERR_INVALID_ARG;total+=v.amount_minor;p.payments.push_back(std::move(v));}return total>0?ESP_OK:ESP_ERR_INVALID_ARG;}
esp_err_t IntentProcessor::execute(ReceiptPlan&p,Ingress ingress){
  const int64_t at=now();std::string event="received-"+p.operation_id;
  // Never consume authority or touch a final device when the durable journal
  // cannot retain the command, result and sync evidence.
  if(!storage_.can_accept_operation())return ESP_ERR_NO_MEM;
  std::vector<InitialPayment> initial;for(const auto&v:p.payments)initial.push_back({v.id,v.amount_minor});
  auto reserved=storage_.reserve_command(p.operation_id.c_str(),p.payload_digest.c_str(),
    ingress==Ingress::Mqtt?"MQTT":"BLE",p.route_snapshot.c_str(),event.c_str(),
    p.receipt_session_id.c_str(),p.canonical_payload.c_str(),initial,at,
    [&](const AuthorityReservation&a){p.unp=a.unp;return accepted_json(p,binding_,a);});
  if(reserved.status==ReservationStatus::Duplicate){if(result_sink_&&!reserved.prior_result.empty())result_sink_(p.operation_id.c_str(),reserved.prior_result.c_str(),ingress,result_context_);return ESP_OK;}
  if(reserved.status==ReservationStatus::PayloadConflict)return ESP_ERR_INVALID_CRC;
  if(reserved.status!=ReservationStatus::New)return ESP_FAIL;
  p.unp=reserved.authority.unp;
  if(!executor_.ready()){std::string unavailable="{\"error_code\":\"PHYSICAL_DEVICE_UNAVAILABLE\",\"operation_id\":\""+p.operation_id+"\",\"state\":\"RECOVERY_REQUIRED\"}";storage_.set_operation_state(p.operation_id.c_str(),"RECOVERY_REQUIRED",unavailable.c_str(),at);if(result_sink_)result_sink_(p.operation_id.c_str(),unavailable.c_str(),ingress,result_context_);return ESP_ERR_INVALID_STATE;}
  storage_.set_operation_state(p.operation_id.c_str(),"EXECUTING",nullptr,at);auto r=executor_.execute(p);auto result=result_json(p,r);storage_.set_operation_state(p.operation_id.c_str(),state(r.certainty),result.c_str(),now());storage_.upsert_receipt(p.receipt_session_id.c_str(),p.operation_id.c_str(),state(r.certainty),p.canonical_payload.c_str(),now());for(auto&v:p.payments)storage_.upsert_payment(v.id.c_str(),p.operation_id.c_str(),p.receipt_session_id.c_str(),state(r.certainty),v.amount_minor,r.terminal_reference.empty()?nullptr:r.terminal_reference.c_str(),r.rrn.empty()?nullptr:r.rrn.c_str(),r.auth_code.empty()?nullptr:r.auth_code.c_str(),now());std::string eid="result-"+p.operation_id;auto stored=storage_.append_event(eid.c_str(),p.operation_id.c_str(),"RECEIPT_RESULT",result.c_str(),hash(result.data(),result.size()).c_str(),now());if(stored==ESP_OK&&result_sink_)result_sink_(p.operation_id.c_str(),result.c_str(),ingress,result_context_);return stored;
}
esp_err_t IntentProcessor::accept(const CommandView&v){ReceiptPlan p;esp_err_t e=decode(v,p);return e==ESP_OK?execute(p,v.ingress):e;}
esp_err_t IntentProcessor::recover_pending(){esp_err_t result=ESP_OK;storage_.recovery(128,[&](const RecoveryItem&i){auto r=executor_.recover(i);const auto terminal=r.terminal_reference.empty()?i.terminal_reference:r.terminal_reference;const auto rrn=r.rrn.empty()?i.rrn:r.rrn;const auto auth=r.auth_code.empty()?i.auth_code:r.auth_code;std::string payload="{\"auth_code\":\""+auth+"\",\"fiscal_reference\":\""+r.fiscal_reference+"\",\"operation_id\":\""+i.operation_id+"\",\"rrn\":\""+rrn+"\",\"state\":\""+state(r.certainty)+"\",\"terminal_reference\":\""+terminal+"\"}";const int64_t at=now();if(storage_.set_operation_state(i.operation_id.c_str(),state(r.certainty),payload.c_str(),at)!=ESP_OK)result=ESP_FAIL;if(!i.receipt_id.empty()&&!i.canonical_payload.empty()&&storage_.upsert_receipt(i.receipt_id.c_str(),i.operation_id.c_str(),state(r.certainty),i.canonical_payload.c_str(),at)!=ESP_OK)result=ESP_FAIL;if(!i.payment_id.empty()&&storage_.upsert_payment(i.payment_id.c_str(),i.operation_id.c_str(),i.receipt_id.empty()?nullptr:i.receipt_id.c_str(),state(r.certainty),i.payment_amount_minor,terminal.empty()?nullptr:terminal.c_str(),rrn.empty()?nullptr:rrn.c_str(),auth.empty()?nullptr:auth.c_str(),at)!=ESP_OK)result=ESP_FAIL;std::string event="recovery-"+i.operation_id;storage_.append_event(event.c_str(),i.operation_id.c_str(),"RECOVERY_RESULT",payload.c_str(),hash(payload.data(),payload.size()).c_str(),at);return true;});return result;}
}
