#include "profile_executor.h"
#include "uart_runtime.h"
#include "edge_runtime_port.h"
#include "bluepad_ble_central.h"
#include "mbedtls/sha256.h"
#include "CommandPayload.hpp"
#include "FrameCodec.hpp"
#include <cstdio>
#include <ctime>
namespace beefiscal::idf{namespace{
std::string reference(const ReceiptPlan&p){uint8_t d[32];mbedtls_sha256((uint8_t*)p.operation_id.data(),p.operation_id.size(),d,0);char b[24];snprintf(b,sizeof(b),"EDGE-%02X%02X%02X%02X",d[0],d[1],d[2],d[3]);return b;}
int write_bytes(const CompositeBinding&b,const uint8_t*p,size_t n){return b.profile==EdgeProfile::DatecsDp150BluePad50?uart_runtime_write(p,n,1000):usb_cdc_write(p,n,1000);}
int read_bytes(const CompositeBinding&b,uint8_t*p,size_t n){return b.profile==EdgeProfile::DatecsDp150BluePad50?uart_runtime_read(p,n,500):usb_cdc_read(p,n,500);}
bool exchange(const CompositeBinding&b,uint16_t command,const std::vector<uint8_t>&payload,uint8_t&sequence,bee::ParsedFrame*out=nullptr){std::vector<uint8_t>frame=b.profile==EdgeProfile::DatecsDp150BluePad50?bee::DatecsCodec::encode(sequence,command,payload):bee::DaisyCodec::encode(sequence,(uint8_t)command,payload);if(frame.empty()||write_bytes(b,frame.data(),frame.size())!=(int)frame.size())return false;std::vector<uint8_t>response;response.reserve(600);uint8_t chunk[128];for(int tries=0;tries<12;tries++){int n=read_bytes(b,chunk,sizeof(chunk));if(n<0)return false;if(n==0)continue;response.insert(response.end(),chunk,chunk+n);if(response.back()==3)break;}bee::ParsedFrame parsed;std::string error;bool ok=b.profile==EdgeProfile::DatecsDp150BluePad50?bee::DatecsCodec::decode(response,parsed,error):bee::DaisyCodec::decode(response,parsed,error);if(!ok||parsed.command!=command||parsed.sequence!=sequence)return false;for(uint8_t status:parsed.status)if(status&0x01)return false;if(out)*out=parsed;sequence=sequence==0xff?0x20:sequence+1;return true;}
bool datecs_document_has_unp(const CompositeBinding&b,uint32_t document,const std::string&unp,uint8_t&sequence){std::vector<uint8_t>payload;std::string error;bee::EjDocumentSelector selector{0,document,0};if(unp.empty()||!bee::buildDatecsEjDocumentSelector(selector,payload,error))return false;bee::ParsedFrame frame;if(!exchange(b,125,payload,sequence,&frame))return false;bee::EjDocumentInfoResult info;if(!bee::parseDatecsEjDocumentInfo(frame.data,info,error)||info.globalDocumentNumber!=document)return false;for(int line=0;line<96;line++){selector={1,0,0};if(!bee::buildDatecsEjDocumentSelector(selector,payload,error)||!exchange(b,125,payload,sequence,&frame))return false;std::string text;if(!bee::parseDatecsEjTextLine(frame.data,text,error))return false;if(text.empty())break;if(text.find(unp)!=std::string::npos)return true;}return false;}
bool daisy_document_has_unp(const CompositeBinding&b,const std::string&unp,uint8_t&sequence,uint32_t&document){std::vector<uint8_t>payload;bee::ParsedFrame frame;std::string error;if(unp.empty()||!exchange(b,113,payload,sequence,&frame)||!bee::parseDaisyLastDocumentNumber(frame.data,document,error)||!document||!bee::buildDaisyIssuedDocument(document,false,payload,error)||!exchange(b,119,payload,sequence,&frame))return false;bee::DaisyIssuedDocumentResult issued;return bee::parseDaisyIssuedDocument(frame.data,false,issued,error)&&issued.found&&issued.number==document&&issued.unp==unp;}
ExecutionResult finish_receipt(const CompositeBinding&b,const ReceiptPlan&p,uint8_t&sequence){std::vector<uint8_t>payload;std::string error;for(auto&line:p.items){bee::SaleItemPayload item;item.name=line.name;item.taxGroup=line.tax_group.empty()?'B':line.tax_group[0];item.unitPrice=line.unit_price;item.quantity=line.quantity;bool built=b.profile==EdgeProfile::DatecsDp150BluePad50?bee::buildDatecsSaleItem(item,payload,error):bee::buildDaisySaleItem(item,payload,error);if(!built||!exchange(b,49,payload,sequence))return{ExecutionCertainty::Unknown,"","FISCAL_LINE_UNKNOWN","","",""};}for(auto&payment:p.payments){bee::PaymentPayload value{payment.amount,payment.type=="CASH"?'P':'N',(uint8_t)(payment.type=="CASH"?0:1)};bool built=b.profile==EdgeProfile::DatecsDp150BluePad50?bee::buildDatecsPayment(value,payload,error):bee::buildDaisyPayment(value,payload,error);if(!built||!exchange(b,53,payload,sequence))return{ExecutionCertainty::Unknown,"","FISCAL_PAYMENT_UNKNOWN","","",""};}payload.clear();if(!exchange(b,56,payload,sequence))return{ExecutionCertainty::Unknown,"","FISCAL_CLOSE_UNKNOWN","","",""};return{ExecutionCertainty::Committed,reference(p),"","","",""};}
}
EspIdfDeviceIo::EspIdfDeviceIo(const CompositeBinding&b):binding_(b){}
bool EspIdfDeviceIo::begin(){if(binding_.profile==EdgeProfile::DatecsDp150BluePad50)return uart_runtime_start(binding_.fiscal)==ESP_OK&&(!binding_.payment.present||bluepad_ble_start(binding_.payment)==ESP_OK);return binding_.profile==EdgeProfile::DaisyCompactS01;}
bool EspIdfDeviceIo::fiscal_ready(){return binding_.profile==EdgeProfile::DatecsDp150BluePad50?uart_runtime_ready():usb_cdc_ready();}
bool EspIdfDeviceIo::payment_ready(){return binding_.payment.present&&bluepad_ble_ready();}
ExecutionResult EspIdfDeviceIo::fiscalize(const ReceiptPlan&p){if(!fiscal_ready())return{ExecutionCertainty::DeviceUnavailable,"","FISCAL_DEVICE_UNAVAILABLE","","",""};uint8_t sequence=0x20;std::vector<uint8_t>payload;std::string error;bee::OpenReceiptPayload open{1,"0000",p.unp,1,false};bool built=binding_.profile==EdgeProfile::DatecsDp150BluePad50?bee::buildDatecsOpenReceipt(open,payload,error):bee::buildDaisyOpenReceipt(open,payload,error);if(!built||!exchange(binding_,48,payload,sequence))return{ExecutionCertainty::Unknown,"","FISCAL_OPEN_UNKNOWN","","",""};return finish_receipt(binding_,p,sequence);}
ExecutionResult EspIdfDeviceIo::fiscal_command(const ReceiptPlan&p){
 if(!fiscal_ready())return{ExecutionCertainty::DeviceUnavailable,"","FISCAL_DEVICE_UNAVAILABLE","","",""};
 uint8_t sequence=0x20;std::vector<uint8_t>payload;std::string error;uint16_t command=0;
 if(p.command_type=="REPORT_X"||p.command_type=="REPORT_Z"){
  command=69;const bool z=p.command_type=="REPORT_Z";
  if(!(binding_.profile==EdgeProfile::DatecsDp150BluePad50?bee::buildDatecsDailyReport(z,payload):bee::buildDaisyDailyReport(z,payload)))return{ExecutionCertainty::Rejected,"","REPORT_PAYLOAD_INVALID","","",""};
 }else if(p.command_type=="CASH_IN"||p.command_type=="CASH_OUT"){
  command=70;bee::CashMovementPayload movement{p.amount,p.command_type=="CASH_OUT"};
  if(!(binding_.profile==EdgeProfile::DatecsDp150BluePad50?bee::buildDatecsCashMovement(movement,payload,error):bee::buildDaisyCashMovement(movement,payload,error)))return{ExecutionCertainty::Rejected,"","CASH_MOVEMENT_INVALID","","",""};
 }else if(p.command_type=="SALE_REVERSE"){
  command=binding_.profile==EdgeProfile::DatecsDp150BluePad50?43:48;bee::ReversalOpenPayload reversal{1,binding_.profile==EdgeProfile::DatecsDp150BluePad50?"00000000":"0000",1,p.reversal_reason,p.original_document,p.original_datetime,p.original_fmin,false,"","",p.unp};
  if(!(binding_.profile==EdgeProfile::DatecsDp150BluePad50?bee::buildDatecsOpenReversal(reversal,payload,error):bee::buildDaisyOpenReversal(reversal,payload,error))||!exchange(binding_,command,payload,sequence))return{ExecutionCertainty::Unknown,"","REVERSAL_OPEN_UNKNOWN","","",""};
  return finish_receipt(binding_,p,sequence);
 }else if(p.command_type=="PRINTER_TEST"){
  if(!exchange(binding_,38,payload,sequence))return{ExecutionCertainty::Unknown,"","PRINTER_TEST_OPEN_UNKNOWN","","",""};
  std::string text="BEELOY PRINTER TEST";if(binding_.profile==EdgeProfile::DatecsDp150BluePad50)text+="\t\t\t\t\t\t";payload.assign(text.begin(),text.end());
  if(!exchange(binding_,42,payload,sequence))return{ExecutionCertainty::Unknown,"","PRINTER_TEST_TEXT_UNKNOWN","","",""};
  payload.clear();if(!exchange(binding_,39,payload,sequence))return{ExecutionCertainty::Unknown,"","PRINTER_TEST_CLOSE_UNKNOWN","","",""};
  return{ExecutionCertainty::Committed,reference(p),"","","",""};
 }else if(p.command_type=="DEVICE_IDENTITY"){
  command=binding_.profile==EdgeProfile::DatecsDp150BluePad50?123:90;if(binding_.profile==EdgeProfile::DatecsDp150BluePad50)payload={'1','\t'};
 }else if(p.command_type=="DEVICE_TIME")command=62;
 else return{ExecutionCertainty::Rejected,"","UNSUPPORTED_FISCAL_COMMAND","","",""};
 if(!exchange(binding_,command,payload,sequence))return{ExecutionCertainty::Unknown,"","FISCAL_COMMAND_UNKNOWN","","",""};
 return{ExecutionCertainty::Committed,reference(p),"","","",""};
}
PaymentOutcome EspIdfDeviceIo::purchase(const std::string&id,int64_t amount){return bluepad_ble_purchase(id,amount);}
PaymentOutcome EspIdfDeviceIo::payment_lookup(const std::string&id){return bluepad_ble_lookup(id);}
PaymentOutcome EspIdfDeviceIo::reverse(const std::string&id,int64_t amount){return bluepad_ble_reverse(id,amount);}
ExecutionResult EspIdfDeviceIo::recover(const RecoveryItem&i){if(!fiscal_ready())return{ExecutionCertainty::DeviceUnavailable,"","FISCAL_DEVICE_UNAVAILABLE",i.terminal_reference,i.rrn,i.auth_code};if(i.state=="CARD_UNKNOWN"&&!i.payment_id.empty()){auto p=payment_lookup(i.terminal_reference.empty()?i.payment_id:i.terminal_reference);if(p.certainty==PaymentCertainty::Unknown)return{ExecutionCertainty::Unknown,"","CARD_UNKNOWN",p.reference,p.rrn,p.auth_code};if(p.certainty==PaymentCertainty::Declined||p.certainty==PaymentCertainty::NotSent)return{ExecutionCertainty::Rejected,"",p.error_code,p.reference,p.rrn,p.auth_code};}uint8_t sequence=0x20;bee::ParsedFrame frame;std::vector<uint8_t>empty;if(!exchange(binding_,76,empty,sequence,&frame))return{ExecutionCertainty::Unknown,"","FISCAL_LOOKUP_UNKNOWN",i.terminal_reference,i.rrn,i.auth_code};bee::ReceiptStatusResult status;std::string error;bool parsed=binding_.profile==EdgeProfile::DatecsDp150BluePad50?bee::parseDatecsReceiptStatus(frame.data,status,error):bee::parseDaisyReceiptStatus(frame.data,status,error);if(!parsed)return{ExecutionCertainty::Unknown,"","FISCAL_LOOKUP_INVALID",i.terminal_reference,i.rrn,i.auth_code};if(status.openState==0){uint32_t document=status.receiptNumber;const bool proven=binding_.profile==EdgeProfile::DatecsDp150BluePad50?document&&datecs_document_has_unp(binding_,document,i.canonical_unp,sequence):daisy_document_has_unp(binding_,i.canonical_unp,sequence,document);if(proven)return{ExecutionCertainty::Committed,"RECOVERED-"+std::to_string(document),"",i.terminal_reference,i.rrn,i.auth_code};return{ExecutionCertainty::Unknown,"","FISCAL_DOCUMENT_NOT_PROVEN",i.terminal_reference,i.rrn,i.auth_code};}if(!exchange(binding_,binding_.profile==EdgeProfile::DatecsDp150BluePad50?60:130,empty,sequence))return{ExecutionCertainty::Unknown,"","FISCAL_CANCEL_UNKNOWN",i.terminal_reference,i.rrn,i.auth_code};if(!i.terminal_reference.empty()&&i.payment_amount_minor>0){auto reversed=reverse(i.terminal_reference,i.payment_amount_minor);if(reversed.certainty!=PaymentCertainty::Approved)return{ExecutionCertainty::Unknown,"","COMPENSATION_REQUIRED",i.terminal_reference,i.rrn,i.auth_code};}return{ExecutionCertainty::Compensated,"","",i.terminal_reference,i.rrn,i.auth_code};}
}
