#include "provisioned_binding.h"
#include "cJSON.h"
#include "mbedtls/base64.h"
#include "mbedtls/pk.h"
#include "mbedtls/sha256.h"
#include "nvs.h"
#include <cctype>
#include <cstring>
#include <memory>
#include <vector>

namespace beefiscal::idf{namespace{
constexpr size_t max_binding=8192;struct Del{void operator()(cJSON*v)const{cJSON_Delete(v);}};
using Json=std::unique_ptr<cJSON,Del>;
const cJSON*obj(const cJSON*p,const char*n){auto*v=cJSON_GetObjectItemCaseSensitive(p,n);return cJSON_IsObject(v)?v:nullptr;}
bool keys(const cJSON*v,std::initializer_list<const char*>a){for(auto*f=v?v->child:nullptr;f;f=f->next){bool ok=false;for(auto*n:a)ok|=f->string&&strcmp(f->string,n)==0;if(!ok)return false;}return true;}
bool str(const cJSON*p,const char*n,std::string&o,size_t max=256){auto*v=cJSON_GetObjectItemCaseSensitive(p,n);if(!cJSON_IsString(v)||!v->valuestring)return false;size_t z=strlen(v->valuestring);if(!z||z>max)return false;o.assign(v->valuestring,z);return true;}
bool optstr(const cJSON*p,const char*n,std::string&o,size_t max=256){if(!cJSON_GetObjectItemCaseSensitive(p,n)){o.clear();return true;}return str(p,n,o,max);}
bool num(const cJSON*p,const char*n,int64_t min,int64_t max,int64_t&o){auto*v=cJSON_GetObjectItemCaseSensitive(p,n);if(!cJSON_IsNumber(v)||v->valuedouble!=v->valueint||v->valueint<min||v->valueint>max)return false;o=v->valueint;return true;}
bool uuid(const std::string&s){if(s.size()!=36)return false;for(size_t i=0;i<s.size();i++){if(i==8||i==13||i==18||i==23){if(s[i]!='-')return false;}else if(!isxdigit((unsigned char)s[i]))return false;}return true;}
bool digest(const char*d,size_t z,std::string&o,uint8_t out[32]){if(mbedtls_sha256((const uint8_t*)d,z,out,0)!=0)return false;static constexpr char h[]="0123456789abcdef";o.resize(64);for(size_t i=0;i<32;i++){o[i*2]=h[out[i]>>4];o[i*2+1]=h[out[i]&15];}return true;}
EdgeProfile profile(const std::string&s){return s=="DATECS_DP150_BLUEPAD50"?EdgeProfile::DatecsDp150BluePad50:s=="DAISY_COMPACT_S01"?EdgeProfile::DaisyCompactS01:EdgeProfile::Unconfigured;}
bool compatible(const CompositeBinding&b){auto&f=b.fiscal;auto&p=b.payment;if(b.profile==EdgeProfile::DatecsDp150BluePad50)return f.vendor=="DATECS"&&f.model=="DP-150 MX"&&f.transport=="RS232"&&f.uart_baud>=1200&&f.uart_data_bits>=7&&f.uart_data_bits<=8&&(f.uart_parity=='N'||f.uart_parity=='E'||f.uart_parity=='O')&&(f.uart_stop_bits==1||f.uart_stop_bits==2)&&f.uart_tx_pin>=0&&f.uart_rx_pin>=0&&p.present&&p.vendor=="DATECS"&&p.model=="BLUEPAD-50 PLUS"&&p.transport=="BLE_GATT"&&!p.ble_identity.empty()&&!p.service_uuid.empty()&&!p.tx_characteristic_uuid.empty()&&!p.rx_characteristic_uuid.empty();if(b.profile==EdgeProfile::DaisyCompactS01)return f.vendor=="DAISY"&&f.model=="COMPACT S 01"&&f.transport=="USB_SERIAL"&&f.usb_vid&&f.usb_pid&&!p.present;return false;}
}
struct ProvisionedBindingStore::Impl{nvs_handle_t h{};bool open{};};
ProvisionedBindingStore::ProvisionedBindingStore(const char*p,const char*k):impl_(new Impl),public_key_(p),key_id_(k){}
ProvisionedBindingStore::~ProvisionedBindingStore(){close();delete impl_;}
const char*edge_profile_name(EdgeProfile p){return p==EdgeProfile::DatecsDp150BluePad50?"DATECS_DP150_BLUEPAD50":p==EdgeProfile::DaisyCompactS01?"DAISY_COMPACT_S01":"UNCONFIGURED";}
esp_err_t ProvisionedBindingStore::open(const char*n){if(!n||!*n||!public_key_||!strstr(public_key_,"BEGIN PUBLIC KEY")||!key_id_||!*key_id_)return ESP_ERR_INVALID_ARG;if(impl_->open)return ESP_OK;esp_err_t e=nvs_open(n,NVS_READWRITE,&impl_->h);if(e!=ESP_OK)return e;impl_->open=true;e=nvs_get_i64(impl_->h,"generation",&generation_);if(e==ESP_ERR_NVS_NOT_FOUND){generation_=0;return ESP_OK;}if(e!=ESP_OK)close();return e;}
void ProvisionedBindingStore::close(){if(impl_->open)nvs_close(impl_->h);impl_->open=false;impl_->h=0;generation_=0;}
esp_err_t ProvisionedBindingStore::decode_and_validate(const char*raw,size_t z,CompositeBinding&b){b={};if(!raw||!z||z>max_binding)return ESP_ERR_INVALID_ARG;Json root(cJSON_ParseWithLengthOpts(raw,z,nullptr,false));if(!root||!cJSON_IsObject(root.get())||!keys(root.get(),{"schema_version","generation","tenant_id","location_id","register_id","edge_device_id","profile","ble_advertising_identity","fiscal_endpoint","payment_endpoint","mqtt","operational_authority","local_http"}))return ESP_ERR_INVALID_ARG;int64_t schema=0;std::string pn;if(!num(root.get(),"schema_version",2,2,schema)||!num(root.get(),"generation",1,INT32_MAX,b.generation)||!str(root.get(),"tenant_id",b.tenant_id)||!str(root.get(),"location_id",b.location_id)||!str(root.get(),"register_id",b.register_id)||!str(root.get(),"edge_device_id",b.edge_device_id)||!str(root.get(),"profile",pn)||!str(root.get(),"ble_advertising_identity",b.ble_advertising_identity,29))return ESP_ERR_INVALID_ARG;b.schema_version=schema;b.profile=profile(pn);if(!uuid(b.tenant_id)||!uuid(b.location_id)||!uuid(b.register_id)||!uuid(b.edge_device_id)||b.profile==EdgeProfile::Unconfigured)return ESP_ERR_INVALID_ARG;
auto*f=obj(root.get(),"fiscal_endpoint");if(!f||!keys(f,{"device_id","vendor","model","transport","driver_id","protocol_id","protocol_version","uart","usb"})||!str(f,"device_id",b.fiscal.device_id)||!str(f,"vendor",b.fiscal.vendor,32)||!str(f,"model",b.fiscal.model,64)||!str(f,"transport",b.fiscal.transport,32)||!optstr(f,"driver_id",b.fiscal.driver_id,64)||!optstr(f,"protocol_id",b.fiscal.protocol_id,64)||!optstr(f,"protocol_version",b.fiscal.protocol_version,32)||!uuid(b.fiscal.device_id))return ESP_ERR_INVALID_ARG;
if(auto*u=obj(f,"uart")){if(!keys(u,{"baud","data_bits","parity","stop_bits","tx_pin","rx_pin"}))return ESP_ERR_INVALID_ARG;int64_t baud,data,stop,tx,rx;std::string parity;if(!num(u,"baud",1200,921600,baud)||!num(u,"data_bits",7,8,data)||!str(u,"parity",parity,1)||!num(u,"stop_bits",1,2,stop)||!num(u,"tx_pin",0,48,tx)||!num(u,"rx_pin",0,48,rx))return ESP_ERR_INVALID_ARG;b.fiscal.uart_baud=baud;b.fiscal.uart_data_bits=data;b.fiscal.uart_parity=parity[0];b.fiscal.uart_stop_bits=stop;b.fiscal.uart_tx_pin=tx;b.fiscal.uart_rx_pin=rx;}
if(auto*u=obj(f,"usb")){if(!keys(u,{"vid","pid","interface","serial"}))return ESP_ERR_INVALID_ARG;int64_t vid,pid,in;if(!num(u,"vid",1,65535,vid)||!num(u,"pid",1,65535,pid)||!num(u,"interface",0,255,in)||!optstr(u,"serial",b.fiscal.usb_serial,128))return ESP_ERR_INVALID_ARG;b.fiscal.usb_vid=vid;b.fiscal.usb_pid=pid;b.fiscal.usb_interface=in;}
auto*p=cJSON_GetObjectItemCaseSensitive(root.get(),"payment_endpoint");if(p&&!cJSON_IsNull(p)){if(!cJSON_IsObject(p)||!keys(p,{"device_id","vendor","model","transport","driver_id","protocol_id","protocol_version","ble_identity","service_uuid","tx_characteristic_uuid","rx_characteristic_uuid"}))return ESP_ERR_INVALID_ARG;b.payment.present=true;if(!str(p,"device_id",b.payment.device_id)||!str(p,"vendor",b.payment.vendor,32)||!str(p,"model",b.payment.model,64)||!str(p,"transport",b.payment.transport,32)||!optstr(p,"driver_id",b.payment.driver_id,64)||!optstr(p,"protocol_id",b.payment.protocol_id,64)||!optstr(p,"protocol_version",b.payment.protocol_version,32)||!str(p,"ble_identity",b.payment.ble_identity,128)||!str(p,"service_uuid",b.payment.service_uuid,64)||!str(p,"tx_characteristic_uuid",b.payment.tx_characteristic_uuid,64)||!str(p,"rx_characteristic_uuid",b.payment.rx_characteristic_uuid,64)||!uuid(b.payment.device_id))return ESP_ERR_INVALID_ARG;}
auto*m=obj(root.get(),"mqtt");if(!m||!keys(m,{"uri","client_id","command_topic","sync_topic","ack_topic","root_ca_ref","client_certificate_ref","client_key_ref"})||!str(m,"uri",b.mqtt.uri,512)||b.mqtt.uri.rfind("mqtts://",0)!=0||!str(m,"client_id",b.mqtt.client_id)||!str(m,"command_topic",b.mqtt.command_topic,512)||!str(m,"sync_topic",b.mqtt.sync_topic,512)||!str(m,"ack_topic",b.mqtt.ack_topic,512)||!str(m,"root_ca_ref",b.mqtt.root_ca_ref,64)||!str(m,"client_certificate_ref",b.mqtt.client_certificate_ref,64)||!str(m,"client_key_ref",b.mqtt.client_key_ref,64))return ESP_ERR_INVALID_ARG;
if(auto*l=obj(root.get(),"local_http")){if(!keys(l,{"enabled","port","token_issuer","token_signing_kid","token_public_key_der_base64","deployment_descriptor_url","deployment_signing_kid","deployment_public_key_base64"}))return ESP_ERR_INVALID_ARG;auto*enabled=cJSON_GetObjectItemCaseSensitive(l,"enabled");int64_t port=0;if(!cJSON_IsBool(enabled)||!num(l,"port",1,65535,port))return ESP_ERR_INVALID_ARG;b.local_http.enabled=cJSON_IsTrue(enabled);b.local_http.port=port;if(b.local_http.enabled&&(!str(l,"token_issuer",b.local_http.token_issuer,256)||!str(l,"token_signing_kid",b.local_http.token_signing_kid,128)||!str(l,"token_public_key_der_base64",b.local_http.token_public_key_der_base64,512)))return ESP_ERR_INVALID_ARG;if(!optstr(l,"deployment_descriptor_url",b.local_http.deployment_descriptor_url,512)||!optstr(l,"deployment_signing_kid",b.local_http.deployment_signing_kid,128)||!optstr(l,"deployment_public_key_base64",b.local_http.deployment_public_key_base64,128))return ESP_ERR_INVALID_ARG;}
auto*a=obj(root.get(),"operational_authority");int64_t start,end;if(!a||!keys(a,{"command_hmac_ref","sync_ack_hmac_ref","transaction_signing_kid","unp_prefix","unp_range_start","unp_range_end"})||!str(a,"command_hmac_ref",b.authority.command_hmac_ref,15)||!str(a,"sync_ack_hmac_ref",b.authority.sync_ack_hmac_ref,15)||!str(a,"transaction_signing_kid",b.authority.transaction_signing_kid,128)||!str(a,"unp_prefix",b.authority.unp_prefix,64)||!num(a,"unp_range_start",1,INT32_MAX,start)||!num(a,"unp_range_end",start,INT32_MAX,end)||!compatible(b))return ESP_ERR_INVALID_ARG;b.authority.unp_range_start=start;b.authority.unp_range_end=end;uint8_t d[32];return digest(raw,z,b.payload_sha256,d)?ESP_OK:ESP_FAIL;}
esp_err_t ProvisionedBindingStore::verify(const SignedBindingEnvelope&e)const{if(!e.canonical_json||!e.canonical_json_size||!e.signature_base64url||!e.key_id||strcmp(e.key_id,key_id_)!=0)return ESP_ERR_INVALID_ARG;std::string s=e.signature_base64url;for(char&c:s){if(c=='-')c='+';else if(c=='_')c='/';}while(s.size()%4)s+='=';std::vector<uint8_t>sig(512);size_t sn=0;if(mbedtls_base64_decode(sig.data(),sig.size(),&sn,(const uint8_t*)s.data(),s.size())!=0)return ESP_ERR_INVALID_CRC;uint8_t d[32];std::string h;if(!digest(e.canonical_json,e.canonical_json_size,h,d))return ESP_FAIL;mbedtls_pk_context pk;mbedtls_pk_init(&pk);int r=mbedtls_pk_parse_public_key(&pk,(const uint8_t*)public_key_,strlen(public_key_)+1);if(r==0)r=mbedtls_pk_verify(&pk,MBEDTLS_MD_SHA256,d,sizeof(d),sig.data(),sn);mbedtls_pk_free(&pk);return r==0?ESP_OK:ESP_ERR_INVALID_CRC;}
esp_err_t ProvisionedBindingStore::load(CompositeBinding&b){if(!impl_->open)return ESP_ERR_INVALID_STATE;size_t z=0;esp_err_t e=nvs_get_blob(impl_->h,"active",nullptr,&z);if(e!=ESP_OK)return e;if(!z||z>max_binding)return ESP_ERR_INVALID_SIZE;std::vector<char>raw(z);if((e=nvs_get_blob(impl_->h,"active",raw.data(),&z))!=ESP_OK||(e=decode_and_validate(raw.data(),z,b))!=ESP_OK)return e;return b.generation==generation_?ESP_OK:ESP_ERR_INVALID_STATE;}
esp_err_t ProvisionedBindingStore::install(const SignedBindingEnvelope&e,CompositeBinding*out){if(!impl_->open)return ESP_ERR_INVALID_STATE;CompositeBinding b;esp_err_t r;if((r=verify(e))!=ESP_OK||(r=decode_and_validate(e.canonical_json,e.canonical_json_size,b))!=ESP_OK)return r;if(b.generation<=generation_)return ESP_ERR_INVALID_VERSION;size_t oldz=0;if(nvs_get_blob(impl_->h,"active",nullptr,&oldz)==ESP_OK&&oldz){std::vector<char>old(oldz);if((r=nvs_get_blob(impl_->h,"active",old.data(),&oldz))!=ESP_OK||(r=nvs_set_blob(impl_->h,"previous",old.data(),oldz))!=ESP_OK)return r;}if((r=nvs_set_blob(impl_->h,"active",e.canonical_json,e.canonical_json_size))!=ESP_OK||(r=nvs_set_i64(impl_->h,"generation",b.generation))!=ESP_OK||(r=nvs_commit(impl_->h))!=ESP_OK)return r;generation_=b.generation;if(out)*out=std::move(b);return ESP_OK;}
}
