#include "sync_runtime.h"
#include "edge_runtime_port.h"
#include "cJSON.h"
#include "esp_random.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "mbedtls/base64.h"
#include "mbedtls/md.h"
#include "mbedtls/sha256.h"
#include <ctime>
#include <cstring>
#include <memory>
#include <algorithm>
#include <vector>
namespace beefiscal::idf{namespace{
struct State{DurableStorage*s{};const CompositeBinding*b{};DeviceIdentity*identity{};std::vector<uint8_t>ack_key;};State state;
struct Del{void operator()(cJSON*v)const{cJSON_Delete(v);}};using Json=std::unique_ptr<cJSON,Del>;
std::string hash(const char*p,size_t n){uint8_t d[32];mbedtls_sha256((const uint8_t*)p,n,d,0);static const char h[]="0123456789abcdef";std::string o(64,'0');for(size_t i=0;i<32;i++){o[i*2]=h[d[i]>>4];o[i*2+1]=h[d[i]&15];}return o;}
std::string print(cJSON*v){char*p=cJSON_PrintUnformatted(v);if(!p)return{};std::string o=p;cJSON_free(p);return o;}
std::string iso(int64_t t){char b[32];time_t x=t;tm value{};gmtime_r(&x,&value);strftime(b,sizeof(b),"%Y-%m-%dT%H:%M:%SZ",&value);return b;}
bool b64decode(const char*s,std::vector<uint8_t>&o){if(!s)return false;std::string v=s;for(char&c:v){if(c=='-')c='+';else if(c=='_')c='/';}while(v.size()%4)v+='=';o.resize(v.size());size_t n=0;if(mbedtls_base64_decode(o.data(),o.size(),&n,(uint8_t*)v.data(),v.size()))return false;o.resize(n);return n>=32;}
bool constant_equal(const uint8_t*a,const uint8_t*b,size_t n){uint8_t d=0;for(size_t i=0;i<n;i++)d|=a[i]^b[i];return d==0;}
std::string uuid(){uint8_t v[16];esp_fill_random(v,sizeof(v));v[6]=(v[6]&15)|0x40;v[8]=(v[8]&63)|0x80;char b[37];snprintf(b,sizeof(b),"%02x%02x%02x%02x-%02x%02x-%02x%02x-%02x%02x-%02x%02x%02x%02x%02x%02x",v[0],v[1],v[2],v[3],v[4],v[5],v[6],v[7],v[8],v[9],v[10],v[11],v[12],v[13],v[14],v[15]);return b;}
cJSON*event(const PendingEvent&e,const std::string&previous,std::string&event_hash,DeviceIdentity&identity){auto*v=cJSON_CreateObject();cJSON_AddStringToObject(v,"event_id",e.event_id.c_str());cJSON_AddStringToObject(v,"operation_id",e.operation_id.c_str());cJSON_AddStringToObject(v,"device_id",state.b->edge_device_id.c_str());cJSON_AddNumberToObject(v,"journal_seq",e.sequence);const char*kind=e.kind=="COMMAND_RECEIVED"?"ACCEPTED":e.kind=="RECEIPT_RESULT"?"FISCALIZED":"SNAPSHOT";Json payload(cJSON_Parse(e.payload.c_str()));if(payload){auto*s=cJSON_GetObjectItemCaseSensitive(payload.get(),"state");if(cJSON_IsString(s)){if(strcmp(s->valuestring,"RECOVERY_REQUIRED")==0)kind="RECOVERY_REQUIRED";else if(strcmp(s->valuestring,"REJECTED")==0)kind="FAILED";else if(strcmp(s->valuestring,"COMPENSATED")==0)kind="COMPENSATED";}}
  cJSON_AddStringToObject(v,"event_type",kind);auto at=iso(e.created_at);cJSON_AddStringToObject(v,"occurred_at",at.c_str());cJSON_AddItemToObject(v,"payload",payload?payload.release():cJSON_CreateObject());if(previous.empty())cJSON_AddNullToObject(v,"prev_hash");else cJSON_AddStringToObject(v,"prev_hash",previous.c_str());cJSON_AddStringToObject(v,"event_hash","");cJSON_AddNullToObject(v,"signature");const std::string unsigned_event=print(v);event_hash=hash(unsigned_event.data(),unsigned_event.size());cJSON_ReplaceItemInObject(v,"event_hash",cJSON_CreateString(event_hash.c_str()));std::string signature;if(identity.sign_hash_hex(event_hash.c_str(),signature)!=ESP_OK){cJSON_Delete(v);return nullptr;}cJSON_ReplaceItemInObject(v,"signature",cJSON_CreateString(signature.c_str()));return v;}
void worker(void*){uint32_t delay_ms=1000;for(;;){std::vector<PendingEvent>pending;state.s->pending(50,[&](const PendingEvent&e){pending.push_back(e);return true;});if(pending.empty()){state.s->prune_acknowledged(time(nullptr),93);delay_ms=1000;vTaskDelay(pdMS_TO_TICKS(1000));continue;}std::string previous=state.s->acknowledged_event_hash();auto*batch=cJSON_CreateObject();auto batch_id=uuid();cJSON_AddStringToObject(batch,"edge_id",state.b->edge_device_id.c_str());cJSON_AddStringToObject(batch,"schema_version","2026-08-07");cJSON_AddNumberToObject(batch,"first_seq",pending.front().sequence);cJSON_AddNumberToObject(batch,"last_seq",pending.back().sequence);if(previous.empty())cJSON_AddNullToObject(batch,"previous_acknowledged_hash");else cJSON_AddStringToObject(batch,"previous_acknowledged_hash",previous.c_str());auto*events=cJSON_AddArrayToObject(batch,"events");bool ok=true;for(auto&e:pending){std::string eh;auto*v=event(e,previous,eh,*state.identity);if(!v){ok=false;break;}cJSON_AddItemToArray(events,v);previous=eh;}cJSON_AddStringToObject(batch,"batch_sha256","");cJSON_AddStringToObject(batch,"signature","");std::string body=print(batch),batch_hash=hash(body.data(),body.size()),signature;if(ok&&state.identity->sign_hash_hex(batch_hash.c_str(),signature)==ESP_OK){cJSON_ReplaceItemInObject(batch,"batch_sha256",cJSON_CreateString(batch_hash.c_str()));cJSON_ReplaceItemInObject(batch,"signature",cJSON_CreateString(signature.c_str()));body=print(batch);int id=mqtt_publish_sync(batch_id.c_str(),(uint8_t*)body.data(),body.size());for(auto&e:pending)state.s->record_publish_attempt(e.event_id.c_str(),id<0?"MQTT_PUBLISH_FAILED":nullptr,time(nullptr));if(id>=0)delay_ms=1000;else delay_ms=(delay_ms < 15000u ? delay_ms * 2u : 30000u);}cJSON_Delete(batch);vTaskDelay(pdMS_TO_TICKS(delay_ms+(esp_random()%251)));}}
}
esp_err_t sync_runtime_start(DurableStorage&s,const CompositeBinding&b,DeviceIdentity&i,const char*key){if(!s.ready()||!i.ready()||!b64decode(key,state.ack_key))return ESP_ERR_INVALID_ARG;state.s=&s;state.b=&b;state.identity=&i;return xTaskCreate(worker,"edge-sync",12288,nullptr,7,nullptr)==pdPASS?ESP_OK:ESP_ERR_NO_MEM;}
esp_err_t sync_runtime_accept_ack(const uint8_t*data,size_t n,void*){if(!state.s||!data||!n||n>8192)return ESP_ERR_INVALID_ARG;Json root(cJSON_ParseWithLengthOpts((char*)data,n,nullptr,false));if(!root)return ESP_ERR_INVALID_ARG;auto*sig=cJSON_GetObjectItemCaseSensitive(root.get(),"signature");auto*edge=cJSON_GetObjectItemCaseSensitive(root.get(),"edge_id");auto*id=cJSON_GetObjectItemCaseSensitive(root.get(),"ack_id");auto*seq=cJSON_GetObjectItemCaseSensitive(root.get(),"committed_through_seq");auto*eh=cJSON_GetObjectItemCaseSensitive(root.get(),"committed_event_hash");if(!cJSON_IsString(sig)||!cJSON_IsString(edge)||!cJSON_IsString(id)||!cJSON_IsNumber(seq)||!cJSON_IsString(eh)||state.b->edge_device_id!=edge->valuestring)return ESP_ERR_INVALID_ARG;std::vector<uint8_t>provided;if(!b64decode(sig->valuestring,provided))return ESP_ERR_INVALID_CRC;cJSON_SetValuestring(sig,"");auto unsigned_body=print(root.get());uint8_t mac[32];mbedtls_md_context_t ctx;mbedtls_md_init(&ctx);auto*info=mbedtls_md_info_from_type(MBEDTLS_MD_SHA256);int e=mbedtls_md_setup(&ctx,info,1);if(!e)e=mbedtls_md_hmac_starts(&ctx,state.ack_key.data(),state.ack_key.size());if(!e)e=mbedtls_md_hmac_update(&ctx,(uint8_t*)unsigned_body.data(),unsigned_body.size());if(!e)e=mbedtls_md_hmac_finish(&ctx,mac);mbedtls_md_free(&ctx);if(e||provided.size()!=32||!constant_equal(mac,provided.data(),32))return ESP_ERR_INVALID_CRC;return state.s->acknowledge_through(seq->valueint,id->valuestring,eh->valuestring,time(nullptr));}
}
