// Code generated by scripts/generate_response_contracts.rb; DO NOT EDIT.
package localapi

var generatedSuccessResponses = []successResponseContract{
	{Method: "POST", Path: "/internal/v1/commands", Operation: "executeCanonicalEdgeCommandForHIL", Status: 200, Media: []string{"application/json"}, Schema: `{"type":"object","additionalProperties":false,"required":["command_id","state"],"properties":{"command_id":{"type":"string"},"state":{"type":"string","enum":["FISCALIZED","FAILED","FISCAL_RESULT_UNKNOWN","BLOCKED"]},"fiscal_reference":{"type":"string"},"error_code":{"type":"string"},"operation_sequence":{"type":"integer","minimum":1},"unp_sequence":{"type":"integer","minimum":1}}}`},
	{Method: "GET", Path: "/internal/v1/final-device", Operation: "probeFinalDeviceForHIL", Status: 200, Media: []string{"application/json"}, Schema: `{"type":"object","additionalProperties":false,"required":["state"],"properties":{"state":{"type":"string","enum":["READY","BLOCK"]},"error_code":{"type":"string","enum":["FISCAL_DEVICE_UNREACHABLE"]}}}`},
	{Method: "GET", Path: "/internal/v1/storage", Operation: "getEdgeStorageStatusForHIL", Status: 200, Media: []string{"application/json"}, Schema: `{"type":"object","additionalProperties":false,"required":["used_bytes","quota_bytes","percent","state"],"properties":{"used_bytes":{"type":"integer","minimum":0},"quota_bytes":{"type":"integer","minimum":1},"percent":{"type":"integer","minimum":0},"state":{"type":"string","enum":["NORMAL","WARNING","HIGH","CRITICAL","FULL"]}}}`},
}

var generatedRequestContracts = []requestContract{
	{Method: "POST", Path: "/internal/v1/commands", Operation: "executeCanonicalEdgeCommandForHIL", Required: true, Media: []string{"application/json"}, Schema: `{"type":"object","additionalProperties":false,"required":["command_id","tenant_id","register_id","device_id","type","fencing_token","payload"],"properties":{"command_id":{"type":"string"},"tenant_id":{"type":"string"},"register_id":{"type":"string"},"device_id":{"type":"string"},"type":{"type":"string"},"fencing_token":{"type":"integer","minimum":1},"payload":{"type":"object"}}}`, Parameters: `[]`},
	{Method: "GET", Path: "/internal/v1/final-device", Operation: "probeFinalDeviceForHIL", Required: false, Media: []string{}, Schema: "", Parameters: `[]`},
	{Method: "GET", Path: "/internal/v1/storage", Operation: "getEdgeStorageStatusForHIL", Required: false, Media: []string{}, Schema: "", Parameters: `[]`},
}

const generatedProblemResponseSchema = `{"type":"object","required":["type","title","status","code","retryable","trace_id"],"properties":{"type":{"type":"string","format":"uri"},"title":{"type":"string"},"status":{"type":"integer"},"code":{"type":"string"},"category":{"type":"string","enum":["VALIDATION","AUTH","CONFLICT","DEVICE","PAYMENT","COMPLIANCE","TRANSPORT","INTERNAL"]},"retryable":{"type":"boolean"},"detail":{"type":"string"},"trace_id":{"type":"string"}}}`
