#include "FrameCodec.hpp"
#include "FiscalDriver.hpp"
#include <cassert>
#include <vector>
using namespace bee;
static std::vector<uint8_t>daisyResponse(){std::vector<uint8_t>v{1,0x2a,0x20,74,4,0x80,0x80,0x80,0x80,0x80,0x80,5};uint16_t s=0;for(size_t i=1;i<v.size();i++)s+=v[i];const char*h="0123456789ABCDEF";v.push_back(h[(s>>12)&15]);v.push_back(h[(s>>8)&15]);v.push_back(h[(s>>4)&15]);v.push_back(h[s&15]);v.push_back(3);return v;}
static void addWord(std::vector<uint8_t>&v,uint16_t x){for(int n:{12,8,4,0})v.push_back(uint8_t(((x>>n)&15)+0x30));}
static std::vector<uint8_t>datecsResponse(){std::vector<uint8_t>v{1};addWord(v,0x2f);v.push_back(0x20);addWord(v,74);v.push_back(4);for(int i=0;i<8;i++)v.push_back(0x80);v.push_back(5);uint16_t s=0;for(size_t i=1;i<v.size();i++)s+=v[i];addWord(v,s);v.push_back(3);return v;}
int main(){auto d=DaisyCodec::encode(0x20,48,{'1',',','0'});assert(d.size()==13&&d.front()==1&&d.back()==3);ParsedFrame p;std::string e;auto dr=daisyResponse();assert(DaisyCodec::decode(dr,p,e)&&p.command==74&&p.status.size()==6);dr[12]^=1;assert(!DaisyCodec::decode(dr,p,e)&&e=="DAISY_BCC");auto x=DatecsCodec::encode(0x20,48,{'1','\t','1'});assert(x.size()==19&&x.front()==1&&x.back()==3);auto xr=datecsResponse();assert(DatecsCodec::decode(xr,p,e)&&p.command==74&&p.status.size()==8);xr[20]^=1;assert(!DatecsCodec::decode(xr,p,e));assert(isDatecsDocumented(255)&&isDatecsDocumented(43)&&!isDatecsDocumented(34));assert(isDaisyDocumented(201)&&isDaisyDocumented(130)&&!isDaisyDocumented(34));for(size_t i=0;i<73;i++){if(i)assert(DatecsAllCommands[i]>DatecsAllCommands[i-1]);CommandSpec s{};assert(datecsCommandSpec(DatecsAllCommands[i],s)&&s.code==DatecsAllCommands[i]);}for(size_t i=0;i<88;i++){if(i)assert(DaisyAllCommands[i]>DaisyAllCommands[i-1]);CommandSpec s{};assert(daisyCommandSpec(DaisyAllCommands[i],s)&&s.code==DaisyAllCommands[i]);}CommandSpec s{};assert(datecsCommandSpec(55,s)&&s.disposition==Disposition::Excluded);assert(daisyCommandSpec(194,s)&&s.disposition==Disposition::Excluded);assert(!datecsCommandSpec(34,s)&&!daisyCommandSpec(34,s));}
