#pragma once
#define SQLITE_OMIT_LOAD_EXTENSION 1
#define SQLITE_DQS 0
#define SQLITE_TEMP_STORE 2
#define SQLITE_DEFAULT_MEMSTATUS 0
#define SQLITE_DEFAULT_MMAP_SIZE 0
#define SQLITE_THREADSAFE 1
#define SQLITE_OMIT_WAL 1
#define SQLITE_DEFAULT_FOREIGN_KEYS 1
#define SQLITE_DEFAULT_PAGE_SIZE 4096
#define SQLITE_DEFAULT_CACHE_SIZE -128
#define SQLITE_MAX_EXPR_DEPTH 0
#define lstat stat
