/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/platform/v1/external-systems": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listExternalSystems"];
        put?: never;
        post: operations["createExternalSystem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/platform/v1/external-systems/{system_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                system_id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateExternalSystem"];
        trace?: never;
    };
    "/platform/v1/external-systems/{system_id}:rotate-key": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["rotateExternalSystemKey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/platform/v1/external-systems/{system_id}:suspend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["suspendExternalSystem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/platform/v1/external-systems/{system_id}:resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["resumeExternalSystem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/platform/v1/external-systems/{system_id}/audit-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listExternalSystemAudit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/platform/v1/external-systems/{system_id}/tenant-bindings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listExternalSystemBindings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/platform/v1/external-systems/{system_id}/webhook-deliveries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listExternalSystemDeliveries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/platform/v1/webhook-deliveries/{delivery_id}:requeue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["requeueWebhookDelivery"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/platform/v1/integration-metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getIntegrationMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/platform/v1/enrollment-conflicts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listEnrollmentConflicts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/platform/v1/enrollment-conflicts/{challenge_id}:resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["resolveEnrollmentConflict"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/integration/v1/enrollments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["startEnrollment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/integration/v1/enrollments:verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["verifyEnrollment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/integration/v1/credentials:recover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["startCredentialRecovery"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/integration/v1/credentials:recover-verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["verifyCredentialRecovery"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/integration/v1/organization": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["putOrganization"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/integration/v1/locations/{source_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: components["parameters"]["SourceId"];
            };
            cookie?: never;
        };
        get?: never;
        put: operations["putLocation"];
        post?: never;
        delete: operations["deleteLocation"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/integration/v1/registers/{source_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: components["parameters"]["SourceId"];
            };
            cookie?: never;
        };
        get?: never;
        put: operations["putRegister"];
        post?: never;
        delete: operations["deleteRegister"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/integration/v1/operators/{source_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: components["parameters"]["SourceId"];
            };
            cookie?: never;
        };
        get?: never;
        put: operations["putOperator"];
        post?: never;
        delete: operations["deleteOperator"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/integration/v1/operations/{operation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getIntegrationOperation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/integration/v1/credentials:rotate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["rotateTenantCredential"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/integration/v1/credentials:revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["revokeTenantCredential"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/integration/v1/binding": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateSourceCompanyId"];
        trace?: never;
    };
}
export interface webhooks {
    integrationCommandUpdated: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["receiveIntegrationCommandUpdate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export interface components {
    schemas: {
        ExternalSystemInput: {
            code: string;
            display_name: string;
            /** Format: uri */
            webhook_url: string;
            webhook_events: "integration.command.updated"[];
        };
        ExternalSystemUpdate: {
            display_name: string;
            /** Format: uri */
            webhook_url: string;
            webhook_events: "integration.command.updated"[];
            version: number;
        };
        TaxIdentifier: {
            country: string;
            type: string;
            value: string;
        };
        EnrollmentRequest: {
            /** Format: email */
            email: string;
            source_company_id: string;
            company: {
                legal_name: string;
                tax_identifier: components["schemas"]["TaxIdentifier"];
                address?: string;
            };
        };
        EnrollmentChallenge: {
            temporary_token: string;
            /** Format: date-time */
            expires_at: string;
            /** Format: date-time */
            resend_after: string;
        };
        CredentialRecoveryRequest: {
            /** Format: email */
            email: string;
            tax_identifier: components["schemas"]["TaxIdentifier"];
        };
        OrganizationResource: {
            legal_name: string;
            tax_identifier: components["schemas"]["TaxIdentifier"];
            address?: string;
            /** @enum {unknown} */
            status?: "ACTIVE" | "INACTIVE";
        };
        LocationResource: {
            code?: string;
            name: string;
            address: string;
            /** @enum {unknown} */
            status?: "ACTIVE" | "INACTIVE";
        };
        RegisterResource: {
            code?: string;
            name: string;
            location_source_id: string;
            /** @enum {unknown} */
            status?: "ACTIVE" | "BLOCKED" | "INACTIVE";
        };
        OperatorResource: {
            operator_code: string;
            first_name: string;
            last_name: string;
            roles: ("CASHIER" | "SUPERVISOR" | "ADMIN" | "AUDITOR" | "SERVICE")[];
            /** @enum {unknown} */
            status?: "ACTIVE" | "INACTIVE";
            /** Format: date-time */
            active_from?: string;
        };
        EnrollmentResult: {
            /** Format: uuid */
            tenant_id: string;
            /** Format: uuid */
            source_system_id: string;
            source_company_id: string;
            access_token: string;
            /** @constant */
            token_type: "Bearer";
            scopes: string[];
        };
        AcceptedOperation: {
            /** Format: uuid */
            operation_id: string;
            /** @constant */
            status: "ACCEPTED";
            /** Format: uri */
            status_url: string;
            /** Format: date-time */
            accepted_at: string;
        };
        Operation: {
            /** Format: uuid */
            operation_id: string;
            /** @enum {string} */
            status: "ACCEPTED" | "QUEUED" | "PROCESSING" | "SUCCEEDED" | "FAILED" | "DEAD" | "SUPERSEDED";
            resource_type: string;
            source_entity_id: string;
            source_version: number;
            result?: Record<string, never>;
        };
        WebhookEvent: {
            /** Format: uuid */
            event_id: string;
            /** @constant */
            event_type: "integration.command.updated";
            /** Format: uuid */
            source_system_id: string;
            /** Format: uuid */
            tenant_id: string;
            /** Format: uuid */
            operation_id: string;
            resource_type?: string;
            source_entity_id?: string;
            source_version?: number;
            status: string;
            result?: Record<string, never>;
            error?: Record<string, never> | null;
            /** Format: date-time */
            occurred_at: string;
        };
        Error: {
            error: {
                /** @enum {string} */
                code: "INVALID_REQUEST" | "CREDENTIAL_INVALID" | "RATE_LIMITED" | "INTEGRATION_CONFLICT" | "NOT_FOUND" | "SYSTEM_SUSPENDED" | "ENROLLMENT_EXPIRED" | "ENROLLMENT_CODE_INVALID" | "ENROLLMENT_LOCKED" | "SOURCE_VERSION_CONFLICT" | "COMMAND_PAYLOAD_CONFLICT" | "WEBHOOK_DELIVERY_DEAD";
                message: string;
            };
        };
    };
    responses: {
        /** @description Durably accepted */
        Accepted: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["AcceptedOperation"];
            };
        };
        /** @description Stable error */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        IdempotencyKey: string;
        SourceVersion: number;
        ActorType: "USER" | "SERVICE";
        ActorId: string;
        SourceId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listExternalSystems: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description External systems */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createExternalSystem: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExternalSystemInput"];
            };
        };
        responses: {
            /** @description System and reveal-once bootstrap token */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    updateExternalSystem: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                system_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExternalSystemUpdate"];
            };
        };
        responses: {
            /** @description Updated system */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            409: components["responses"]["Error"];
        };
    };
    rotateExternalSystemKey: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                system_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reveal-once replacement key */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["Error"];
        };
    };
    suspendExternalSystem: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                system_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Suspended */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    resumeExternalSystem: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                system_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listExternalSystemAudit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                system_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Append-only audit events */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listExternalSystemBindings: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                system_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tenant bindings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listExternalSystemDeliveries: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                system_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Delivery and attempt journal */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    requeueWebhookDelivery: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                delivery_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dead delivery requeued */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            409: components["responses"]["Error"];
        };
    };
    getIntegrationMetrics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Queue, security and conflict metrics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listEnrollmentConflicts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Conflicts awaiting decision */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    resolveEnrollmentConflict: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                challenge_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {unknown} */
                    decision: "KEEP_EXISTING" | "REPLACE_EXISTING";
                    reason: string;
                };
            };
        };
        responses: {
            /** @description Decision applied */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["Error"];
        };
    };
    startEnrollment: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnrollmentRequest"];
            };
        };
        responses: {
            /** @description OTP challenge created */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrollmentChallenge"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    verifyEnrollment: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    code: string;
                };
            };
        };
        responses: {
            /** @description Tenant binding and reveal-once credential */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrollmentResult"];
                };
            };
            401: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    startCredentialRecovery: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CredentialRecoveryRequest"];
            };
        };
        responses: {
            /** @description Generic OTP recovery challenge */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrollmentChallenge"];
                };
            };
            401: components["responses"]["Error"];
            429: components["responses"]["Error"];
        };
    };
    verifyCredentialRecovery: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    code: string;
                };
            };
        };
        responses: {
            /** @description Rotated reveal-once tenant credential */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrollmentResult"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    putOrganization: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                "Source-Version": components["parameters"]["SourceVersion"];
                "BeeFiscal-Source-Actor-Type": components["parameters"]["ActorType"];
                "BeeFiscal-Source-Actor-Id": components["parameters"]["ActorId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrganizationResource"];
            };
        };
        responses: {
            202: components["responses"]["Accepted"];
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    putLocation: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                "Source-Version": components["parameters"]["SourceVersion"];
                "BeeFiscal-Source-Actor-Type": components["parameters"]["ActorType"];
                "BeeFiscal-Source-Actor-Id": components["parameters"]["ActorId"];
            };
            path: {
                source_id: components["parameters"]["SourceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LocationResource"];
            };
        };
        responses: {
            202: components["responses"]["Accepted"];
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    deleteLocation: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                "Source-Version": components["parameters"]["SourceVersion"];
                "BeeFiscal-Source-Actor-Type": components["parameters"]["ActorType"];
                "BeeFiscal-Source-Actor-Id": components["parameters"]["ActorId"];
            };
            path: {
                source_id: components["parameters"]["SourceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            202: components["responses"]["Accepted"];
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    putRegister: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                "Source-Version": components["parameters"]["SourceVersion"];
                "BeeFiscal-Source-Actor-Type": components["parameters"]["ActorType"];
                "BeeFiscal-Source-Actor-Id": components["parameters"]["ActorId"];
            };
            path: {
                source_id: components["parameters"]["SourceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterResource"];
            };
        };
        responses: {
            202: components["responses"]["Accepted"];
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    deleteRegister: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                "Source-Version": components["parameters"]["SourceVersion"];
                "BeeFiscal-Source-Actor-Type": components["parameters"]["ActorType"];
                "BeeFiscal-Source-Actor-Id": components["parameters"]["ActorId"];
            };
            path: {
                source_id: components["parameters"]["SourceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            202: components["responses"]["Accepted"];
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    putOperator: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                "Source-Version": components["parameters"]["SourceVersion"];
                "BeeFiscal-Source-Actor-Type": components["parameters"]["ActorType"];
                "BeeFiscal-Source-Actor-Id": components["parameters"]["ActorId"];
            };
            path: {
                source_id: components["parameters"]["SourceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OperatorResource"];
            };
        };
        responses: {
            202: components["responses"]["Accepted"];
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    deleteOperator: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                "Source-Version": components["parameters"]["SourceVersion"];
                "BeeFiscal-Source-Actor-Type": components["parameters"]["ActorType"];
                "BeeFiscal-Source-Actor-Id": components["parameters"]["ActorId"];
            };
            path: {
                source_id: components["parameters"]["SourceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            202: components["responses"]["Accepted"];
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    getIntegrationOperation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                operation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Operation state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Operation"];
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    rotateTenantCredential: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reveal-once replacement credential */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrollmentResult"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    revokeTenantCredential: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                "BeeFiscal-Source-Actor-Type": components["parameters"]["ActorType"];
                "BeeFiscal-Source-Actor-Id": components["parameters"]["ActorId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Credential immediately revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
        };
    };
    updateSourceCompanyId: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                "BeeFiscal-Source-Actor-Type": components["parameters"]["ActorType"];
                "BeeFiscal-Source-Actor-Id": components["parameters"]["ActorId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    source_company_id: string;
                    expected_version: number;
                };
            };
        };
        responses: {
            /** @description Binding updated and journaled */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            409: components["responses"]["Error"];
        };
    };
    receiveIntegrationCommandUpdate: {
        parameters: {
            query?: never;
            header: {
                "BeeFiscal-Event-Id": string;
                "BeeFiscal-Source-System-Id": string;
                "BeeFiscal-Delivery-Id": string;
                "BeeFiscal-Signature": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WebhookEvent"];
            };
        };
        responses: {
            /** @description Accepted and durably deduplicated */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
