import test from "node:test";
import assert from "node:assert/strict";
import {fiscalCheckout,probeFinalDevice} from "./fiscalCheckout.ts";
import type {TransportSnapshot} from "./transport.ts";

const id="00112233-4455-4677-8899-aabbccddeeff",now=new Date().toISOString(),sale={external_id:"order",operator_id:"A001",currency:"EUR" as const,items:[{name:"Coffee"}],payments:[{type:"CASH"}],metadata:{}},binding={tenant_id:"tenant",register_id:"register",edge_id:"edge",binding_version:7,expires_at:new Date(Date.now()+60000).toISOString()};
const base:TransportSnapshot={cloudRoute:"READY",bleAdapter:"READY",edgeRuntime:"READY",fiscalDevice:"READY",bleSessionExpiresAt:binding.expires_at,observedAt:now};
test("REST route consumes the OpenAPI MiniPosFiscalOperation and never touches BLE",async()=>{let ble=0;const out=await fiscalCheckout(base,id,sale,binding,async()=>({state:"FISCALIZED",operation_id:"rest-op",fiscal_reference:"FD-REST-1"}),{sendFiscalCommandAndWait:async()=>{ble++;return{operation_id:id,state:"FISCALIZED"}}} as any);assert.equal(out.route,"REST");assert.equal(out.fiscalReference,"FD-REST-1");assert.equal(ble,0)});
test("cloud outage sends canonical offline command and waits for final result",async()=>{let envelope:any;const out=await fiscalCheckout({...base,cloudRoute:"UNAVAILABLE"},id,sale,binding,async()=>{throw new Error("REST must not run")},{sendFiscalCommandAndWait:async(v:any)=>{envelope=v;return{operation_id:id,state:"FISCALIZED",fiscal_reference:"FD-1"}}} as any);assert.equal(out.route,"BLE");assert.equal(out.state,"COMPLETED");assert.equal(envelope.fencing_token,7);assert.match(envelope.payload_sha256,/^[a-f0-9]{64}$/)});
test("OpenAPI UNKNOWN REST and unknown BLE result require reconciliation",async()=>{const rest=await fiscalCheckout(base,id,sale,binding,async()=>({state:"UNKNOWN",operation_id:"rest-op"}),{} as any);assert.equal(rest.state,"UNKNOWN");assert.equal(rest.requiredAction,"RECONCILE");const local=await fiscalCheckout({...base,cloudRoute:"UNAVAILABLE"},id,sale,binding,async()=>({state:"FISCALIZED",operation_id:"unused"}),{sendFiscalCommandAndWait:async()=>({operation_id:id,state:"FISCAL_RESULT_UNKNOWN"})} as any);assert.equal(local.state,"UNKNOWN");assert.equal(local.requiredAction,"RECONCILE")});
test("known REST and BLE rejection are final failures, not ambiguous outcomes",async()=>{const rest=await fiscalCheckout(base,id,sale,binding,async()=>({state:"FAILED",operation_id:"rest-op"}),{} as any);assert.equal(rest.state,"FAILED");assert.equal(rest.requiredAction,undefined);const local=await fiscalCheckout({...base,cloudRoute:"UNAVAILABLE"},id,sale,binding,async()=>({state:"FISCALIZED",operation_id:"unused"}),{sendFiscalCommandAndWait:async()=>({operation_id:id,state:"REJECTED",error_code:"PAPER_OUT"})} as any);assert.equal(local.state,"FAILED");assert.equal(local.reason,"PAPER_OUT");assert.equal(local.requiredAction,undefined)});
test("final-device probe uses a short-lived non-fiscal command",async()=>{let envelope:any;const ready=await probeFinalDevice(id,binding,{sendFiscalCommandAndWait:async(v:any)=>{envelope=v;return{operation_id:id,state:"READY"}}} as any);assert.equal(ready,true);assert.equal(envelope.command_type,"DEVICE_PROBE");assert.ok(new Date(envelope.expires_at).getTime()-new Date(envelope.issued_at).getTime()===15000)});
