import assert from "node:assert/strict";
import test from "node:test";
import {chooseTransport} from "./transport.ts";
import type {TransportSnapshot} from "./transport.ts";
const now=new Date("2026-08-07T10:00:00Z");
const base:TransportSnapshot={cloudRoute:"READY",bleAdapter:"READY",edgeRuntime:"READY",fiscalDevice:"READY",bleSessionExpiresAt:"2026-08-07T11:00:00Z",observedAt:now.toISOString()};
test("REST is preferred while the cloud path is healthy",()=>assert.equal(chooseTransport(base,now).transport,"REST"));
test("cloud loss switches to BLE only with a valid session and live end device",()=>assert.equal(chooseTransport({...base,cloudRoute:"UNAVAILABLE"},now).transport,"BLE"));
test("loss of final fiscal device always blocks, even when BLE remains connected",()=>{const d=chooseTransport({...base,cloudRoute:"UNAVAILABLE",fiscalDevice:"UNAVAILABLE"},now);assert.equal(d.transport,"BLOCK");assert.equal(d.reason,"FISCAL_DEVICE_UNREACHABLE")});
test("expired session blocks local execution",()=>assert.equal(chooseTransport({...base,cloudRoute:"UNAVAILABLE",bleSessionExpiresAt:"2026-08-07T09:00:00Z"},now).transport,"BLOCK"));
test("transport and fiscal-device metrics remain separate",()=>{const d=chooseTransport({...base,cloudRoute:"DEGRADED",fiscalDevice:"UNKNOWN"},now);assert.equal(d.transportMetrics.cloudRoute,"DEGRADED");assert.equal(d.fiscalDeviceMetrics.state,"UNKNOWN")});
